--- Horse Collision Overhaul for Kingdom Come: Deliverance.
--
-- Gives mounted collisions a reaction proportional to the horse's gait. In
-- vanilla, riding into an NPC produces only an audio bark and no animation at
-- any speed. This module adds three tiers:
--
-- * **Walk** - the NPC plays a full standing stagger animation and is not
--   knocked down. No health damage, and the vanilla bark still fires.
-- * **Trot** - a physics ragdoll at reduced impulse.
-- * **Gallop** - a physics ragdoll at full impulse.
--
-- At trot and gallop the horse also loses stamina, and dismounts Henry when
-- spent. That is the anti-bulldozing budget: riding through a crowd has to
-- end with Henry on the ground rather than being a free way to scatter a
-- dozen people.
--
-- ## How the walk stagger works
--
-- This part has no precedent in other KCD mods, so it is worth stating
-- plainly. Lua cannot drive an NPC's animation directly. Everything obvious
-- was tried and fails silently: `human:PlayAnim` is accepted but never
-- renders, physics impulses are ignored because actors are animation-driven,
-- `soul:DealDamage` only moves stat numbers, and the `hitReaction` and
-- `combat:hit` brain messages reach a behavior tree that cannot drive the
-- body.
--
-- What does work is `actor:StartInteractiveActionByName`, the call vanilla
-- uses to make an actor mime opening a door. It takes over the body, plays a
-- whole animation, and hands control back. Its name argument resolves against
-- the FragTags of exactly one Mannequin fragment, `AnimationControlled`,
-- where vanilla ships only object interactions.
--
-- So the mod adds its own entries there. Four data files ship alongside this
-- script, all generated by `build_adb.py`, and all four are required:
--
-- 1. `kcd_male_database.adb` - adds `hcm_stagger_*` options pointing at
--    `hitreaction_idle_medium_torso_stab_*`, a standing hit reaction the game
--    already contains.
-- 2. `kcd_animationControlledTags.xml` - declares those FragTags. An option
--    whose tag is not declared aborts after one frame.
-- 3. `wh_female_fragmentids.xml` - declares `AnimationControlled` for women,
--    who have the same clips but no such fragment in vanilla.
-- 4. `wh_female_database.adb` - the fragment block itself, added wholesale.
--
-- See `docs/TESTING_DIARY.md` for the full investigation.
--
-- ## Limitations
--
-- * Dogs and other animals do not react. They use separate animation
--   databases which this mod does not touch.
-- * Ships full replacements of the male and female animation databases, so
--   it conflicts with any mod that edits human animations.
--
-- @module HorseCollisionMod
-- @author jrandall54
-- @release 2.0.1

HorseCollisionMod = {}

HorseCollisionMod.Version = "2.0.1"

--- Tuning values. Safe to edit in place; nothing here is derived at runtime.
--
-- @field SpeedWalk lower bound of the walk tier, in meters per second
-- @field SpeedTrot lower bound of the trot tier
-- @field SpeedGallop lower bound of the gallop tier
-- @field HitRadius radius of the broad-phase sphere around the horse
-- @field HorseFrontReach how far ahead of the horse origin counts as a hit
-- @field HorseRearReach how far behind the horse origin counts as a hit
-- @field HorseHalfWidth lateral half-width of the horse footprint
-- @field HorseMaxVerticalDiff height difference above which a hit is ignored
-- @field TickSeconds detection interval, used to sweep the footprint forward
-- @field SweepMultiplier how far ahead to sweep, per meter per second
-- @field MaxSweepExtra cap on the forward sweep, in meters
-- @field HitCooldownMs minimum gap between reactions on the same victim
-- @field Knockback horizontal ragdoll impulse at full strength
-- @field Uplift vertical ragdoll impulse at full strength
-- @field ProtectMutt when true, Henry's dog is never a valid victim
-- @field StaminaDrainWalk horse stamina cost per victim at walk
-- @field StaminaDrainTrot horse stamina cost per victim at trot
-- @field StaminaDrainGallop horse stamina cost per victim at gallop
-- @field ThrowRiderOnStaminaEmpty dismount Henry when the horse is spent
-- @field CombatStaminaMultiplier stamina cost multiplier while in a fight
-- @field SuppressStaggerInCombat skip the stagger animation during a fight
-- @field SendHitReaction post the native brain message so barks still fire
-- @field WalkStagger whether the walk tier plays a stagger animation
-- @field LogTelemetry write diagnostics to kcd.log
-- @table Config
HorseCollisionMod.Config = {
	-- KCD horses have three speed plateaus, not four. Telemetry across 90+
	-- logged impacts clustered at 2.05-3.74, 6.38-7.03 and 9.18-10.81 m/s,
	-- so these thresholds sit in the empty gaps between those clusters.
	SpeedWalk = 1.8,
	SpeedTrot = 4.5,
	SpeedGallop = 8.5,
	-- Broad-phase cull only. Everything inside this sphere is then tested
	-- against the horse footprint below, so this can stay generous without
	-- NPCs reacting from an unnatural distance.
	HitRadius = 2.5,
	HitCooldownMs = 3000,
	-- Horse footprint, in meters from the horse's origin. A horse is long
	-- and narrow, so a sphere catches people alongside and behind it who
	-- were never actually struck.
	--
	-- Tuned from 103 logged impacts rather than from guessed dimensions.
	-- Lateral distances were pressed hard against the previous 0.55 cap
	-- (median 0.30, 90th percentile 0.51), which is what let NPCs half a
	-- meter clear of the flank still react. 0.35 is about a horse chest's
	-- half-width and keeps the impacts genuinely in front of the animal.
	HorseFrontReach = 1.05,
	HorseRearReach = 0.20,
	HorseHalfWidth = 0.35,
	HorseMaxVerticalDiff = 2.35,
	-- The footprint is extended forward by the distance the horse covers in
	-- one tick, so victims are not missed between frames.
	--
	-- This was the single biggest cause of over-reach: 45 of 103 logged
	-- impacts landed beyond the front reach and were admitted by the sweep
	-- alone, which sat pinned at its old 0.95 cap a quarter of the time and
	-- pushed the effective reach out past two meters. Halved and capped
	-- much lower; it only needs to cover one tick of travel, not a stride.
	TickSeconds = 0.1,
	SweepMultiplier = 0.50,
	MaxSweepExtra = 0.35,
	Knockback = 50.0,
	Uplift = 30.0,
	ProtectMutt = true,
	-- Measured against a full horse stamina pool of 210. At these values a
	-- gallop costs roughly three bodies and a trot roughly five before the
	-- horse is spent and Henry is thrown. The previous 20/40 allowed ten
	-- and five, which made plowing through a crowd close to free.
	-- A walking bump is not hard enough to tire a horse at all.
	StaminaDrainWalk = 0.0,
	StaminaDrainTrot = 45.0,
	StaminaDrainGallop = 75.0,
	ThrowRiderOnStaminaEmpty = true,
	-- Stamina cost is multiplied by this while the player is in a fight.
	--
	-- Riding through a market at speed is meant to be fun and cheap. Using
	-- the horse as a crowd-control weapon mid-battle is not: without this,
	-- charging a group of four leaves them ragdolled and the rider free to
	-- shoot or swing at no cost. At 2.5 a galloping charge into combat
	-- spends the horse in a single impact, so it is a committed move rather
	-- than a repeatable one.
	CombatStaminaMultiplier = 2.5,
	-- Skip the stagger animation while the player is fighting.
	--
	-- The stagger hands the victim's body to an interactive action, which
	-- pulls them out of their combat behavior. On return they have lost
	-- track of the player and bark lines like "Where did he go?" while he
	-- is standing in front of them. Suppressing it in combat keeps their
	-- perception intact; the knockdown tiers are unaffected either way.
	SuppressStaggerInCombat = true,
	SendHitReaction = true,
	-- Turn off to compare against vanilla collision handling without
	-- uninstalling the mod. The knockdown tiers are unaffected.
	WalkStagger = true,
	LogTelemetry = true
}

--- Engine enum, transcribed from `Libs/AI/TypeDefinitions.xml`.
--
-- The values are deliberately non-sequential; they mirror a C++ enum. The
-- full set is kept rather than just the value used, so the contract stays
-- verifiable against the engine.
--
-- @table HitReactionType
HorseCollisionMod.HitReactionType = {
	Melee = 1,
	Collision = 2,
	Fall = 7,
	Bullet = 10,
	MeleeStealth = 16
}

--- Engine enum, transcribed from `Libs/AI/TypeDefinitions.xml`.
--
-- Ascending severity. `Tickle` and `Unpleasant` cost the victim no health.
--
-- @table HitReactionStrength
HorseCollisionMod.HitReactionStrength = {
	Zero = 0,
	Healing = 1,
	Tickle = 2,
	Unpleasant = 3,
	Exhausting = 4,
	MinorInjury = 5,
	MajorInjury = 6,
	Fatal = 7
}

--- Time of the last reaction per victim, keyed by entity id.
-- @table RecentHits
HorseCollisionMod.RecentHits = {}

--- Current time in milliseconds.
-- @treturn number milliseconds since the game session started
local function GetTimeMs()
	return System.GetCurrTime() * 1000
end

--- Magnitude of a CryEngine vector.
-- @tparam ?table v vector with x, y and z components, or nil
-- @treturn number length, or 0 when v is nil
local function GetVectorLength(v)
	if not v then
		return 0
	end

	return math.sqrt((v.x * v.x) + (v.y * v.y) + (v.z * v.z))
end

--- Writes a prefixed line to kcd.log when telemetry is enabled.
-- @tparam string message text to log
function HorseCollisionMod:Log(message)
	if not self.Config.LogTelemetry then
		return
	end

	System.LogAlways("[HorseCollisionMod] " .. tostring(message))
end

--- Resolves a speed to its gait name.
-- @tparam number speed horse speed in meters per second
-- @treturn string one of "Gallop", "Trot", "Walk" or "Idle"
function HorseCollisionMod:GetSpeedTier(speed)
	local cfg = self.Config

	if speed >= cfg.SpeedGallop then
		return "Gallop"
	end

	if speed >= cfg.SpeedTrot then
		return "Trot"
	end

	if speed >= cfg.SpeedWalk then
		return "Walk"
	end

	return "Idle"
end

--- Posts the native `hitReaction` message to the victim's brain.
--
-- This is what makes the vanilla collision bark, perception and crime
-- handling fire, so the reaction still feels like part of the game rather
-- than something bolted on. It does **not** drive animation.
--
-- Delivery is best effort. The receiving handler is declared `Atomic="true"`
-- and drops messages when busy, so nothing here may depend on a given
-- message arriving.
--
-- @tparam table npc victim entity
-- @tparam userdata horseWuid WUID of the horse, sent as the attacker
-- @tparam number strength a `HitReactionStrength` value
function HorseCollisionMod:SendHitReaction(npc, horseWuid, strength)
	if not self.Config.SendHitReaction then
		return
	end

	pcall(function()
		-- Brain messages carry their arguments as a "key(value), key(value)"
		-- string rather than a table.
		local values = "hitStrength(" .. tostring(strength)
				.. "), hitType(" .. tostring(self.HitReactionType.Collision) .. ")"

		-- The horse is named as the attacker, not Henry. That matches what
		-- the engine does for a trample, and the victim's brain resolves the
		-- rider from the horse itself when assigning blame.
		if horseWuid and Framework and Framework.WUIDToMsg then
			values = "attacker(" .. Framework.WUIDToMsg(horseWuid) .. "), " .. values
		end

		XGenAIModule.SendMessageToEntity(npc.id, "hitReaction", values)
	end)
end

--- Tests whether a victim is actually under the horse.
--
-- The sphere search is a broad-phase cull and nothing more. A horse is about
-- two meters long and under a meter wide, so a sphere around its origin also
-- catches people walking alongside or trailing behind it, which is what makes
-- collisions feel like they reach too far.
--
-- This narrows the sphere to an oriented box: the victim must be within the
-- horse's width laterally, between its rear and front reach along its facing,
-- and at a comparable height. The front reach is extended by the distance the
-- horse travels in one tick so that fast victims are not missed between
-- frames.
--
-- @tparam table npc victim entity
-- @tparam table horsePos world position of the horse
-- @tparam table horseForward horse facing, unit vector
-- @tparam number speed horse speed in meters per second
-- @treturn boolean true when the victim is inside the footprint
function HorseCollisionMod:IsInHorseFootprint(npc, horsePos, horseForward, speed)
	local cfg = self.Config
	local npcPos = nil

	pcall(function()
		npcPos = npc:GetPos()
	end)

	if not npcPos or not horsePos or not horseForward then
		return false
	end

	local dx = npcPos.x - horsePos.x
	local dy = npcPos.y - horsePos.y
	local dz = npcPos.z - horsePos.z

	-- Rejects anyone on a bridge overhead or in a cellar below, who would
	-- otherwise pass the flat two-dimensional test.
	if math.abs(dz) > cfg.HorseMaxVerticalDiff then
		return false
	end

	-- Distance along the horse's facing, and perpendicular to it. The
	-- perpendicular is taken directly from the forward vector rather than
	-- asking the engine for a second axis, so the two cannot disagree.
	local forwardDistance = (horseForward.x * dx) + (horseForward.y * dy)
	local lateralDistance = math.abs((horseForward.y * dx) - (horseForward.x * dy))

	local sweepExtra = speed * cfg.TickSeconds * cfg.SweepMultiplier

	if sweepExtra > cfg.MaxSweepExtra then
		sweepExtra = cfg.MaxSweepExtra
	end

	local inside = forwardDistance >= -cfg.HorseRearReach
			and forwardDistance <= (cfg.HorseFrontReach + sweepExtra)
			and lateralDistance <= cfg.HorseHalfWidth

	if inside then
		self:Log("Footprint fwd=" .. string.format("%.2f", forwardDistance)
				.. " lat=" .. string.format("%.2f", lateralDistance)
				.. " dz=" .. string.format("%.2f", dz)
				.. " sweep=" .. string.format("%.2f", sweepExtra))
	end

	return inside
end

--- Works out which side of the victim the impact lands on.
--
-- The stagger clips are authored relative to the NPC's facing, so the impact
-- has to be expressed in the victim's own frame. Using the horse's frame
-- instead makes NPCs stagger into the horse rather than away from it.
--
-- The impact is derived from the horse's **direction of travel**, not its
-- position. Position is ambiguous at the moment of contact, when the horse
-- is effectively on top of the victim and a centimeter either way flips the
-- answer. Travel direction is stable, and it is what actually decides which
-- side of the body is struck: a horse moving north hits the south face of
-- whoever is in front of it.
--
-- @tparam table npc victim entity
-- @tparam table velocity horse velocity vector
-- @tparam number speed horse speed in meters per second
-- @treturn string one of "so_forward", "so_back", "so_left", "so_right"
function HorseCollisionMod:GetImpactDir(npc, velocity, speed)
	local forward = nil

	pcall(function()
		if npc.GetDirectionVector then
			forward = npc:GetDirectionVector(1)
		end
	end)

	if not forward or not velocity or speed <= 0 then
		return "so_forward"
	end

	-- The blow arrives from the direction the horse came from, which is the
	-- opposite of its travel. Flattened to the ground plane, since a rider
	-- is always above a pedestrian and the height would bias every result.
	local fromX = -velocity.x / speed
	local fromY = -velocity.y / speed

	-- Projected onto the victim's axes: dot is how much the blow comes from
	-- ahead of them (negative means from behind), cross is how much it comes
	-- from their left (negative means their right).
	local dot = (forward.x * fromX) + (forward.y * fromY)
	local cross = (forward.x * fromY) - (forward.y * fromX)

	-- The larger magnitude wins, which snaps the blow to the nearest of the
	-- four authored clips. Comparing magnitudes rather than testing a fixed
	-- angle means a glancing hit still resolves sensibly.
	if math.abs(dot) >= math.abs(cross) then
		if dot >= 0 then
			return "so_forward"
		end

		return "so_back"
	end

	if cross >= 0 then
		return "so_left"
	end

	return "so_right"
end

--- Plays the walk-speed stagger on a victim.
--
-- Calls `actor:StartInteractiveActionByName` with one of the `hcm_stagger_*`
-- names this mod adds to the animation database. See the module header for
-- why this is the only call that works.
--
-- The return value reports whether the call was accepted, which is **not**
-- the same as the animation playing: an unrecognized name is accepted and
-- then aborts within a frame. Only in-game observation confirms playback.
--
-- @tparam table npc victim entity
-- @tparam table velocity horse velocity vector
-- @tparam number speed horse speed in meters per second
-- @treturn boolean true when the call was accepted without error
function HorseCollisionMod:PlayStagger(npc, velocity, speed)
	if not npc.actor or type(npc.actor.StartInteractiveActionByName) ~= "function" then
		return false
	end

	-- GetImpactDir speaks the engine's "so_" vocabulary; the database entries
	-- this mod adds are named without that prefix, so strip it.
	local dir = self:GetImpactDir(npc, velocity, speed)
	local action = "hcm_stagger_" .. string.gsub(dir, "so_", "")

	-- Gender is logged because the female animation set has no
	-- AnimationControlled fragment, so female victims accept the call and
	-- play nothing. Without this the misses look random.
	local gender = "?"

	pcall(function()
		if npc.soul and npc.soul.GetGender then
			gender = tostring(npc.soul:GetGender())
		end
	end)

	local ok, err = pcall(function()
		-- The second argument is the object being interacted with. There is
		-- no object in a collision, so the victim is passed as its own
		-- target; the animation needs no alignment to anything external.
		npc.actor:StartInteractiveActionByName(action, npc.id, true, 1)
	end)

	self:Log("Stagger action=" .. action
			.. " gender=" .. gender
			.. " ok=" .. tostring(ok)
			.. " err=" .. tostring(err))

	return ok
end

--- Knocks a victim down with a physics ragdoll.
--
-- Used at trot and gallop. `actor:Fall` switches the victim to a ragdoll,
-- after which an impulse can be applied. Impulses are ignored on an upright,
-- animation-driven actor, which is why the order matters and why the impulse
-- is deferred by a tick.
--
-- @tparam table npc victim entity
-- @tparam table velocity horse velocity vector
-- @tparam number speed horse speed in meters per second
-- @tparam number impulseScale multiplier on the configured impulse, 0 to 1
function HorseCollisionMod:Ragdoll(npc, velocity, speed, impulseScale)
	pcall(function()
		if npc.actor then
			npc.actor:Fall({x=0, y=0, z=0}, true)
		end
	end)

	local k_back = self.Config.Knockback * impulseScale
	local k_up = self.Config.Uplift * impulseScale

	if k_back <= 0 and k_up <= 0 then
		return
	end

	pcall(function()
		local hitPos = {x=0, y=0, z=0}
		local dir = {x=1, y=0, z=0}

		if npc.GetPos then
			hitPos = npc:GetPos()
		end

		-- Lift the application point to roughly chest height so the victim
		-- rotates over the impact instead of having their feet swept.
		hitPos.z = hitPos.z + 1.0

		if speed > 0 and velocity then
			dir.x = velocity.x / speed
			dir.y = velocity.y / speed
			dir.z = 0
		end

		-- Forward push and upward lift are combined into one vector, then
		-- split back into a unit direction and a magnitude, because
		-- AddImpulse wants those as separate arguments.
		local combined = { x = dir.x * k_back, y = dir.y * k_back, z = k_up }
		local impulseMag = math.sqrt((combined.x * combined.x)
				+ (combined.y * combined.y)
				+ (combined.z * combined.z))

		if npc.AddImpulse and impulseMag > 0 then
			local normDir = {
				x = combined.x / impulseMag,
				y = combined.y / impulseMag,
				z = combined.z / impulseMag
			}

			-- The ragdoll needs a tick to physicalize before it accepts an
			-- impulse.
			Script.SetTimer(50, function()
				pcall(function()
					npc:AddImpulse(-1, hitPos, normDir, impulseMag, 1)
				end)
			end)
		end
	end)
end

--- Whether this collision should count as a combat one.
--
-- Two independent signals, because neither alone is reliable:
--
-- * `player.soul:IsInCombatDanger()` is what vanilla scripts use, but it
--   reflects immediate danger rather than "a fight is happening", and it was
--   observed reading false through a whole session the player described as
--   being in combat with guards. Mounted and moving, the player may simply
--   not be in danger at the instant of each impact.
-- * The victim having a weapon drawn. Townsfolk do not walk around armed, so
--   this catches the case the first signal misses: charging someone who is
--   actively fighting.
--
-- Both raw values are logged so a disagreement between them is visible
-- rather than being hidden behind a single boolean.
--
-- @tparam table npc victim entity
-- @treturn boolean true when combat rules should apply
-- @treturn string diagnostic describing both signals
function HorseCollisionMod:IsCombatCollision(npc)
	local danger = false
	local dangerOk = false
	local armed = false
	local armedOk = false

	dangerOk = pcall(function()
		if player.soul and player.soul.IsInCombatDanger then
			danger = player.soul:IsInCombatDanger()
		end
	end)

	armedOk = pcall(function()
		if npc.human and npc.human.IsWeaponDrawn then
			armed = npc.human:IsWeaponDrawn()
		end
	end)

	local detail = "danger=" .. tostring(danger) .. "/" .. tostring(dangerOk)
			.. " armed=" .. tostring(armed) .. "/" .. tostring(armedOk)

	return (danger == true or armed == true), detail
end

--- Throws the rider from the horse.
--
-- Prefers the horse's own `RearAndThrowDown`, which plays the animation of
-- the animal rearing and unseating its rider. Falls back to ragdolling the
-- player, which is what earlier builds did and which reads as the player
-- simply collapsing rather than being thrown.
--
-- `RearAndThrowDown` is undocumented. It sits on the horse entity's `horse`
-- extension, alongside `HasRider` and `IsMountable`.
--
-- @tparam table horseEnt the player's horse entity
-- @tparam table playerEnt the player entity
function HorseCollisionMod:ThrowRider(horseEnt, playerEnt)
	local thrown = false

	-- The method lives on the horse's own `horse` extension, found by
	-- enumerating what the entity actually carries. The other entries are
	-- kept as fallbacks in case a different mount type differs.
	local candidates = {
		{ name = "horse.horse", holder = horseEnt.horse },
		{ name = "horse", holder = horseEnt },
		{ name = "horse.actor", holder = horseEnt.actor }
	}

	for _, candidate in pairs(candidates) do
		if not thrown and candidate.holder
				and type(candidate.holder.RearAndThrowDown) == "function" then
			local ok = pcall(function()
				candidate.holder:RearAndThrowDown()
			end)

			self:Log("ThrowRider via " .. candidate.name .. " ok=" .. tostring(ok))

			if ok then
				thrown = true
			end
		end
	end

	if not thrown then
		self:Log("ThrowRider falling back to player ragdoll")

		pcall(function()
			playerEnt.actor:Fall({x=0, y=0, z=0}, true)
		end)
	end
end

--- Charges the horse for an impact and dismounts Henry when it is spent.
--
-- Stamina is written with `soul:SetState`, never `soul:DealDamage`. That
-- call takes `(stamina, health, attacker, ...)`  -  stamina first  -  even though
-- vanilla's own debug helper names the parameters health-first, so using it
-- here silently injures the horse instead.
--
-- @tparam table horseEnt the player's horse entity
-- @tparam table playerEnt the player entity
-- @tparam number staminaDrain points of stamina to remove
function HorseCollisionMod:DrainHorseStamina(horseEnt, playerEnt, staminaDrain)
	if not staminaDrain or staminaDrain <= 0 or not horseEnt or not playerEnt then
		return
	end

	pcall(function()
		if not horseEnt.soul then
			return
		end

		local before = horseEnt.soul:GetState("stamina")

		if not before then
			return
		end

		-- Clamped at zero rather than allowed to go negative, so that a
		-- single heavy impact cannot bank a deficit the horse then has to
		-- recover from before it can move again.
		local target = before - staminaDrain

		if target < 0 then
			target = 0
		end

		horseEnt.soul:SetState("stamina", target)

		self:Log("Horse stamina " .. string.format("%.1f", before)
				.. " -> " .. string.format("%.1f", target))

		if not self.Config.ThrowRiderOnStaminaEmpty then
			return
		end

		if target <= 0 and playerEnt.actor then
			self:Log("Horse spent - throwing rider.")
			self:ThrowRider(horseEnt, playerEnt)
		end
	end)
end

--- Applies the appropriate reaction for one collision.
--
-- Enforces the per-victim cooldown, then dispatches on gait.
--
-- @tparam table npc victim entity
-- @tparam table velocity horse velocity vector
-- @tparam number speed horse speed in meters per second
-- @tparam table horseEnt the player's horse entity
-- @tparam table playerEnt the player entity
-- @tparam userdata horseWuid WUID of the horse
function HorseCollisionMod:TriggerCollision(npc, velocity, speed, horseEnt, playerEnt,
		horseWuid)
	local npcId = tostring(npc.id)
	local now = GetTimeMs()

	-- The detection sphere is tested ten times a second, so without a
	-- per-victim cooldown a single pass through a crowd would restart the
	-- same NPC's reaction every tick and they would never finish staggering.
	local lastHit = self.RecentHits[npcId]

	if lastHit and (now - lastHit) < self.Config.HitCooldownMs then
		return
	end

	self.RecentHits[npcId] = now

	local tierName = self:GetSpeedTier(speed)
	local strength = self.HitReactionStrength
	local cfg = self.Config
	local combatScale = 1.0
	local isCombat, combatDetail = self:IsCombatCollision(npc)

	if isCombat then
		combatScale = cfg.CombatStaminaMultiplier
	end

	self:Log("Impact tier=" .. tierName
			.. " speed=" .. string.format("%.2f", speed)
			.. " combatScale=" .. string.format("%.1f", combatScale)
			.. " " .. combatDetail)

	if tierName == "Walk" then
		local suppressed = cfg.SuppressStaggerInCombat and combatScale > 1.0

		if cfg.WalkStagger and not suppressed then
			self:PlayStagger(npc, velocity, speed)
		end

		self:SendHitReaction(npc, horseWuid, strength.Tickle)
		self:DrainHorseStamina(horseEnt, playerEnt, cfg.StaminaDrainWalk * combatScale)
		return
	end

	if tierName == "Trot" then
		self:Ragdoll(npc, velocity, speed, 0.6)
		self:SendHitReaction(npc, horseWuid, strength.MinorInjury)
		self:DrainHorseStamina(horseEnt, playerEnt, cfg.StaminaDrainTrot * combatScale)
		return
	end

	if tierName == "Gallop" then
		self:Ragdoll(npc, velocity, speed, 1.0)
		self:SendHitReaction(npc, horseWuid, strength.MajorInjury)
		self:DrainHorseStamina(horseEnt, playerEnt, cfg.StaminaDrainGallop * combatScale)
		return
	end
end

--- One tick of collision detection.
--
-- Bails out early unless the player is mounted and moving at least at
-- walking pace, then tests every entity within `HitRadius` of the horse.
--
-- Every engine call is wrapped in `pcall`, because entities can be unstreamed
-- or partially initialized at any moment and an uncaught error would kill the
-- timer loop for the rest of the session.
function HorseCollisionMod:SafeUpdate()
	if type(player) == "nil"
			or (not player)
			or type(player.human) == "nil"
			or type(player.player) == "nil" then
		return
	end

	local isMounted = false

	pcall(function()
		isMounted = player.human:IsMounted()
	end)

	if not isMounted then
		return
	end

	local horseWuid = nil

	pcall(function()
		horseWuid = player.player:GetPlayerHorse()
	end)

	if not horseWuid then
		return
	end

	local horseEnt = nil

	pcall(function()
		horseEnt = XGenAIModule.GetEntityByWUID(horseWuid)
	end)

	if not horseEnt then
		return
	end

	local velocity = nil

	pcall(function()
		if horseEnt.GetVelocity then
			velocity = horseEnt:GetVelocity()
		end

		if not velocity and player.GetVelocity then
			velocity = player:GetVelocity()
		end
	end)

	local speed = GetVectorLength(velocity)

	if speed < self.Config.SpeedWalk then
		return
	end

	local horsePos = nil
	local horseForward = nil

	pcall(function()
		horsePos = horseEnt:GetPos()
	end)

	pcall(function()
		if horseEnt.GetDirectionVector then
			horseForward = horseEnt:GetDirectionVector(1)
		end
	end)

	if not horsePos or not horseForward then
		return
	end

	local hitEnts = nil

	pcall(function()
		hitEnts = System.GetEntitiesInSphere(horsePos, self.Config.HitRadius)
	end)

	if type(hitEnts) ~= "table" then
		return
	end

	for _, ent in pairs(hitEnts) do
		local isCandidate = (ent
				and type(ent) == "table"
				and ent.id
				and ent.id ~= player.id
				and ent.id ~= horseEnt.id)

		if isCandidate then
			local isMutt = false

			-- Henry's dog follows close enough to be caught constantly, and
			-- trampling him on every ride is nobody's idea of immersion. He
			-- is identified by entity name because dogs share the generic
			-- NPC class.
			pcall(function()
				local entName = ent:GetName()

				if entName and string.find(entName, "dogCompanion") then
					isMutt = true
				end
			end)

			local isProtected = (self.Config.ProtectMutt and isMutt)

			if not isProtected then
				local isHuman = false

				-- The sphere returns everything nearby: crates, doors, loose
				-- items. The faction check catches NPCs whose class is set
				-- to something unexpected, which quest characters often are.
				pcall(function()
					isHuman = (ent.class == 'NPC'
							or ent.class == 'Player'
							or (ent.Properties and ent.Properties.esFaction))
				end)

				if isHuman and ent.actor then
					local isDead = false

					-- Corpses are already ragdolls. Reacting to them would
					-- twitch bodies around and re-trigger every tick.
					if ent.IsDead then
						pcall(function()
							isDead = ent:IsDead()
						end)
					end

					local inFootprint = self:IsInHorseFootprint(ent, horsePos,
							horseForward, speed)

					if not isDead and inFootprint then
						self:TriggerCollision(ent, velocity, speed, horseEnt, player, horseWuid)
					end
				end
			end
		end
	end
end

--- Reschedules itself every 100 ms and runs one detection tick.
--
-- The tick number guards against duplicate loops. Each load screen starts a
-- new loop, and any loop whose number no longer matches the current one stops
-- on its next iteration, so reloading a save leaves no stale timers running.
--
-- @tparam number assignedTick the loop generation this timer belongs to
function HorseCollisionMod:UpdateTimer(assignedTick)
	if self.TimerTick ~= assignedTick then
		return
	end

	-- The next tick is booked before any work is done. If detection ever
	-- throws in a way pcall cannot contain, the loop still survives; booking
	-- afterwards would end the mod for the rest of the session.
	Script.SetTimer(100, function()
		HorseCollisionMod:UpdateTimer(assignedTick)
	end)

	local success, err = pcall(function()
		self:SafeUpdate()
	end)

	if not success then
		self:Log("CRITICAL ERROR IN UPDATE TIMER: " .. tostring(err))
	end
end

--- UI event handler that serves as the mod's entry point.
--
-- A Startup script has no general "game loaded" hook available to it, so the
-- end of the loading screen stands in for one.
--
-- @tparam string actionName UI action that fired
-- @tparam string eventName phase of that action
-- @tparam table argTable event arguments, unused
function HorseCollisionMod:uiActionListener(actionName, eventName, argTable)
	if actionName == "sys_loadingimagescreen" and eventName == "OnEnd" then
		local currentTick = (self.TimerTick or 0) + 1

		self.TimerTick = currentTick

		self:Log("Load screen ended. v" .. self.Version
				.. " initializing physics timer loop "
				.. tostring(currentTick))

		Script.SetTimer(100, function()
			HorseCollisionMod:UpdateTimer(currentTick)
		end)
	end
end

if type(UIAction) == "table" and type(UIAction.RegisterActionListener) == "function" then
	UIAction.RegisterActionListener(HorseCollisionMod, "", "", "uiActionListener")
end
