"""Generates the mod's armor table from the game's own item tables.

What a target is wearing decides how far it is thrown and what it costs the
horse, and neither figure is available at runtime. `inventory:GetInventoryTable`
gives the item WUIDs an entity carries and `ItemManager.GetItem` resolves each
to an item class, but nothing in the ScriptBind surface reports an item's
weight. The weight lives in `Libs/Tables/item/pickable_item.xml`, joined to
`armor.xml` by `item_id`, and Lua cannot read files, so the join is done here
and shipped as a table.

Only armor is emitted. Food, keys and coin are in the same inventory and carry
weights of their own, and including them would make a villager carrying bread
read as better protected than one who is not.

Three columns come out of it:

    weight      from pickable_item.xml, what the piece adds to the target
    smash_def   from armor.xml, the game's own blunt defense for the piece
    type        from armor.xml, which separates horse tack from what a
                person wears

The type matters because saddles, bridles, horseshoes and spurs are filed as
armor. Summing them into a person's total counts gear that is not on them, and
the same table serves the horse by keeping only those rows.

Run from the repository root, or through build.ps1, which runs it before
packing:

    python tools/build_item_weights.py
"""

import io
import os
import re
import sys

from build_adb import find_game_root, read_pak_entry

ARMOR_TABLE = "Libs/Tables/item/armor.xml"
PICKABLE_TABLE = "Libs/Tables/item/pickable_item.xml"
TYPE_TABLE = "Libs/Tables/item/armor_type.xml"

OUTPUT = os.path.join("mod_assets", "Scripts", "Startup",
                      "HorseCollisionMod_ItemData.lua")

# Worn by a horse, or by a rider but never protective. Kept in the table with
# their type so the horse side of Phase 3 can select exactly these, and so a
# person's total can exclude them.
TACK_TYPES = ("8", "10", "11", "12")

HEADER = """-- Generated by tools/build_item_weights.py from the game's own tables.
-- Do not edit. Regenerate instead.
--
-- Armor.<item class> = { weight, smash_def, armor_type_id }
--
-- weight and smash_def come from pickable_item.xml and armor.xml, joined by
-- item_id. The item class is what ItemManager.GetItem reports for an item in
-- an entity's inventory, so a lookup needs no conversion.
--
-- TackTypes are the armor types worn by a horse, or by a rider without
-- protecting anything. A sum over a person excludes them; the horse's own
-- total is made of them.

HorseCollisionModItemData = {
"""


def rows(pak, entry):
    """Every <row> in a game table, as dictionaries of its attributes."""
    blob = read_pak_entry(pak, entry).decode("utf-8", "replace")

    return [dict(re.findall(r'(\w+)="([^"]*)"', row))
            for row in re.findall(r"<row\b([^>]*?)/>", blob)]


def number(text, default="0"):
    """A table value as Lua source, trimmed of trailing zeros."""
    try:
        value = float(text)
    except (TypeError, ValueError):
        value = float(default)

    if value == int(value):
        return str(int(value))

    return repr(round(value, 4))


def main():
    root = find_game_root()
    pak = os.path.join(root, "Data", "Tables.pak")

    if not os.path.exists(pak):
        raise SystemExit("no Tables.pak under %s" % root)

    weights = {r["item_id"]: r.get("weight", "0")
               for r in rows(pak, PICKABLE_TABLE) if "item_id" in r}
    types = {r["armor_type_id"]: r.get("armor_type_name", "")
             for r in rows(pak, TYPE_TABLE) if "armor_type_id" in r}

    armor = []
    missing = 0

    for row in rows(pak, ARMOR_TABLE):
        item = row.get("item_id")

        if not item:
            continue

        if item not in weights:
            # A piece with no weight would sum as nothing and read as
            # unarmored, which is worse than knowing the table is incomplete.
            missing += 1
            continue

        armor.append((item, weights[item], row.get("smash_def", "0"),
                      row.get("armor_type_id", "0")))

    armor.sort()

    lines = [HEADER, "\tArmor = {\n"]

    for item, weight, smash, kind in armor:
        lines.append('\t\t["%s"] = { %s, %s, %s },\n'
                     % (item, number(weight), number(smash), number(kind)))

    lines.append("\t},\n\n\tTackTypes = {\n")

    for kind in TACK_TYPES:
        lines.append("\t\t[%s] = true,   -- %s\n" % (kind, types.get(kind, "?")))

    lines.append("\t},\n\n\tTypeNames = {\n")

    for kind in sorted(types, key=int):
        lines.append('\t\t[%s] = "%s",\n' % (kind, types[kind]))

    lines.append("\t},\n}\n")

    out = os.path.abspath(OUTPUT)
    folder = os.path.dirname(out)

    if not os.path.isdir(folder):
        os.makedirs(folder)

    with io.open(out, "w", encoding="ascii", newline="\r\n") as handle:
        handle.write("".join(lines))

    print("Wrote %s" % OUTPUT)
    print("  %d armor pieces, %d armor types" % (len(armor), len(types)))

    if missing:
        print("  %d armor rows had no weight and were skipped" % missing)

    return 0


if __name__ == "__main__":
    sys.exit(main())
