"""Builds the settings documentation out of the settings file itself.

Two outputs share one source: the `[code]` block on the Nexus page, which
`pre_release_check.py` compares against the keys that ship, and the settings
table in README.md, which the build compares against this output. The settings
file is the single source, and its own inline comments become the
descriptions, so neither falls behind when a setting is added.

Only the player-facing half is emitted. Everything after the banner in the
settings file is exposed for completeness (internals, timings measured against
an animation, switches with one sensible value) and is documented in place.
That is the same boundary `check_nexus_page` applies.

Section headings come from the settings file's own comment blocks, so both
outputs are ordered the way the file a player edits is ordered.

    python tools/nexus_settings_block.py                # print the page block
    python tools/nexus_settings_block.py --check        # compare with the page
    python tools/nexus_settings_block.py --readme       # rewrite README's table
    python tools/nexus_settings_block.py --check-readme # exit 1 if it is stale
"""

import argparse
import io
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SETTINGS = os.path.join(REPO_ROOT, "src", "HorseCollisionMod_Settings.lua")
PAGE = os.path.join(REPO_ROOT, "nexus_description.txt")
README = os.path.join(REPO_ROOT, "README.md")
BANNER = "\t-- ====="

# The README's generated table sits between these two lines.
README_BEGIN = ("<!-- settings table: generated by "
                "tools/nexus_settings_block.py --readme -->")
README_END = "<!-- end of settings table -->"


def read(path):
    return io.open(path, encoding="utf-8", errors="replace").read()


def player_facing():
    """The settings a player is meant to touch, in file order, with comments.

    Yields ("section", text) and ("setting", name, value, description). A
    section is a comment block sitting on its own above a run of settings; a
    description is the trailing comment on the setting's own line, plus any
    continuation lines under it.
    """
    text = read(SETTINGS)

    # Start at the table itself. The file opens with a comment block explaining
    # how to edit it, which is prose about the file rather than a group of
    # settings inside it, and reading from the top turns it into a heading.
    opening = text.find("HorseCollisionModSettings = {")

    if opening != -1:
        text = text[opening:]

    banner = text.find(BANNER)

    if banner != -1:
        text = text[:banner]

    lines = text.split("\n")
    out = []
    pending = []
    # Lines already folded into a setting's trailing comment. Without this the
    # loop visits them again and emits each one a second time as a heading.
    eaten = set()

    for i, line in enumerate(lines):
        if i in eaten:
            continue

        bare = line.strip()

        # A comment line on its own: either a section heading or prose about the
        # setting underneath. Held until the next setting decides which.
        if bare.startswith("--") and "=" not in line.split("--")[0]:
            pending.append(bare.lstrip("- ").strip())
            continue

        m = re.match(r"^\t([A-Za-z_]\w*)\s*=\s*(.+?)\s*(?:--\s*(.*))?$", line)

        if not m:
            # A blank line ends a comment block, which makes it a section.
            if not bare and pending:
                out.append(("section", " ".join(pending)))
                pending = []

            continue

        name, value, own = m.group(1), m.group(2).rstrip(","), m.group(3) or ""

        # A setting whose value is a table is listed as its members rather
        # than as a bare "{", which tells a player nothing. Rendered inline so
        # the row stays one row: the page is checked by setting name, and a
        # member per row would need a name with a dot in it that
        # check_nexus_page cannot match.
        if value == "{":
            members = []
            depth = 1
            j = i + 1

            while j < len(lines) and depth > 0:
                body = lines[j].split("--")[0]

                # Only the table's own members count. A member whose value is
                # itself a list, such as a tier's sound layers, is named
                # without its contents: printing them turns one row into an
                # unreadable line of braces and tells a player less than the
                # tier name does.
                if depth == 1:
                    for key, val in re.findall(r"(\w+)\s*=\s*([^,{]*\{?)", body):
                        val = val.strip()
                        members.append(key if val.endswith("{")
                                else "%s %s" % (key, val))

                depth += body.count("{") - body.count("}")
                eaten.add(j)
                j += 1

            value = ", ".join(members)

        # Continuation of the trailing comment: a following line whose only
        # content is a comment aligned past the value column.
        j = i + 1

        while j < len(lines):
            cont = re.match(r"^\s{20,}--\s*(.*)$", lines[j])

            if not cont:
                break

            own += " " + cont.group(1).strip()
            eaten.add(j)
            j += 1

        if pending:
            out.append(("section", " ".join(pending)))
            pending = []

        out.append(("setting", name, value, own.strip()))

    return out


def block():
    rows = player_facing()
    width = max(len(r[1]) for r in rows if r[0] == "setting") + 2
    vwidth = min(24, max(len(r[2]) for r in rows if r[0] == "setting") + 2)
    lines = []

    for row in rows:
        if row[0] == "section":
            # A heading sits at the left margin; check_nexus_page reads an
            # unindented word as a heading rather than as a setting.
            text = row[1]

            if len(text) > 78:
                text = text[:75].rstrip() + "..."

            lines.append("")
            lines.append(text)
            continue

        _kind, name, value, desc = row
        desc = desc[:1].upper() + desc[1:] if desc else ""
        lines.append("  %-*s%-*s%s" % (width, name, vwidth, value, desc))

    return "\n".join(lines).strip("\n")


def markdown():
    """The README's settings table: one table per section of the file."""
    lines = []
    open_table = False

    def cell(text):
        return text.replace("|", "\\|")

    for row in player_facing():
        if row[0] == "section":
            lines += ["", cell(" ".join(row[1].split())), ""]
            open_table = False
            continue

        if not open_table:
            lines += ["| Setting | Default | Effect |", "| --- | --- | --- |"]
            open_table = True

        _kind, name, value, desc = row
        desc = desc[:1].upper() + desc[1:] if desc else ""
        lines.append("| `%s` | %s | %s |" % (name, cell(value), cell(desc)))

    return "\n".join(lines).strip("\n")


def readme_with_table():
    """README.md with its generated table replaced by the current one."""
    text = read(README)
    start = text.find(README_BEGIN)
    end = text.find(README_END)

    if start == -1 or end < start:
        sys.exit("README.md has no settings table markers:\n  %s\n  %s"
                 % (README_BEGIN, README_END))

    head = text[:start + len(README_BEGIN)]

    return text, head + "\n\n" + markdown() + "\n\n" + text[end:]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
            help="report which player-facing settings the page is missing")
    ap.add_argument("--readme", action="store_true",
            help="rewrite the settings table in README.md")
    ap.add_argument("--check-readme", action="store_true",
            help="exit 1 if README.md's settings table is not current")
    args = ap.parse_args()

    if args.readme or args.check_readme:
        current, wanted = readme_with_table()

        if args.check_readme:
            if current != wanted:
                sys.stdout.write("README.md's settings table differs from "
                                 "the settings file. Regenerate it:\n"
                                 "  python tools/nexus_settings_block.py "
                                 "--readme\n")
                sys.exit(1)

            return

        io.open(README, "w", encoding="utf-8").write(wanted)
        return

    if not args.check:
        sys.stdout.write(block() + "\n")
        return

    page = read(PAGE) if os.path.exists(PAGE) else ""
    found = re.search(r"\[code\](.*?)\[/code\]", page, re.S)
    listed = set(re.findall(r"^[ \t]{2,}(\w+)\s{2,}", found.group(1), re.M)) \
            if found else set()
    shipped = set(r[1] for r in player_facing() if r[0] == "setting")

    sys.stdout.write("player-facing settings: %d   on the page: %d\n"
            % (len(shipped), len(shipped & listed)))

    for key in sorted(shipped - listed):
        sys.stdout.write("   missing from the page: %s\n" % key)

    for key in sorted(listed - shipped):
        sys.stdout.write("   on the page but not player-facing: %s\n" % key)


if __name__ == "__main__":
    main()
