--- Horse Collision Overhaul for Kingdom Come: Deliverance.
--
-- Gives mounted collisions a reaction proportional to the horse's gait. In
-- vanilla, riding into an NPC produces only an audio bark and no animation at
-- any speed. This module adds three tiers:
--
-- * **Walk** - the NPC plays a full standing stagger animation and is not
--   knocked down. No health damage, and the vanilla bark still fires.
-- * **Trot** - a physics ragdoll at reduced impulse.
-- * **Gallop** - a physics ragdoll at full impulse.
--
-- At trot and gallop the horse also loses stamina, and dismounts Henry when
-- spent. That is the anti-bulldozing budget: riding through a crowd has to
-- end with Henry on the ground rather than being a free way to scatter a
-- dozen people.
--
-- ## How the walk stagger works
--
-- Lua cannot drive an NPC's animation directly, and every obvious approach
-- fails silently: `human:PlayAnim` is accepted but never
-- renders, physics impulses are ignored because actors are animation-driven,
-- `soul:DealDamage` only moves stat numbers, and the `hitReaction` and
-- `combat:hit` brain messages reach a behavior tree that cannot drive the
-- body.
--
-- What does play a clip is `actor:StartInteractiveActionByName`, the call
-- vanilla uses to make an actor mime opening a door. It takes over the body,
-- plays a whole animation, and hands control back. Its name argument resolves
-- against the FragTags of exactly one Mannequin fragment,
-- `AnimationControlled`, where vanilla ships only object interactions.
--
-- It is not the only actor call that matters. An interactive action is
-- root-motion driven, so the animation moves the body and nothing constrains
-- where it ends up, which is why a reaction played beside a building could
-- carry its victim into the wall. `actor:SetMovementControlledByAnimation`
-- turns that off per victim, and is called a tick after the action starts;
-- see `ReleaseVictimMovement` for why the order is not negotiable.
--
-- So the mod adds its own entries there, without replacing anything. Seven
-- data files ship alongside this script, all generated by `build_adb.py`,
-- and every one is named `hcm_*` so it cannot collide with another mod:
--
-- * `hcm_<set>_database.adb` - the parent, and the authoritative definition
--   of `AnimationControlled`. It carries vanilla's own 30 options plus this
--   mod's 4, and references the untouched vanilla database as a SubADB for
--   every other fragment. Carrying vanilla's options is not optional: a
--   sub-database does not merge into a fragment another one defines, so
--   without them a redirected NPC loses every door and cabinet interaction.
-- * `hcm_<set>_fragmentids.xml` - points `AnimationControlled` at the tag
--   file below. For women it also has to declare that fragment at all,
--   since they have the same clips but no such fragment in vanilla.
-- * `hcm_<set>_controllerdefs.xml` - points its `Fragments` element at the
--   file above. This is what an entity resolves names through at runtime,
--   and redirecting the database alone is not enough.
-- * `hcm_animationControlledTags.xml` - declares those FragTags. An option
--   whose tag is not declared aborts after one frame.
-- See `docs/HOW_IT_WORKS.md` for why this indirection is worth the trouble.
--
-- ## Limitations
--
-- * Dogs and other animals do not react. They use separate animation
--   databases which this mod does not touch.
-- * Two mods redirecting `AnimDatabase3P` on the same entity class conflict.
--   The contested value is a Lua string, so a cooperative mod can chain by
--   referencing whatever is already set.
--
-- @module HorseCollisionMod
-- @author jrandall54
-- @release 4.1.0-dev.2

HorseCollisionMod = {}

HorseCollisionMod.Version = "4.1.0-dev.2"

--- Loop generation counter, deliberately kept outside the table above.
--
-- `lua_reload_script` re-executes this file, and its first act is to rebuild
-- HorseCollisionMod from scratch, which takes TimerTick with it. A counter
-- stored on the table therefore restarts at 1 on every reload, while any loop
-- still running from before compares its own generation against that same 1,
-- matches, and carries on. Each reload would leave another loop sweeping for
-- collisions ten times a second, all of them writing to the same cooldown
-- table.
--
-- The `or 0` is what makes this survive a reload: the global is already set by
-- then, so the count continues instead of restarting, and every stale loop
-- sees a generation that no longer matches and stops on its next tick.
HorseCollisionModGeneration = HorseCollisionModGeneration or 0

--- Tuning values. Safe to edit in place; nothing here is derived at runtime.
--
-- Grouped by what they affect, and deliberately kept terse: this is the table
-- people open to change a setting, not to read. The reasoning behind the
-- defaults is in docs/TECHNICAL_DETAILS.md under "Reaction defaults".
--
-- @field SpeedWalk lower bound of the walk tier, in meters per second
-- @field SpeedTrot lower bound of the trot tier
-- @field SpeedGallop lower bound of the gallop tier
-- @field HitRadius radius of the broad-phase sphere around the horse
-- @field HorseFrontReach how far ahead of the horse origin counts as a hit
-- @field HorseRearReach how far behind the horse origin counts as a hit
-- @field HorseHalfWidth lateral half-width of the horse footprint
-- @field HorseMaxVerticalDiff height difference above which a hit is ignored
-- @field TickSeconds detection interval, used to sweep the footprint forward
-- @field SweepMultiplier how far ahead to sweep, per meter per second
-- @field MaxSweepExtra cap on the forward sweep, in meters
-- @field HitCooldownMs minimum gap between reactions on the same victim
-- @field KnockdownRecoveryMs how long a knocked-down victim is left alone,
--   which is longer than the walk cooldown because they are still on the ground
-- @field ImpactSpeedSamples ticks of speed history a collision is scored from
-- @field MaxImpactSpeed ceiling on the speed a collision is scored at
-- @field Knockback horizontal ragdoll impulse at full strength
-- @field Uplift vertical ragdoll impulse at full strength
-- @field ArmorReferenceWeight armor weight that scales a target by exactly one
-- @field ArmorImpulseExponent how sharply armor weight reduces the impulse
-- @field MinArmorImpulse floor on the armor impulse multiplier
-- @field MaxArmorImpulse ceiling on the armor impulse multiplier, reached by
--   an unarmored target
-- @field ArmorStaminaExponent how sharply armor weight raises the stamina cost
-- @field MinArmorStamina floor on the armor stamina multiplier
-- @field MaxArmorStamina ceiling on the armor stamina multiplier
-- @field ProtectMutt when true, Henry's dog is never a valid victim
-- @field StaminaDrainWalk horse stamina cost per victim at walk
-- @field StaminaDrainTrot horse stamina cost per victim at trot
-- @field StaminaDrainGallop horse stamina cost per victim at gallop
-- @field ThrowRiderOnStaminaEmpty dismount Henry when the horse is spent
-- @field CombatStaminaMultiplier stamina cost multiplier while in a fight
-- @field SuppressStaggerInCombat skip the stagger animation during a fight
-- @field SendHitReaction post the native brain message so barks still fire
-- @field WalkStagger whether the walk tier plays a stagger animation
-- @field SuppressAutoCureSec how often the auto-cure exemption is rechecked,
--   in seconds, or 0 to leave victims in the daycycle
-- @field TrotReaction what a trot impact does, "knockdown" for an animated
--   fall or "ragdoll" for the physics knockdown
-- @field AutoCureHealthLimit health at or above which the auto-cure exemption
--   is dropped, matching vanilla's own limit
-- @field ReleaseAnimationMovement take movement control off the animation once
--   a reaction has started, so victims are not carried into walls
-- @field ReplanAfterReaction ask a victim to re-plan their activity once the
--   reaction is over, so they approach and re-align to whatever they were using
-- @field LogTelemetry write diagnostics to kcd.log
-- @field DiagnoseMisses name the reason a nearby NPC produced no reaction
-- @table Config
HorseCollisionMod.Config = {
	-- Speed tiers, in meters per second. Below SpeedWalk nothing happens.
	SpeedWalk                = 1.8,
	SpeedTrot                = 4.5,
	SpeedGallop              = 8.5,

	-- Detection. HitRadius is a broad-phase sphere; everything inside it is
	-- then tested against the horse footprint, in meters from the horse
	-- origin. The sweep extends the footprint forward by one tick of travel.
	HitRadius                = 2.5,
	HorseFrontReach          = 1.05,
	HorseRearReach           = 0.20,
	HorseHalfWidth           = 0.35,
	HorseMaxVerticalDiff     = 2.35,
	TickSeconds              = 0.1,
	SweepMultiplier          = 0.50,
	MaxSweepExtra            = 0.35,
	HitCooldownMs            = 3000,
	KnockdownRecoveryMs      = 6000,

	-- A collision is scored on the peak of the last ImpactSpeedSamples ticks,
	-- not on the speed read when the victim is noticed. MaxImpactSpeed is the
	-- ceiling on that value, a little above the top of the gallop plateau.
	ImpactSpeedSamples       = 3,
	MaxImpactSpeed           = 11.0,

	-- Knockdown impulse. Trot and gallop only; the walk tier never ragdolls.
	Knockback                = 50.0,
	Uplift                   = 30.0,

	-- What the target is wearing, as a multiplier on the impulse and on the
	-- horse's stamina cost. Both are 1.0 at ArmorReferenceWeight; an
	-- exponent of 0 switches that half off.
	ArmorReferenceWeight     = 8.0,
	ArmorImpulseExponent     = 0.5,
	MinArmorImpulse          = 0.35,
	MaxArmorImpulse          = 1.5,
	ArmorStaminaExponent     = 0.4,
	MinArmorStamina          = 0.75,
	MaxArmorStamina          = 3.0,

	-- Horse stamina, against a full pool of roughly 210.
	StaminaDrainWalk         = 0.0,
	StaminaDrainTrot         = 18.0,
	StaminaDrainGallop       = 22.0,
	ThrowRiderOnStaminaEmpty = true,

	-- How long a victim is exempted from vanilla's auto-cure daycycle,
	-- in seconds. Zero leaves them in it.
	SuppressAutoCureSec      = 30,

	-- What a trot impact does. "knockdown" plays an animated fall through
	-- the same path as the walk stagger and creates no physics body, so it
	-- cannot incur the trample damage a ragdoll does. "ragdoll" is the
	-- physics knockdown the mod shipped before.
	TrotReaction             = "knockdown",

	-- Takes movement control off the animation once a reaction has started,
	-- so the victim is moved by the entity rather than by root motion and
	-- stops being carried through walls. False restores the behavior before
	-- this, where a stagger beside a building could end inside it.
	ReleaseAnimationMovement = true,

	-- Sends a victim back to their activity once their reaction is over, so
	-- they walk to whatever they were using and are aligned to it on the way
	-- in rather than resuming it from wherever they fell.
	ReplanAfterReaction      = true,

	-- The health at or above which a victim is no longer a candidate for
	-- vanilla's auto-cure daycycle. Vanilla's own limit is 40, declared as
	-- `t_autoCureLowHealthLimit` in `Libs/AI/final/sb_daycycles.xml`. The
	-- exemption is held until the victim is back over this.
	AutoCureHealthLimit      = 40.0,

	-- Combat.
	CombatStaminaMultiplier  = 2.2,
	SuppressStaggerInCombat  = true,

	-- Switches.
	ProtectMutt              = true,
	WalkStagger              = true,
	SendHitReaction          = true,
	LogTelemetry             = true,

	-- Names the reason a nearby NPC produced no reaction. Every test in the
	-- detection loop rejects silently, so a missed impact and an impact that
	-- never happened look identical. Off by default: it is noisy and only
	-- useful while investigating.
	DiagnoseMisses           = false
}


--- Engine enum, transcribed from `Libs/AI/TypeDefinitions.xml`.
--
-- The values are deliberately non-sequential; they mirror a C++ enum. The
-- full set is kept rather than just the value used, so the contract stays
-- verifiable against the engine.
--
-- @table HitReactionType
HorseCollisionMod.HitReactionType = {
	Melee = 1,
	Collision = 2,
	Fall = 7,
	Bullet = 10,
	MeleeStealth = 16
}

--- Engine enum, transcribed from `Libs/AI/TypeDefinitions.xml`.
--
-- Ascending severity. `Tickle` and `Unpleasant` cost the victim no health.
--
-- @table HitReactionStrength
HorseCollisionMod.HitReactionStrength = {
	Zero = 0,
	Healing = 1,
	Tickle = 2,
	Unpleasant = 3,
	Exhausting = 4,
	MinorInjury = 5,
	MajorInjury = 6,
	Fatal = 7
}

--- When each victim may react again, in milliseconds, keyed by entity id.
--
-- Holds the time a victim becomes eligible rather than the time it was last
-- hit, because how long that takes depends on what the last impact did. A
-- stagger is over quickly; a knockdown leaves them on the ground for several
-- seconds.
-- @table RecentHits
HorseCollisionMod.RecentHits = {}

--- Last time each entity was reported as a miss, keyed by entity id.
HorseCollisionMod.RecentRejections = {}

--- Recent horse speeds, newest last, for spotting deceleration on impact.
--
-- Speed is sampled once per tick at the top of the loop. A collision slows the
-- horse, so if a victim only enters the footprint on the tick after contact
-- begins, the speed read is the speed after the impact rather than the speed
-- that caused it. That would explain a gallop being recorded as a walk, and it
-- would also drop the reaction entirely whenever the loss takes the horse under
-- `SpeedWalk`, because that test returns before any entity is examined.
--
-- Kept deliberately short. Half a second of history is enough to see a
-- deceleration and not so much that an earlier gallop colours a later walk.
HorseCollisionMod.SpeedHistory = {}

HorseCollisionMod.SpeedHistorySize = 10


-- How long after a reaction begins the victim is rebuilt, per tier.
--
-- Timed from the start of the reaction, because nothing here reads whether the
-- victim is still on the ground, so the figure has to cover the whole fall and
-- get-up. Too short cuts the animation; every millisecond past the end is time
-- the victim spends standing idle before their own behavior resumes.
--
-- Separate per tier because a stagger is over in about a second while a
-- knockdown runs several times longer. Not settings: once these are right
-- there is no reason for a player to hold an opinion about them.
-- How the end of a reaction is recognized, so the rebuild is triggered by an
-- observation rather than by a clock guessing at the animation's length.
--
-- `actor:GetCurrentAnimationState()` reports `AnimationControlled` for exactly
-- as long as an interactive action owns the actor, and the value it changes to
-- afterwards is an ordinary locomotion state. Leaving that value is therefore
-- the reaction ending, whatever clip played and however long it ran.
--
-- A fixed delay cannot do this job. Measured across knockdowns the state was
-- held for anywhere between 4.3 and 7.0 seconds, and a stagger released it in
-- 2.3, so any single figure lands inside the range and rebuilds some victims
-- mid-animation. Rebuilding mid-animation is worse than not rebuilding at all,
-- because the animation takes the body back afterwards and the freeze the
-- rebuild exists to prevent happens anyway.
--
-- The ceiling covers a victim who dies, unstreams, or holds the state past
-- anything observed, and the state must have been seen at least once before
-- leaving it counts, so a poll landing before the action starts cannot be
-- mistaken for the reaction already being over.
HorseCollisionMod.ReactionAnimationState = "AnimationControlled"
HorseCollisionMod.ReactionPollMs = 100
HorseCollisionMod.ReactionEndCeilingMs = 12000


local function GetTimeMs()
	return System.GetCurrTime() * 1000
end

--- Magnitude of a CryEngine vector.
-- @tparam ?table v vector with x, y and z components, or nil
-- @treturn number length, or 0 when v is nil
local function GetVectorLength(v)
	if not v then
		return 0
	end

	return math.sqrt((v.x * v.x) + (v.y * v.y) + (v.z * v.z))
end

--- Records one speed sample.
--
-- @tparam number speed the current sample, in meters per second
function HorseCollisionMod:TrackSpeed(speed)
	local history = self.SpeedHistory

	history[#history + 1] = speed

	while #history > self.SpeedHistorySize do
		table.remove(history, 1)
	end
end

--- The peak of the last `count` speed samples.
--
-- @tparam number count how many of the most recent samples to consider
-- @treturn number the highest speed among them, in meters per second
function HorseCollisionMod:RecentPeak(count)
	local history = self.SpeedHistory
	local first = #history - count + 1
	local peak = 0

	if first < 1 then
		first = 1
	end

	for i = first, #history do
		if history[i] > peak then
			peak = history[i]
		end
	end

	return peak
end

--- The recent speed samples, oldest first, as a compact string.
--
-- Printed on every impact while diagnosing. The width of the deceleration on
-- contact is what sets `ImpactSpeedSamples`, and it is only visible in the
-- samples either side of the collision.
--
-- @tparam number count how many of the most recent samples to include
-- @treturn string the samples, space separated, to two decimal places
function HorseCollisionMod:SpeedTrail(count)
	local history = self.SpeedHistory
	local first = #history - count + 1
	local parts = {}

	if first < 1 then
		first = 1
	end

	for i = first, #history do
		parts[#parts + 1] = string.format("%.2f", history[i])
	end

	return table.concat(parts, " ")
end

--- The speed a collision should be scored at.
--
-- A horse loses speed the moment it hits someone. Detection samples velocity
-- once per tick, so the speed read on the tick that notices a victim has
-- already been reduced by the collision it is meant to describe, and a gallop
-- impact can be scored as a walk. The peak of the last few samples brackets
-- the moment of contact instead.
--
-- The window is deliberately short. Taken over a whole second it would charge
-- gallop to a rider who galloped up and then slowed deliberately to nudge
-- someone.
--
-- Capped because the physics system reports occasional speeds above anything a
-- horse holds, and this value scales knockback force as well as selecting the
-- tier.
--
-- @treturn number the speed to score the impact at, in meters per second
function HorseCollisionMod:ImpactSpeed()
	local peak = self:RecentPeak(self.Config.ImpactSpeedSamples)

	if peak > self.Config.MaxImpactSpeed then
		return self.Config.MaxImpactSpeed
	end

	return peak
end

--- Logs why a candidate was passed over, at most once per second per entity.
--
-- Every rejection in the detection loop is silent, so an impact that produces
-- no reaction is indistinguishable from one that was never detected. This
-- names the reason.
--
-- Rate limited because the loop runs about twenty times a second and the
-- detection sphere returns everything nearby, including crates and doors.
--
-- @tparam table npc the entity that was rejected
-- @tparam string reason short label for which test rejected it
-- @tparam string detail the measurement behind that decision
function HorseCollisionMod:LogRejection(npc, reason, detail)
	if not self.Config.DiagnoseMisses then
		return
	end

	local id = tostring(npc and npc.id or "?")
	local now = GetTimeMs()
	local last = self.RecentRejections[id]

	if last and (now - last) < 1000 then
		return
	end

	self.RecentRejections[id] = now

	local name = "?"

	pcall(function()
		name = npc:GetName() or "?"
	end)

	self:Log("Miss " .. reason .. " name=" .. tostring(name)
			.. " " .. tostring(detail))
end


--- Current time in milliseconds.
-- @treturn number milliseconds since the game session started
--- Writes a prefixed line to kcd.log when telemetry is enabled.
-- @tparam string message text to log
function HorseCollisionMod:Log(message)
	if not self.Config.LogTelemetry then
		return
	end

	System.LogAlways("[HorseCollisionMod] " .. tostring(message))
end

--- Resolves a speed to its gait name.
-- @tparam number speed speed in meters per second
-- @treturn string one of "Gallop", "Trot", "Walk" or "Idle"
function HorseCollisionMod:GetSpeedTier(speed)
	local cfg = self.Config

	if speed >= cfg.SpeedGallop then
		return "Gallop"
	end

	if speed >= cfg.SpeedTrot then
		return "Trot"
	end

	if speed >= cfg.SpeedWalk then
		return "Walk"
	end

	return "Idle"
end

--- Posts the native `hitReaction` message to the victim's brain.
--
-- This is what makes the vanilla collision bark, perception and crime
-- handling fire, so the reaction still feels like part of the game rather
-- than something bolted on. It does **not** drive animation.
--
-- Delivery is best effort. The receiving handler is declared `Atomic="true"`
-- and drops messages when busy, so nothing here may depend on a given
-- message arriving.
--
-- @tparam table npc victim entity
-- @tparam userdata horseWuid WUID of the horse, sent as the attacker
-- @tparam number strength a `HitReactionStrength` value
function HorseCollisionMod:SendHitReaction(npc, horseWuid, strength)
	if not self.Config.SendHitReaction then
		return
	end

	pcall(function()
		-- Brain messages carry their arguments as a "key(value), key(value)"
		-- string rather than a table.
		local values = "hitStrength(" .. tostring(strength)
				.. "), hitType(" .. tostring(self.HitReactionType.Collision) .. ")"

		-- The horse is named as the attacker, not Henry. That matches what
		-- the engine does for a trample, and the victim's brain resolves the
		-- rider from the horse itself when assigning blame.
		if horseWuid and Framework and Framework.WUIDToMsg then
			values = "attacker(" .. Framework.WUIDToMsg(horseWuid) .. "), " .. values
		end

		XGenAIModule.SendMessageToEntity(npc.id, "hitReaction", values)
	end)
end

--- Logs a named entity's health whenever it changes.
--
-- Health has moved in every ride with no impact to account for it, and an
-- impact the footprint rejects writes no line at all, so there is nothing to
-- correlate the loss against. Watching one target records the moment health
-- moves, whether or not the mod caused it.
--
-- A diagnostic, started from the console rather than from play. It samples
-- twice a second and writes only on a change, so a quiet watch costs two
-- lines.
--
-- @tparam string name entity name to watch
-- @tparam number seconds how long to watch, default 90
function HorseCollisionMod:WatchHealth(name, seconds)
	local ent = System.GetEntityByName(name)

	if not ent or not ent.soul then
		self:Log("Watch " .. tostring(name) .. " not found")
		return
	end

	-- The same generation guard the detection loop uses. A watch left running
	-- across a load screen would otherwise hold a stale entity forever.
	local generation = self.TimerTick
	local deadline = System.GetCurrTime() + (seconds or 90)
	local last = nil

	local function tick()
		if generation ~= self.TimerTick then
			return
		end

		local ok, health = pcall(function()
			return ent.soul:GetState("health")
		end)

		if not ok or type(health) ~= "number" then
			self:Log("Watch " .. name .. " lost")
			return
		end

		if last and health ~= last then
			local z = "?"
			local away = "?"

			-- Where the rider was standing when the health moved. A loss with
			-- the horse alongside is a contact the footprint rejected; a loss
			-- with the horse far off is something else entirely.
			pcall(function()
				local q = ent:GetWorldPos()
				local r = player:GetWorldPos()

				z = string.format("%.2f", q.z)
				away = string.format("%.1f", math.sqrt(
						(q.x - r.x) * (q.x - r.x)
						+ (q.y - r.y) * (q.y - r.y)))
			end)

			self:Log("Watch " .. name
					.. " health=" .. string.format("%.4f", health)
					.. " delta=" .. string.format("%+.4f", health - last)
					.. " z=" .. z
					.. " rider=" .. away .. "m"
					.. " speed=" .. string.format("%.2f", self:RecentPeak(3)))
		end

		last = health

		if System.GetCurrTime() < deadline then
			Script.SetTimer(500, tick)
		else
			self:Log("Watch " .. name .. " ended health="
					.. string.format("%.4f", health))
		end
	end

	self:Log("Watch " .. name .. " started health="
			.. string.format("%.4f", ent.soul:GetState("health")))
	tick()
end


--- What an entity is wearing, summed from its inventory.
--
-- Nothing in the ScriptBind surface reports which items are equipped, and
-- nothing reports an item's weight. Neither gap matters for a collision
-- target: an NPC carries only what it wears plus a few trinkets, and the
-- weights are generated into `HorseCollisionMod_ItemData.lua` from the game's
-- own tables. Filtering an inventory to the classes in that table is therefore
-- equivalent to reading the equipped set.
--
-- The player is the exception, carrying whatever has been picked up, but the
-- player is never the victim of an impact.
--
-- Saddles, bridles, horseshoes and spurs are filed as armor. `tack` selects
-- between the two: false for what a person is wearing, true for a horse's own
-- gear, which is what Phase 3 barding needs from the same call.
--
-- @tparam table entity any entity with an inventory
-- @tparam[opt] boolean tack true to sum horse gear instead of worn armor
-- @treturn table weight, smashDef, pieces, heaviest and heaviestType
function HorseCollisionMod:ArmorOf(entity, tack)
	local total = {
		weight = 0,
		smashDef = 0,
		pieces = 0,
		heaviest = 0,
		heaviestType = 0,
	}

	local data = rawget(_G, "HorseCollisionModItemData")

	if not data or not entity or not entity.inventory then
		return total
	end

	local ok, items = pcall(function()
		return entity.inventory:GetInventoryTable()
	end)

	if not ok or type(items) ~= "table" then
		return total
	end

	for _, wuid in pairs(items) do
		-- Per item rather than around the loop. An entity streaming out
		-- mid-sum would otherwise discard the pieces already counted.
		pcall(function()
			local item = ItemManager.GetItem(wuid)

			if not item or not item.class then
				return
			end

			local row = data.Armor[item.class]

			if not row then
				return
			end

			local isTack = data.TackTypes[row[3]] == true

			if isTack ~= (tack == true) then
				return
			end

			total.weight = total.weight + row[1]
			total.smashDef = total.smashDef + row[2]
			total.pieces = total.pieces + 1

			if row[1] > total.heaviest then
				total.heaviest = row[1]
				total.heaviestType = row[3]
			end
		end)
	end

	return total
end


--- An armor total as a log fragment.
--
-- @tparam table total a table from `ArmorOf`
-- @treturn string the totals, and the heaviest piece's type by name
function HorseCollisionMod:DescribeArmor(total)
	local data = rawget(_G, "HorseCollisionModItemData")
	local kind = "none"

	if data and data.TypeNames[total.heaviestType] then
		kind = data.TypeNames[total.heaviestType]
	end

	return "pieces=" .. tostring(total.pieces)
			.. " weight=" .. string.format("%.1f", total.weight)
			.. " smashDef=" .. string.format("%.2f", total.smashDef)
			.. " heaviest=" .. kind
end


--- How much a target's armor changes the impact it takes.
--
-- One curve serves both halves. `weight` is the target's armor weight and
-- `reference` the weight that changes nothing, so the ratio between them is
-- the whole signal; `exponent` sets how sharply it bites and 0 switches the
-- scaling off entirely.
--
-- Armor makes a target harder to throw and more tiring to hit, so the impulse
-- takes the reciprocal of the ratio and the stamina cost takes it directly.
-- Both are clamped, because the curve has no natural floor or ceiling and an
-- unclamped extreme reads in game as a target that cannot be moved at all, or
-- one that flies out of sight.
--
-- @tparam number weight the target's armor weight
-- @tparam number reference the weight that produces 1.0
-- @tparam number exponent how strongly weight matters, 0 to disable
-- @tparam boolean invert true for the impulse, false for the stamina cost
-- @tparam number low the smallest multiplier allowed
-- @tparam number high the largest
-- @treturn number the multiplier
function HorseCollisionMod:ArmorCurve(weight, reference, exponent, invert, low, high)
	if exponent == 0 or reference <= 0 then
		return 1.0
	end

	-- A target wearing nothing at all still has a body. Without a floor the
	-- ratio goes to infinity and the clamp becomes the only thing deciding
	-- the result, which hides the setting rather than applying it.
	local w = weight

	if w < 0.5 then
		w = 0.5
	end

	local ratio = w / reference

	if invert then
		ratio = reference / w
	end

	local scale = math.pow(ratio, exponent)

	if scale < low then
		return low
	end

	if scale > high then
		return high
	end

	return scale
end


--- The impulse multiplier for a target's armor.
--
-- @tparam table armor a table from `ArmorOf`
-- @treturn number a multiplier on the tier's impulse scale
function HorseCollisionMod:ArmorImpulseScale(armor)
	local cfg = self.Config

	return self:ArmorCurve(armor.weight, cfg.ArmorReferenceWeight,
			cfg.ArmorImpulseExponent, true,
			cfg.MinArmorImpulse, cfg.MaxArmorImpulse)
end


--- The stamina multiplier for a target's armor.
--
-- Composes with the combat multiplier already applied, and is the same shape
-- the Phase 3 Horsemanship multiplier will take, so the three multiply rather
-- than each becoming its own rule.
--
-- @tparam table armor a table from `ArmorOf`
-- @treturn number a multiplier on the tier's stamina cost
function HorseCollisionMod:ArmorStaminaScale(armor)
	local cfg = self.Config

	return self:ArmorCurve(armor.weight, cfg.ArmorReferenceWeight,
			cfg.ArmorStaminaExponent, false,
			cfg.MinArmorStamina, cfg.MaxArmorStamina)
end


-- When the impact probe samples, in milliseconds after the hit.
--
-- 500 catches what the impact cost, since the engine applies damage after the
-- message is handled. 3000 catches anything continuing. 6000 and 10000 reach
-- past the get-up, which a ragdoll does not finish before the earlier samples
-- have already been taken.
--
-- Documented as an ordinary comment rather than an LDoc block: LDoc reads an
-- annotated table as a set of named fields and refuses one holding an array.
HorseCollisionMod.ImpactProbeSamples = { 500, 3000, 6000, 10000 }


--- Exempts a collision victim from vanilla's auto-cure daycycle.
--
-- An NPC carrying a bleeding or poison buff whose health is under
-- `t_autoCureLowHealthLimit`, which vanilla sets to 40, enters the
-- `cureLookHurt` behavior in `Libs/AI/final/sb_daycycles_cure.xml`. That
-- subtree plays the `PretendingIllness` animation under a wait with no
-- timeout, and regenerates health at 0.02 per second. Nothing inside it ends,
-- so a victim left under the threshold stands in the street until health
-- climbs back over it, which takes a quarter of an hour of game time and
-- reads as a permanently broken NPC.
--
-- Vanilla exempts its own characters from the daycycle through a context
-- option, used for duellists and for scripted wanderers among others. The
-- same option is set here, and cleared on a timer.
--
-- The gate admitting the cure is read only on entry, so the option has to be
-- in place before health crosses the threshold. It is set at the moment of
-- impact, and collision damage resolves around half a second later.
--
-- @tparam table npc victim entity
function HorseCollisionMod:SuppressAutoCure(npc)
	local HANDLE = "HorseCollisionMod"
	local seconds = self.Config.SuppressAutoCureSec

	if type(seconds) ~= "number" or seconds <= 0 then
		return
	end

	if not npc or not npc.id or type(XGenAIModule) ~= "table" then
		return
	end

	if type(Contexts) ~= "table" then
		return
	end

	-- The message form, `context:timedOptionRequest`, carries its own
	-- expiration and reads as the tidier option, but it is a request to the
	-- brain and a busy brain drops it: sent to a guard in combat, the option
	-- read back false immediately. The direct call writes the Contexts table
	-- and does not depend on the brain accepting anything.
	--
	-- Non-persistent is deliberate. The option does not survive a save, so an
	-- exemption this code fails to clear cannot become permanent in a player's
	-- game.
	pcall(function()
		Contexts.SetNonpersistentOption(npc, "suppressAutoCure", HANDLE)
	end)

	local held = false
	pcall(function()
		held = Contexts.CheckOption(npc, "suppressAutoCure")
	end)

	if self.Config.LogTelemetry then
		local name = "?"
		pcall(function() name = npc:GetName() or "?" end)
		self:Log("SuppressAutoCure " .. name .. " for=" .. tostring(seconds)
				.. "s set=" .. tostring(held))
	end

	if not held then
		return
	end

	-- Releases a victim already held by the cure, which the exemption alone
	-- cannot do: the gate admitting the subtree is only read on entry, so an
	-- option set afterwards leaves a running cure running. The cure installs
	-- itself as a daycycle patch under this handle, and removing it ends the
	-- activity. The order matters, because removing the patch while the victim
	-- is still bleeding under the threshold and not yet exempt lets the cure
	-- start again immediately.
	--
	-- On a victim that was never stuck this reports false and costs nothing,
	-- so it doubles as the repair path for a save carrying stuck NPCs: any
	-- victim ridden into again is released.
	pcall(function()
		local wuid = XGenAIModule.GetMyWUID(npc)

		if wuid then
			XGenAIModule.RemoveDaycyclePatch(wuid, "curePatch")
		end
	end)

	-- Held for as long as the victim is a candidate for the cure, rather than
	-- for a fixed time. A fixed window cannot be chosen, because what it has
	-- to outlast is the victim climbing back over the threshold at vanilla's
	-- 0.02 health per second, which from thirty health is nearly nine minutes.
	-- A window that lapses while the victim is still below it opens the gate
	-- and the cure starts immediately.
	--
	-- One watcher per victim. A second impact replaces the token, so the
	-- earlier watcher stops on its next pass rather than running alongside.
	local token = (self.CureWatchToken or 0) + 1
	self.CureWatchToken = token
	self.CureWatch = self.CureWatch or {}

	local key = tostring(npc.id)
	self.CureWatch[key] = token

	local function release()
		pcall(function()
			Contexts.ClearOption(npc, "suppressAutoCure", HANDLE)
		end)
	end

	local function watch()
		if self.CureWatch[key] ~= token then
			return
		end

		local health = nil

		pcall(function()
			health = npc.soul:GetState("health")
		end)

		-- A victim that is gone, dead, or safely above the threshold has no
		-- further use for the exemption.
		if type(health) ~= "number" or health <= 0
				or health >= self.Config.AutoCureHealthLimit then
			self.CureWatch[key] = nil
			release()

			return
		end

		Script.SetTimer(seconds * 1000, watch)
	end

	Script.SetTimer(seconds * 1000, watch)
end


--- Samples the victim's health across an impact.
--
-- Vanilla converts a collision hit whose rider is the player into a real
-- `combat:hit` attributed to the player, carrying the `hitStrength` sent
-- here. The engine resolves damage and the reputation change from that
-- strength, and applies both after the message is handled, so neither is
-- readable at the moment of the hit. The health state is sampled again on a
-- timer instead.
--
-- Four samples, because they answer different questions. The first shows what
-- the impact itself cost. The rest reach past the get-up, because health is
-- also lost after a ragdoll resolves, in discrete amounts that look like a
-- fall rather than like bleeding.
--
-- Height is sampled alongside health for the same reason. The impulse throws
-- the target, and a change in z across the recovery separates a fall from
-- anything the collision itself did.
--
-- @tparam table npc victim entity
-- @tparam string tierName the tier the impact scored
-- @tparam number strength the `HitReactionStrength` sent with the hit
-- @tparam[opt] table armor totals from `ArmorOf`, read again when absent
function HorseCollisionMod:ProbeImpactCost(npc, tierName, strength, armor)
	if not self.Config.LogTelemetry or not npc or not npc.soul then
		return
	end

	local ok, before = pcall(function()
		return npc.soul:GetState("health")
	end)

	if not ok or type(before) ~= "number" then
		return
	end

	local name = "?"
	pcall(function()
		name = npc:GetName() or "?"
	end)

	local function height()
		local okPos, pos = pcall(function()
			return npc:GetWorldPos()
		end)

		if okPos and type(pos) == "table" and type(pos.z) == "number" then
			return pos.z
		end

		return nil
	end

	local baseZ = height()

	-- Where the victim stood when the impact landed. A reaction should leave
	-- them near it; travelling on while animation-controlled is how a victim
	-- reaches somewhere the collision never put them.
	local origin = nil

	pcall(function()
		origin = npc:GetWorldPos()
	end)

	local exhaust = -1

	pcall(function()
		exhaust = npc.soul:GetState("exhaust") or -1
	end)

	self:Log("ImpactCost " .. name .. " tier=" .. tierName
			.. " strength=" .. tostring(strength)
			.. " health=" .. string.format("%.4f", before)
			.. " z=" .. (baseZ and string.format("%.2f", baseZ) or "?")
			.. " exhaust=" .. string.format("%.1f", exhaust)
			.. " " .. self:DescribeArmor(armor or self:ArmorOf(npc)))

	local function sample(label)
		local okAfter, after = pcall(function()
			return npc.soul:GetState("health")
		end)

		if not okAfter or type(after) ~= "number" then
			return
		end

		local z = height()
		local dz = "?"
		local travel = "?"

		pcall(function()
			if origin then
				local q = npc:GetWorldPos()

				if q then
					travel = string.format("%.2f",
							math.sqrt((q.x - origin.x) ^ 2
									+ (q.y - origin.y) ^ 2))
				end
			end
		end)

		if z and baseZ then
			dz = string.format("%+.2f", z - baseZ)
		end

		-- The starting health is repeated on every sample. Samples now run
		-- past the cooldown, so a second impact on the same target can
		-- interleave its lines with the first one's, and the name alone no
		-- longer identifies which impact a sample belongs to.
		self:Log("ImpactCost " .. name .. " " .. label
				.. " from=" .. string.format("%.4f", before)
				.. " health=" .. string.format("%.4f", after)
				.. " delta=" .. string.format("%+.4f", after - before)
				.. " dz=" .. dz
				.. " travel=" .. travel)
	end

	for _, at in ipairs(self.ImpactProbeSamples) do
		Script.SetTimer(at, function()
			sample("t+" .. at .. "ms")
		end)
	end
end


--- Tests whether a victim is actually under the horse.
--
-- The sphere search is a broad-phase cull and nothing more. A horse is about
-- two meters long and under a meter wide, so a sphere around its origin also
-- catches people walking alongside or trailing behind it, which is what makes
-- collisions feel like they reach too far.
--
-- This narrows the sphere to an oriented box: the victim must be within the
-- horse's width laterally, between its rear and front reach along its facing,
-- and at a comparable height. The front reach is extended by the distance the
-- horse travels in one tick so that fast victims are not missed between
-- frames.
--
-- @tparam table npc victim entity
-- @tparam table horsePos world position of the horse
-- @tparam table horseForward horse facing, unit vector
-- @tparam number speed horse speed in meters per second
-- @treturn boolean true when the victim is inside the footprint
function HorseCollisionMod:IsInHorseFootprint(npc, horsePos, horseForward, speed)
	local cfg = self.Config
	local npcPos = nil

	pcall(function()
		npcPos = npc:GetPos()
	end)

	if not npcPos or not horsePos or not horseForward then
		return false
	end

	local dx = npcPos.x - horsePos.x
	local dy = npcPos.y - horsePos.y
	local dz = npcPos.z - horsePos.z

	-- Rejects anyone on a bridge overhead or in a cellar below, who would
	-- otherwise pass the flat two-dimensional test.
	if math.abs(dz) > cfg.HorseMaxVerticalDiff then
		return false
	end

	-- Distance along the horse's facing, and perpendicular to it. The
	-- perpendicular is taken directly from the forward vector rather than
	-- asking the engine for a second axis, so the two cannot disagree.
	local forwardDistance = (horseForward.x * dx) + (horseForward.y * dy)
	local lateralDistance = math.abs((horseForward.y * dx) - (horseForward.x * dy))

	local sweepExtra = speed * cfg.TickSeconds * cfg.SweepMultiplier

	if sweepExtra > cfg.MaxSweepExtra then
		sweepExtra = cfg.MaxSweepExtra
	end

	local inside = forwardDistance >= -cfg.HorseRearReach
			and forwardDistance <= (cfg.HorseFrontReach + sweepExtra)
			and lateralDistance <= cfg.HorseHalfWidth

	local detail = "fwd=" .. string.format("%.2f", forwardDistance)
			.. " lat=" .. string.format("%.2f", lateralDistance)
			.. " dz=" .. string.format("%.2f", dz)
			.. " sweep=" .. string.format("%.2f", sweepExtra)
			.. " limits=" .. string.format("%.2f/%.2f/%.2f",
					cfg.HorseFrontReach + sweepExtra, cfg.HorseHalfWidth,
					cfg.HorseMaxVerticalDiff)

	if inside then
		self:Log("Footprint " .. detail)
	end

	return inside, detail
end


--- Measurements for a candidate the footprint test rejected.
--
-- Same geometry as the test itself rather than a second copy of it, so the
-- numbers reported are the numbers the decision was made on.
--
-- @treturn string the distances and the limits they were checked against
function HorseCollisionMod:FootprintDetail(npc, horsePos, horseForward, speed)
	local _, detail = self:IsInHorseFootprint(npc, horsePos, horseForward, speed)

	return detail or "unmeasurable"
end

--- Works out which side of the victim the impact lands on.
--
-- The stagger clips are authored relative to the NPC's facing, so the impact
-- has to be expressed in the victim's own frame. Using the horse's frame
-- instead makes NPCs stagger into the horse rather than away from it.
--
-- The impact is derived from the horse's **direction of travel**, not its
-- position. Position is ambiguous at the moment of contact, when the horse
-- is effectively on top of the victim and a centimeter either way flips the
-- answer. Travel direction is stable, and it is what actually decides which
-- side of the body is struck: a horse moving north hits the south face of
-- whoever is in front of it.
--
-- @tparam table npc victim entity
-- @tparam table velocity horse velocity vector
-- @tparam number speed horse speed in meters per second
-- @treturn string one of "so_forward", "so_back", "so_left", "so_right"
function HorseCollisionMod:GetImpactDir(npc, velocity, speed)
	local forward = nil

	pcall(function()
		if npc.GetDirectionVector then
			forward = npc:GetDirectionVector(1)
		end
	end)

	if not forward or not velocity or speed <= 0 then
		return "so_forward"
	end

	-- The blow arrives from the direction the horse came from, which is the
	-- opposite of its travel. Flattened to the ground plane, since a rider
	-- is always above a pedestrian and the height would bias every result.
	local fromX = -velocity.x / speed
	local fromY = -velocity.y / speed

	-- Projected onto the victim's axes: dot is how much the blow comes from
	-- ahead of them (negative means from behind), cross is how much it comes
	-- from their left (negative means their right).
	local dot = (forward.x * fromX) + (forward.y * fromY)
	local cross = (forward.x * fromY) - (forward.y * fromX)

	-- The larger magnitude wins, which snaps the blow to the nearest of the
	-- four authored clips. Comparing magnitudes rather than testing a fixed
	-- angle means a glancing hit still resolves sensibly.
	if math.abs(dot) >= math.abs(cross) then
		if dot >= 0 then
			return "so_forward"
		end

		return "so_back"
	end

	if cross >= 0 then
		return "so_left"
	end

	return "so_right"
end

--- Stops the animation driving a victim's own movement.
--
-- `actor:SetMovementControlledByAnimation` is the runtime equivalent of a
-- fragment's `MovementControlMethod` layer, and it is the only lever that
-- applies to one victim rather than to every option in the database. Turning
-- it off leaves the actor on entity-driven movement, which is the state
-- vanilla's own hit reactions play in and the reason they respect geometry an
-- interactive action passes through.
--
-- Called on the tick after the action starts, never before it. An interactive
-- action applies the fragment's own movement control as it begins, so a call
-- made ahead of it is overwritten and does nothing at all: victims clipped
-- into walls exactly as they did without it.
--
-- @tparam table npc victim entity
-- @treturn boolean true when the call was accepted without error
function HorseCollisionMod:ReleaseVictimMovement(npc)
	if not npc.actor
			or type(npc.actor.SetMovementControlledByAnimation) ~= "function" then
		return false
	end

	local ok, err = pcall(function()
		npc.actor:SetMovementControlledByAnimation(false)
	end)

	if self.Config.LogTelemetry then
		self:Log("MovementControl released ok=" .. tostring(ok)
				.. " err=" .. tostring(err))
	end

	return ok
end

--- Records how far a reaction turned its victim.
--
-- TEMPORARY, for one pair of diagnostic rides. Remove before this branch
-- merges.
--
-- Measurement only. This reads a heading twice and writes a log line; it never
-- sets an angle. Three earlier mechanisms tried to correct this value from Lua
-- and all three were removed, because at a smart object the angle belongs to
-- the object and is written when the victim approaches it.
--
-- What is being separated is whether the rotation belongs to the animation or
-- to the mod. `ReleaseAnimationMovement` takes the body off the animation's
-- root motion so it stops passing through walls; whether that also changes what
-- the clip does to the victim's heading has never been measured. Running this
-- with the setting on and again with it off answers that, and the answer
-- decides whether the drift is a property of the clip or the price of the
-- anti-clipping fix.
--
-- @tparam table npc victim entity
-- @tparam string action the reaction being played
function HorseCollisionMod:MeasureReactionTurn(npc, action)
	if not self.Config.LogTelemetry then
		return
	end

	local function heading()
		local z = nil

		pcall(function()
			z = npc:GetAngles().z
		end)

		return type(z) == "number" and z or nil
	end

	local before = heading()

	if not before then
		return
	end

	local generation = self.TimerTick

	self:WhenReactionEnds(npc, function(why, waited)
		if generation ~= self.TimerTick then
			return
		end

		local after = heading()

		if not after then
			return
		end

		local turn = math.pi * 2
		local drift = ((after - before + math.pi) % turn) - math.pi

		self:Log("ReactionTurn " .. action
				.. " released=" .. tostring(self.Config.ReleaseAnimationMovement)
				.. " drift=" .. string.format("%+.0f", math.deg(drift))
				.. "deg on=" .. why
				.. " waited=" .. string.format("%.0f", waited) .. "ms")
	end)
end

--- Sends a victim back to their activity by way of approaching it again.
--
-- A smart object reaches its loop through `Move` to the object followed by
-- `ExactMove directionType="AlignWithEntity"`, so the angle an NPC holds while
-- leaning on a wall or standing at a stall is the object's, written by the
-- approach rather than owned by the NPC.
--
-- A reaction leaves the victim near enough to that object to resume the loop
-- without approaching it. The alignment never runs, and the loop plays at
-- whatever angle the fall left them at, which reads in game as an innkeeper
-- leaning into a wall from the wrong side. A victim thrown clear of the object
-- walks back instead and is aligned correctly on the way in, which is the same
-- code producing the correct result for the only reason that matters: the
-- approach happened.
--
-- Restarting the daycycle is what makes the approach happen. Vanilla sends the
-- same message from `Libs/AI/final/sb_switch_hitreactions.xml` after its own
-- hit reactions, and from `Scripts/Haste/hasteInstruction_teleportBase.lua`
-- after teleporting an NPC, both being cases where a body has been moved
-- without its behavior being told.
--
-- Entity links are not involved. Probing a victim before a reaction, after it
-- and after the rebuild showed an unchanged list of persistent assignments, a
-- home and a workplace, with no `usedSO` link visible at any point.
--
-- @tparam table npc victim entity
-- @treturn boolean true when the message was accepted without error
function HorseCollisionMod:ReplanVictim(npc)
	if not self.Config.ReplanAfterReaction then
		return false
	end

	local ok, err = pcall(function()
		XGenAIModule.SendMessageToEntity(npc.id, "daycycle:restartRequest", "")
	end)

	if self.Config.LogTelemetry then
		self:Log("VictimReplan ok=" .. tostring(ok)
				.. " err=" .. tostring(err))
	end

	return ok
end

--- Runs something once a victim's reaction animation has finished.
--
-- Polls `actor:GetCurrentAnimationState()`, which reports
-- `AnimationControlled` for as long as an interactive action owns the actor.
-- Leaving that value is the reaction ending, which makes the wait an
-- observation instead of a guess at how long a particular clip runs.
--
-- The state must have been seen at least once before leaving it counts. A poll
-- landing in the gap before the action takes hold would otherwise read an
-- ordinary locomotion state and report a reaction that has not started yet as
-- already over.
--
-- @tparam table npc victim entity
-- @tparam function fn called with the reason (`state`, `ceiling` or
--   `unreadable`) and how long the wait took in milliseconds
function HorseCollisionMod:WhenReactionEnds(npc, fn)
	-- Entity ids are reused across a save load, so a wait booked before one
	-- and finishing after it would act on whichever NPC inherited the id,
	-- having been aimed at a victim from a world that no longer exists. The
	-- detection loop and the health watch carry the same guard.
	local generation = self.TimerTick
	local startedAt = GetTimeMs()
	local deadline = startedAt + self.ReactionEndCeilingMs
	local seen = false

	local function poll()
		if generation ~= self.TimerTick then
			return
		end

		local state = nil

		pcall(function()
			state = tostring(npc.actor:GetCurrentAnimationState())
		end)

		local elapsed = GetTimeMs() - startedAt

		if state == self.ReactionAnimationState then
			seen = true
		elseif seen then
			fn("state", elapsed)

			return
		end

		if GetTimeMs() >= deadline then
			fn(seen and "ceiling" or "unreadable", elapsed)

			return
		end

		Script.SetTimer(self.ReactionPollMs, poll)
	end

	Script.SetTimer(self.ReactionPollMs, poll)
end

--- Rebuilds a victim so their own behavior reattaches to their body.
--
-- An animated reaction hands the victim's body to the animation, and their
-- behavior is never told. The reaction ends with the body standing where it
-- fell while the victim's own idea of where they are carries on elsewhere, and
-- the two only rejoin the next time the engine rebuilds the actor. A player
-- triggers that by looking away and back, which drops the NPC to a level of
-- detail the engine repositions them from; until then the victim stands still
-- and then appears to teleport.
--
-- `entity:Hide(1)` followed immediately by `entity:Hide(0)` forces that
-- rebuild. Both calls are made together, with no timer between them: the
-- teardown happens on the call rather than over elapsed time, so the actor is
-- rebuilt without ever missing a frame of rendering. Separating them by even
-- twenty milliseconds is visible as a blink and buys nothing.
--
-- @tparam table npc victim entity
-- @treturn boolean true when the calls were accepted without error
function HorseCollisionMod:RebuildVictim(npc)
	if type(npc.Hide) ~= "function" then
		return false
	end

	local ok, err = pcall(function()
		npc:Hide(1)
		npc:Hide(0)
	end)

	if self.Config.LogTelemetry then
		self:Log("VictimRebuild ok=" .. tostring(ok)
				.. " err=" .. tostring(err))
	end

	return ok
end

--- Plays one of this mod's reactions on a victim.
--
-- Calls `actor:StartInteractiveActionByName` with a name this mod adds to the
-- animation database, chosen by joining `prefix` to the impact direction. See
-- the module header for why this is the only call that works.
--
-- The return value reports whether the call was accepted, which is **not**
-- the same as the animation playing: an unrecognized name is accepted and
-- then aborts within a frame. Only in-game observation confirms playback.
--
-- @tparam table npc victim entity
-- @tparam table velocity horse velocity vector
-- @tparam number speed horse speed in meters per second
-- @tparam string prefix the reaction family, `hcm_stagger_` at walk or
--   `hcm_knockdown_` at trot, completed with the impact direction
-- @treturn boolean true when the call was accepted without error
function HorseCollisionMod:PlayReaction(npc, velocity, speed, prefix)
	if not npc.actor or type(npc.actor.StartInteractiveActionByName) ~= "function" then
		return false
	end

	-- GetImpactDir speaks the engine's "so_" vocabulary; the database entries
	-- this mod adds are named without that prefix, so strip it.
	local dir = self:GetImpactDir(npc, velocity, speed)
	local action = prefix .. string.gsub(dir, "so_", "")


	-- Gender is logged because the female animation set has no
	-- AnimationControlled fragment, so female victims accept the call and
	-- play nothing. Without this the misses look random.
	local gender = "?"

	pcall(function()
		if npc.soul and npc.soul.GetGender then
			gender = tostring(npc.soul:GetGender())
		end
	end)

	local ok, err = pcall(function()
		-- The second argument is the object being interacted with. There is
		-- no object in a collision, so the victim is passed as its own
		-- target; the animation needs no alignment to anything external.
		npc.actor:StartInteractiveActionByName(action, npc.id, true, 1)
	end)

	-- Deferred by a tick for the same reason the ragdoll impulse is: the
	-- action has to have started before anything it sets can be overridden.
	if self.Config.ReleaseAnimationMovement then
		Script.SetTimer(50, function()
			self:ReleaseVictimMovement(npc)
		end)
	end

	-- TEMPORARY. Measurement only, removed before this branch merges.
	self:MeasureReactionTurn(npc, action)

	self:WhenReactionEnds(npc, function(why, waited)
		self:RebuildVictim(npc)
		self:ReplanVictim(npc)

		if self.Config.LogTelemetry then
			self:Log("VictimRebuild action=" .. action
					.. " on=" .. why
					.. " waited=" .. string.format("%.0f", waited) .. "ms")
		end
	end)

	self:Log("Reaction action=" .. action
			.. " gender=" .. gender
			.. " ok=" .. tostring(ok)
			.. " err=" .. tostring(err))

	return ok
end

--- Knocks a victim down with a physics ragdoll.
--
-- Used at trot and gallop. `actor:Fall` switches the victim to a ragdoll,
-- after which an impulse can be applied. Impulses are ignored on an upright,
-- animation-driven actor, so the order matters and the impulse is deferred
-- by a tick.
--
-- @tparam table npc victim entity
-- @tparam table velocity horse velocity vector
-- @tparam number speed horse speed in meters per second
-- @tparam number impulseScale multiplier on the configured impulse, 0 to 1
function HorseCollisionMod:Ragdoll(npc, velocity, speed, impulseScale)
	pcall(function()
		if npc.actor then
			npc.actor:Fall({x=0, y=0, z=0}, true)
		end
	end)

	local k_back = self.Config.Knockback * impulseScale
	local k_up = self.Config.Uplift * impulseScale

	if k_back <= 0 and k_up <= 0 then
		return
	end

	pcall(function()
		local hitPos = {x=0, y=0, z=0}
		local dir = {x=1, y=0, z=0}

		if npc.GetPos then
			hitPos = npc:GetPos()
		end

		-- Lift the application point to roughly chest height so the victim
		-- rotates over the impact instead of having their feet swept.
		hitPos.z = hitPos.z + 1.0

		-- Normalised against the velocity's own length, not against the
		-- scored speed. Those are different numbers: the score is the peak of
		-- the last few ticks, chosen so a collision is rated by the speed the
		-- horse carried into it, while the velocity here is what the horse is
		-- doing now, after the contact has slowed it.
		--
		-- Dividing one by the other leaves a direction shorter than unit and
		-- an impulse weakened by that ratio, so the same target took 67.3 at
		-- full speed and 37.7 when the horse had dropped to 2.84 against a
		-- score of 10.72. Knockback then varies with how hard the horse
		-- happened to brake rather than with the tier and the target.
		local moving = GetVectorLength(velocity or {x = 0, y = 0, z = 0})

		if moving > 0 then
			dir.x = velocity.x / moving
			dir.y = velocity.y / moving
			dir.z = 0
		end

		-- Forward push and upward lift are combined into one vector, then
		-- split back into a unit direction and a magnitude, because
		-- AddImpulse wants those as separate arguments.
		local combined = { x = dir.x * k_back, y = dir.y * k_back, z = k_up }
		local impulseMag = math.sqrt((combined.x * combined.x)
				+ (combined.y * combined.y)
				+ (combined.z * combined.z))

		-- Logged because the multiplier and the tier scalar are both visible
		-- in telemetry while the figure they produce was not, which left a
		-- report of armored targets moving further at trot than at gallop
		-- with nothing to check it against.
		if self.Config.LogTelemetry then
			self:Log("Impulse " .. tostring(npc:GetName())
					.. " scale=" .. string.format("%.2f", impulseScale)
					.. " magnitude=" .. string.format("%.1f", impulseMag))
		end

		if npc.AddImpulse and impulseMag > 0 then
			local normDir = {
				x = combined.x / impulseMag,
				y = combined.y / impulseMag,
				z = combined.z / impulseMag
			}

			-- The ragdoll needs a tick to physicalize before it accepts an
			-- impulse.
			Script.SetTimer(50, function()
				pcall(function()
					npc:AddImpulse(-1, hitPos, normDir, impulseMag, 1)
				end)
			end)
		end
	end)
end

--- Whether this collision should count as a combat one.
--
-- Two independent signals, because neither alone is reliable:
--
-- * `player.soul:IsInCombatDanger()` is what vanilla scripts use, but it
--   reflects immediate danger rather than "a fight is happening", and reads
--   false for long stretches of an ongoing fight. Mounted and moving, the
--   player may not be in danger at the instant of each impact.
-- * The victim having a weapon drawn. Townsfolk do not walk around armed, so
--   this catches the case the first signal misses: charging someone who is
--   actively fighting.
--
-- Both raw values are logged so a disagreement between them is visible
-- rather than being hidden behind a single boolean.
--
-- @tparam table npc victim entity
-- @treturn boolean true when combat rules should apply
-- @treturn string diagnostic describing both signals
function HorseCollisionMod:IsCombatCollision(npc)
	local danger = false
	local dangerOk = false
	local armed = false
	local armedOk = false

	dangerOk = pcall(function()
		if player.soul and player.soul.IsInCombatDanger then
			danger = player.soul:IsInCombatDanger()
		end
	end)

	armedOk = pcall(function()
		if npc.human and npc.human.IsWeaponDrawn then
			armed = npc.human:IsWeaponDrawn()
		end
	end)

	local detail = "danger=" .. tostring(danger) .. "/" .. tostring(dangerOk)
			.. " armed=" .. tostring(armed) .. "/" .. tostring(armedOk)

	return (danger == true or armed == true), detail
end

--- Throws the rider from the horse.
--
-- Prefers the horse's own `RearAndThrowDown`, which plays the animation of
-- the animal rearing and unseating its rider. Falls back to ragdolling the
-- player, which is what earlier builds did and which reads as the player
-- collapsing rather than being thrown.
--
-- `RearAndThrowDown` is undocumented. It sits on the horse entity's `horse`
-- extension, alongside `HasRider` and `IsMountable`.
--
-- @tparam table horseEnt the player's horse entity
-- @tparam table playerEnt the player entity
function HorseCollisionMod:ThrowRider(horseEnt, playerEnt)
	local thrown = false

	-- The method lives on the horse's own `horse` extension, found by
	-- enumerating what the entity actually carries. The other entries are
	-- kept as fallbacks in case a different mount type differs.
	local candidates = {
		{ name = "horse.horse", holder = horseEnt.horse },
		{ name = "horse", holder = horseEnt },
		{ name = "horse.actor", holder = horseEnt.actor }
	}

	for _, candidate in pairs(candidates) do
		if not thrown and candidate.holder
				and type(candidate.holder.RearAndThrowDown) == "function" then
			local ok = pcall(function()
				candidate.holder:RearAndThrowDown()
			end)

			self:Log("ThrowRider via " .. candidate.name .. " ok=" .. tostring(ok))

			if ok then
				thrown = true
			end
		end
	end

	if not thrown then
		self:Log("ThrowRider falling back to player ragdoll")

		pcall(function()
			playerEnt.actor:Fall({x=0, y=0, z=0}, true)
		end)
	end
end

--- Charges the horse for an impact and dismounts Henry when it is spent.
--
-- Stamina is written with `soul:SetState`, never `soul:DealDamage`. That
-- call takes `(stamina, health, attacker, ...)`  -  stamina first  -  even though
-- vanilla's own debug helper names the parameters health-first, so using it
-- here silently injures the horse instead.
--
-- @tparam table horseEnt the player's horse entity
-- @tparam table playerEnt the player entity
-- @tparam number staminaDrain points of stamina to remove
function HorseCollisionMod:DrainHorseStamina(horseEnt, playerEnt, staminaDrain)
	if not staminaDrain or staminaDrain <= 0 or not horseEnt or not playerEnt then
		return
	end

	pcall(function()
		if not horseEnt.soul then
			return
		end

		local before = horseEnt.soul:GetState("stamina")

		if not before then
			return
		end

		-- Clamped at zero rather than allowed to go negative, so that a
		-- single heavy impact cannot bank a deficit the horse then has to
		-- recover from before it can move again.
		local target = before - staminaDrain

		if target < 0 then
			target = 0
		end

		horseEnt.soul:SetState("stamina", target)

		self:Log("Horse stamina " .. string.format("%.1f", before)
				.. " -> " .. string.format("%.1f", target))

		if not self.Config.ThrowRiderOnStaminaEmpty then
			return
		end

		if target <= 0 and playerEnt.actor then
			self:Log("Horse spent - throwing rider.")
			self:ThrowRider(horseEnt, playerEnt)
		end
	end)
end

--- Applies the appropriate reaction for one collision.
--
-- Enforces the per-victim cooldown, then dispatches on gait.
--
-- @tparam table npc victim entity
-- @tparam table velocity horse velocity vector
-- @tparam number speed speed to score the impact at, in meters per second
-- @tparam table horseEnt the player's horse entity
-- @tparam table playerEnt the player entity
-- @tparam userdata horseWuid WUID of the horse
-- @tparam number sampledSpeed speed read on this tick, recorded in the log so
--   the correction for collision deceleration stays visible
function HorseCollisionMod:TriggerCollision(npc, velocity, speed, horseEnt, playerEnt,
		horseWuid, sampledSpeed)
	local npcId = tostring(npc.id)
	local now = GetTimeMs()

	-- The detection sphere is tested ten times a second, so without a
	-- per-victim cooldown a single pass through a crowd would restart the
	-- same NPC's reaction every tick and they would never finish staggering.
	--
	-- The wait runs until the victim can act again rather than for a fixed
	-- time after the last impact. Someone knocked down is still on the
	-- ground long after a stagger would have finished, and an impact landing
	-- while they are down plays no reaction, because every reaction is a
	-- standing animation, and usually costs them no health either.
	--
	-- Nothing in the engine reports whether an actor is on the ground. The
	-- entity's angles stay upright through a ragdoll and no ScriptBind
	-- exposes the state, so the recovery is timed rather than observed, and
	-- it is timed from the impulse the mod applied itself.
	local readyAt = self.RecentHits[npcId]

	-- A deadline further away than the longest cooldown that can be written
	-- was not written against this clock. `System.GetCurrTime` is persisted
	-- in the save, so loading an earlier one moves it backwards by however
	-- far the save was rewound, and every victim hit before that point is
	-- then locked out for the length of the rewind. Deadlines up to 239
	-- seconds ahead were read out of a running game against a configured
	-- maximum of 6.
	--
	-- Discarding the stamp rather than trusting it also covers entity ids
	-- being reused across a load, which otherwise locks out a victim that
	-- was never hit at all.
	if readyAt then
		local longest = math.max(self.Config.HitCooldownMs,
				self.Config.KnockdownRecoveryMs)

		if readyAt - now > longest then
			self.RecentHits[npcId] = nil
			readyAt = nil
		end
	end

	if readyAt and now < readyAt then
		-- Logged outside the miss diagnostic. It fires only when a victim
		-- is hit again while still down, which is a handful of lines rather
		-- than the thousands that diagnostic writes, and it is the only
		-- evidence that the wait is doing anything.
		if self.Config.LogTelemetry then
			self:Log("Recovering " .. tostring(npc:GetName())
					.. " for=" .. tostring(readyAt - now) .. "ms")
		end

		return
	end

	local tierName = self:GetSpeedTier(speed)
	local strength = self.HitReactionStrength
	local cfg = self.Config
	local combatScale = 1.0
	local isCombat, combatDetail = self:IsCombatCollision(npc)

	-- Only the knockdown tiers put anyone on the ground, so the walk tier
	-- keeps the shorter wait.
	local recovery = cfg.HitCooldownMs

	if tierName ~= "Walk" then
		recovery = cfg.KnockdownRecoveryMs
	end

	self.RecentHits[npcId] = now + recovery

	-- What actually prevents the lockup. A victim under 40 health carrying a
	-- bleeding buff is otherwise taken over by vanilla's auto-cure daycycle,
	-- which stands them in the street playing `PretendingIllness`.
	self:SuppressAutoCure(npc)

	-- Walked once per impact. Every use below wants the same totals, and
	-- enumerating an inventory per use would repeat the work three times.
	local armor = self:ArmorOf(npc)
	local armorImpulse = self:ArmorImpulseScale(armor)
	local armorStamina = self:ArmorStaminaScale(armor)

	if isCombat then
		combatScale = cfg.CombatStaminaMultiplier
	end

	self:Log("Impact tier=" .. tierName
			.. " speed=" .. string.format("%.2f", speed)
			.. " sampled=" .. string.format("%.2f", sampledSpeed or speed)
			.. (cfg.DiagnoseMisses
					and (" trail=[" .. self:SpeedTrail(self.SpeedHistorySize) .. "]")
					or "")
			.. " combatScale=" .. string.format("%.1f", combatScale)
			.. " armorImpulse=" .. string.format("%.2f", armorImpulse)
			.. " armorStamina=" .. string.format("%.2f", armorStamina)
			.. " " .. combatDetail)

	if tierName == "Walk" then
		local suppressed = cfg.SuppressStaggerInCombat and combatScale > 1.0

		if cfg.WalkStagger and not suppressed then
			self:PlayReaction(npc, velocity, speed, "hcm_stagger_")
		end

		self:ProbeImpactCost(npc, "Walk", strength.Tickle, armor)
		self:SendHitReaction(npc, horseWuid, strength.Tickle)
		self:DrainHorseStamina(horseEnt, playerEnt,
				cfg.StaminaDrainWalk * combatScale * armorStamina)
		return
	end

	if tierName == "Trot" then
		-- Sampled before the impulse, not after. Ragdoll can cost the
		-- victim health of its own, and a probe that reads afterwards
		-- folds that into the starting figure instead of the delta.
		self:ProbeImpactCost(npc, "Trot", strength.MinorInjury, armor)

		-- An animated knockdown never makes the victim a physics object, so
		-- the horse cannot strike them and the engine charges nothing. The
		-- ragdoll is kept because it is what shipped, and because an
		-- animation does not carry the impact's momentum.
		if cfg.TrotReaction == "knockdown" then
			self:PlayReaction(npc, velocity, speed, "hcm_knockdown_")
		else
			self:Ragdoll(npc, velocity, speed, 0.6 * armorImpulse)
		end
		self:SendHitReaction(npc, horseWuid, strength.MinorInjury)
		self:DrainHorseStamina(horseEnt, playerEnt,
				cfg.StaminaDrainTrot * combatScale * armorStamina)
		return
	end

	if tierName == "Gallop" then
		-- Sampled before the impulse, not after. Ragdoll can cost the
		-- victim health of its own, and a probe that reads afterwards
		-- folds that into the starting figure instead of the delta.
		self:ProbeImpactCost(npc, "Gallop", strength.MajorInjury, armor)
		self:Ragdoll(npc, velocity, speed, 1.0 * armorImpulse)
		self:SendHitReaction(npc, horseWuid, strength.MajorInjury)
		self:DrainHorseStamina(horseEnt, playerEnt,
				cfg.StaminaDrainGallop * combatScale * armorStamina)
		return
	end
end

--- One tick of collision detection.
--
-- Bails out early unless the player is mounted and moving at least at
-- walking pace, then tests every entity within `HitRadius` of the horse.
--
-- Every engine call is wrapped in `pcall`, because entities can be unstreamed
-- or partially initialized at any moment and an uncaught error would kill the
-- timer loop for the rest of the session.
function HorseCollisionMod:SafeUpdate()
	if type(player) == "nil"
			or (not player)
			or type(player.human) == "nil"
			or type(player.player) == "nil" then
		return
	end

	local isMounted = false

	pcall(function()
		isMounted = player.human:IsMounted()
	end)

	if not isMounted then
		return
	end

	local horseWuid = nil

	pcall(function()
		horseWuid = player.player:GetPlayerHorse()
	end)

	if not horseWuid then
		return
	end

	local horseEnt = nil

	pcall(function()
		horseEnt = XGenAIModule.GetEntityByWUID(horseWuid)
	end)

	if not horseEnt then
		return
	end

	local velocity = nil

	pcall(function()
		if horseEnt.GetVelocity then
			velocity = horseEnt:GetVelocity()
		end

		if not velocity and player.GetVelocity then
			velocity = player:GetVelocity()
		end
	end)

	local speed = GetVectorLength(velocity)
	self:TrackSpeed(speed)

	local impactSpeed = self:ImpactSpeed()

	-- Below walking pace nothing can happen, so the loop normally stops here
	-- before looking at a single entity. While diagnosing it keeps going, or
	-- an impact lost because the collision itself slowed the horse would leave
	-- no trace at all.
	if impactSpeed < self.Config.SpeedWalk and not self.Config.DiagnoseMisses then
		return
	end

	local horsePos = nil
	local horseForward = nil

	pcall(function()
		horsePos = horseEnt:GetPos()
	end)

	pcall(function()
		if horseEnt.GetDirectionVector then
			horseForward = horseEnt:GetDirectionVector(1)
		end
	end)

	if not horsePos or not horseForward then
		return
	end

	local hitEnts = nil

	pcall(function()
		hitEnts = System.GetEntitiesInSphere(horsePos, self.Config.HitRadius)
	end)

	if type(hitEnts) ~= "table" then
		return
	end

	for _, ent in pairs(hitEnts) do
		local isCandidate = (ent
				and type(ent) == "table"
				and ent.id
				and ent.id ~= player.id
				and ent.id ~= horseEnt.id)

		if isCandidate then
			local isMutt = false

			-- Henry's dog follows close enough to be caught constantly, and
			-- trampling him on every ride is nobody's idea of immersion. He
			-- is identified by entity name because dogs share the generic
			-- NPC class.
			pcall(function()
				local entName = ent:GetName()

				if entName and string.find(entName, "dogCompanion") then
					isMutt = true
				end
			end)

			local isProtected = (self.Config.ProtectMutt and isMutt)

			if not isProtected then
				local isHuman = false

				-- The sphere returns everything nearby: crates, doors, loose
				-- items, animals. Humans are named by class, and there are
				-- three: men spawn as NPC, women as NPC_Female, and the rider
				-- as Player. Naming them is what keeps this a human filter.
				--
				-- A faction fallback stood here and was wrong in both
				-- directions. Dogs carry `esFaction`, so a guard dog was
				-- given a human knockdown fragment on a dog skeleton, which
				-- is a fragment that cannot resolve. And women passed only
				-- through that fallback rather than by class, which is a
				-- fragile way to reach half the population and sits behind a
				-- long run of female-specific faults in this mod.
				pcall(function()
					isHuman = (ent.class == 'NPC'
							or ent.class == 'NPC_Female'
							or ent.class == 'Player')
				end)

				if not isHuman then
					self:LogRejection(ent, "not-human",
							"class=" .. tostring(ent.class))
				elseif not ent.actor then
					self:LogRejection(ent, "no-actor",
							"class=" .. tostring(ent.class))
				end

				if isHuman and ent.actor then
					local isDead = false

					-- Corpses are already ragdolls. Reacting to them would
					-- twitch bodies around and re-trigger every tick.
					if ent.IsDead then
						pcall(function()
							isDead = ent:IsDead()
						end)
					end

					local inFootprint = self:IsInHorseFootprint(ent, horsePos,
							horseForward, speed)

					if isDead then
						self:LogRejection(ent, "dead", "")
					elseif not inFootprint then
						self:LogRejection(ent, "outside-footprint",
								self:FootprintDetail(ent, horsePos, horseForward, speed))
					elseif impactSpeed < self.Config.SpeedWalk then
						self:LogRejection(ent, "below-walk-speed",
								"impact=" .. string.format("%.2f", impactSpeed)
								.. " sampled=" .. string.format("%.2f", speed))
					else
						self:TriggerCollision(ent, velocity, impactSpeed, horseEnt,
								player, horseWuid, speed)
					end
				end
			end
		end
	end
end

--- Reschedules itself every 100 ms and runs one detection tick.
--
-- The tick number guards against duplicate loops. Each load screen starts a
-- new loop, and any loop whose number no longer matches the current one stops
-- on its next iteration, so reloading a save leaves no stale timers running.
--
-- @tparam number assignedTick the loop generation this timer belongs to
function HorseCollisionMod:UpdateTimer(assignedTick)
	if self.TimerTick ~= assignedTick then
		return
	end

	-- The next tick is booked before any work is done. If detection ever
	-- throws in a way pcall cannot contain, the loop still survives; booking
	-- afterwards would end the mod for the rest of the session.
	Script.SetTimer(100, function()
		HorseCollisionMod:UpdateTimer(assignedTick)
	end)

	local success, err = pcall(function()
		self:SafeUpdate()
	end)

	if not success then
		self:Log("CRITICAL ERROR IN UPDATE TIMER: " .. tostring(err))
	end
end

--- Applies HorseCollisionMod_Settings.lua over the defaults above.
--
-- Settings live in their own file so that changing one does not mean finding a
-- table partway down a thousand-line script. That file ships alongside this one
-- in `Scripts/Startup/` and defines a single global.
--
-- Startup scripts are loaded in name order, so the settings file runs after
-- this one and its global does not exist at the time this file is executed.
-- The merge therefore happens from the load screen, by which point everything
-- in `Scripts/Startup/` has run.
--
-- A key that is not already in Config is rejected rather than added. Config is
-- the list of settings that exist, so an unknown key means a typo, and adding
-- it would be silently ignored by whatever was supposed to read it. A wrong
-- type is rejected for the same reason. Both are logged, because a setting that
-- quietly does nothing is worse than one that visibly fails.
--
-- @treturn number settings applied
-- @treturn number entries rejected
function HorseCollisionMod:ApplySettings()
	local settings = rawget(_G, "HorseCollisionModSettings")

	if type(settings) ~= "table" then
		return 0, 0
	end

	local applied = 0
	local rejected = 0

	for key, value in pairs(settings) do
		local current = self.Config[key]

		if current == nil then
			self:Log("Setting '" .. tostring(key) .. "' is not a setting, ignored")
			rejected = rejected + 1
		elseif type(value) ~= type(current) then
			self:Log("Setting '" .. tostring(key) .. "' wants a "
					.. type(current) .. ", got " .. type(value) .. ", ignored")
			rejected = rejected + 1
		elseif value ~= current then
			self.Config[key] = value
			applied = applied + 1
		end
	end

	return applied, rejected
end

-- Entity classes whose animation database this mod redirects.
--
-- Documented as an ordinary comment rather than an LDoc block, for the reason
-- given on ImpactProbeSamples above: LDoc reads an annotated table as a set of
-- named fields, and one that only maps class names to a character set carries
-- nothing a per-field line would add.
--
-- Each entry maps an entity class table to the character set it belongs to.
--
-- Both the exposed classes and the `_x` templates they came from are listed,
-- and the distinction is the whole reason this works. `NPC_x` is a template;
-- `NPC.lua` does `NPC = CreateAI(NPC_x)`, and `CreateAI` builds a fresh table
-- and *copies* the fields in. So the live class holds a snapshot of the stock
-- paths taken when its script loaded, and redirecting only the template
-- changes nothing about what spawns.
--
-- The player class is declared
-- directly rather than through CreateAI, so redirecting it did work, which
-- made the mod's own files load and hid the fault.
-- The parent database is a few hundred bytes and holds no
-- fragments of its own; it references the untouched vanilla database inside its
-- own pak, plus this mod's fragment file.
--
-- This is what makes the mod additive. The alternative, and what 2.0.0 shipped,
-- is overriding kcd_male_database.adb outright, which means any other mod
-- touching human animations either loses its changes to this one or takes this
-- one's away depending only on mod_order.txt. Mannequin databases cannot be
-- merged, so that conflict is total and silent in both directions.
--
HorseCollisionMod.AnimationDatabases = {
	-- The exposed classes. These are what the engine spawns, and what has to
	-- be redirected for any of this to take effect.
	NPC           = "male",
	NPC_NAI       = "male",
	NullAI        = "male",
	DummyTarget   = "male",
	Player        = "male",
	NPC_Female    = "female",
	PlayerFemale  = "female",

	-- The templates they were built from. Redirected too, so that anything
	-- calling CreateAI after this point inherits the right paths rather than
	-- the stock ones.
	NPC_x         = "male",
	NPC_NAI_x     = "male",
	NullAI_x      = "male",
	DummyTarget_x = "male",
	NPC_Female_x  = "female"
}
--- The parent database each character set uses.
--
-- Only `AnimDatabase3P` is redirected. `ActionController` deliberately is not:
-- leaving entities on vanilla's controller def means every fragment except
-- this mod's resolves through vanilla's own files, and the mod never appears
-- in the resolution path of animations it has nothing to do with.
--
-- Redirecting `ActionController` as well would let the stagger FragTags live
-- in a file named hcm_*, and it resolves correctly, but it puts a copied
-- fragment id file in the path of unrelated animations: the beggar's kneeling
-- resolves through BeggarIn and kcd_beggar_tags.xml by way of that same file,
-- and stops. The FragTags are declared in vanilla's own tag file instead,
-- which is 1 KB and costs no other animation its resolution path.
--
-- @table AnimationSets
HorseCollisionMod.AnimationSets = {
	male   = "Animations/Mannequin/ADB/hcm_male_database.adb",
	female = "Animations/Mannequin/ADB/hcm_female_database.adb"
}

--- Points the human entity classes at this mod's parent databases.
--
-- AnimDatabase3P is read when an actor spawns, so this has to happen before the
-- world is populated. A Startup script runs early enough, but the entity class
-- tables are loaded on demand and may not all exist yet, hence the retry from
-- the load screen for any that were missing.
--
-- Redirecting a class twice is harmless, and a class that never appears is
-- skipped rather than treated as an error, so this is safe to call repeatedly.
--
-- @treturn number how many classes were redirected by this call
-- @treturn number how many are still waiting for their class table to exist
function HorseCollisionMod:RedirectAnimationDatabases()
	local redirected = 0
	local pending = 0

	for class, set in pairs(self.AnimationDatabases) do
		local target = rawget(_G, class)
		local database = self.AnimationSets[set]

		if type(target) ~= "table" then
			pending = pending + 1
		elseif target.AnimDatabase3P ~= database then
			target.AnimDatabase3P = database
			redirected = redirected + 1
		end
	end

	return redirected, pending
end

--- UI event handler that serves as the mod's entry point.
--
-- A Startup script has no general "game loaded" hook available to it, so the
-- end of the loading screen stands in for one.
--
-- @tparam string actionName UI action that fired
-- @tparam string eventName phase of that action
-- @tparam table argTable event arguments, unused
function HorseCollisionMod:uiActionListener(actionName, eventName, argTable)
	if actionName == "sys_loadingimagescreen" and eventName == "OnEnd" then
		HorseCollisionModGeneration = HorseCollisionModGeneration + 1

		local currentTick = HorseCollisionModGeneration

		self.TimerTick = currentTick

		-- Cooldown deadlines are stamped against a clock the save restores,
		-- and the entity ids keying them are reused across a load. Neither
		-- survives the transition, so the table is dropped rather than
		-- carried into a world it no longer describes.
		self.RecentHits = {}

		local applied, rejected = self:ApplySettings()

		if applied > 0 or rejected > 0 then
			self:Log("Settings: " .. tostring(applied) .. " applied, "
					.. tostring(rejected) .. " ignored")
		end

		local again = self:RedirectAnimationDatabases()

		if again > 0 then
			self:Log("Redirected " .. tostring(again)
					.. " animation databases that loaded late")
		end

		self:Log("Load screen ended. v" .. self.Version
				.. " initializing physics timer loop "
				.. tostring(currentTick))

		Script.SetTimer(100, function()
			HorseCollisionMod:UpdateTimer(currentTick)
		end)
	end
end

-- Runs at file scope rather than from the load screen, because
-- AnimDatabase3P is read when an actor spawns and the load screen ends
-- after the world is already populated.
local hcmRedirected, hcmPending = HorseCollisionMod:RedirectAnimationDatabases()

HorseCollisionMod:Log("Redirected " .. tostring(hcmRedirected)
		.. " animation databases, " .. tostring(hcmPending) .. " pending")

if type(UIAction) == "table" and type(UIAction.RegisterActionListener) == "function" then
	UIAction.RegisterActionListener(HorseCollisionMod, "", "", "uiActionListener")
end
