--- Horse Collision Overhaul for Kingdom Come: Deliverance.
--
-- Gives mounted collisions a reaction proportional to the horse's gait. In
-- vanilla, riding into an NPC produces only an audio bark and no animation at
-- any speed. This module adds three tiers:
--
-- * **Walk** - the NPC plays a full standing stagger animation and is not
--   knocked down. No health damage, and the vanilla bark still fires.
-- * **Trot** - a physics ragdoll at reduced impulse.
-- * **Gallop** - a physics ragdoll at full impulse.
--
-- At trot and gallop the horse also loses stamina, and dismounts Henry when
-- spent. That is the anti-bulldozing budget: riding through a crowd has to
-- end with Henry on the ground rather than being a free way to scatter a
-- dozen people.
--
-- ## How the walk stagger works
--
-- Lua cannot drive an NPC's animation directly, and every obvious approach
-- fails silently: `human:PlayAnim` is accepted but never
-- renders, physics impulses are ignored because actors are animation-driven,
-- `soul:DealDamage` only moves stat numbers, and the `hitReaction` and
-- `combat:hit` brain messages reach a behavior tree that cannot drive the
-- body.
--
-- What does play a clip is `actor:StartInteractiveActionByName`, the call
-- vanilla uses to make an actor mime opening a door. It takes over the body,
-- plays a whole animation, and hands control back. Its name argument resolves
-- against the FragTags of exactly one Mannequin fragment,
-- `AnimationControlled`, where vanilla ships only object interactions.
--
-- It is not the only actor call that matters. An interactive action is
-- root-motion driven, so the animation moves the body and nothing constrains
-- where it ends up, which is why a reaction played beside a building could
-- carry its victim into the wall. `actor:SetMovementControlledByAnimation`
-- turns that off per victim, and is called a tick after the action starts;
-- see `ReleaseActorMovement` for why the order is not negotiable.
--
-- So the mod adds its own entries there, without replacing anything. Seven
-- data files ship alongside this script, all generated by `build_adb.py`,
-- and every one is named `hcm_*` so it cannot collide with another mod:
--
-- * `hcm_<set>_database.adb` - the parent, and the authoritative definition
--   of `AnimationControlled`. It carries vanilla's own 30 options plus this
--   mod's 4, and references the untouched vanilla database as a SubADB for
--   every other fragment. Carrying vanilla's options is not optional: a
--   sub-database does not merge into a fragment another one defines, so
--   without them a redirected NPC loses every door and cabinet interaction.
-- * `hcm_<set>_fragmentids.xml` - points `AnimationControlled` at the tag
--   file below. For women it also has to declare that fragment at all,
--   since they have the same clips but no such fragment in vanilla.
-- * `hcm_<set>_controllerdefs.xml` - points its `Fragments` element at the
--   file above. This is what an entity resolves names through at runtime,
--   and redirecting the database alone is not enough.
-- * `hcm_animationControlledTags.xml` - declares those FragTags. An option
--   whose tag is not declared aborts after one frame.
-- See `docs/HOW_IT_WORKS.md` for why this indirection is worth the trouble.
--
-- ## Limitations
--
-- * Dogs and other animals do not react. They use separate animation
--   databases which this mod does not touch.
-- * Two mods redirecting `AnimDatabase3P` on the same entity class conflict.
--   The contested value is a Lua string, so a cooperative mod can chain by
--   referencing whatever is already set.
--
-- @module HorseCollisionMod
-- @author jrandall54
-- @release 5.24.0
HorseCollisionMod = {}

HorseCollisionMod.Version = "5.24.0"

--- Loop generation counter, deliberately kept outside the table above.
--
-- `lua_reload_script` re-executes this file, and its first act is to rebuild
-- HorseCollisionMod from scratch, which takes TimerTick with it. A counter
-- stored on the table therefore restarts at 1 on every reload, while any loop
-- still running from before compares its own generation against that same 1,
-- matches, and carries on. Each reload would leave another loop sweeping for
-- collisions ten times a second, all of them writing to the same cooldown
-- table.
--
-- The `or 0` is what makes this survive a reload: the global is already set by
-- then, so the count continues instead of restarting, and every stale loop
-- sees a generation that no longer matches and stops on its next tick.
HorseCollisionModGeneration = HorseCollisionModGeneration or 0

--- Tuning values. Safe to edit in place; nothing here is derived at runtime.
--
-- Grouped by what they affect, and deliberately kept terse: this is the table
-- people open to change a setting, not to read. The reasoning behind the
-- defaults is in docs/TECHNICAL_DETAILS.md under "Reaction defaults".
--
-- @field SpeedWalk lower bound of the walk tier, in meters per second
-- @field SpeedTrot lower bound of the trot tier
-- @field SpeedGallop lower bound of the gallop tier
-- @field HitRadius radius of the broad-phase sphere around the horse
-- @field HorseFrontReach how far ahead of the horse origin counts as a hit
-- @field HorseRearReach how far behind the horse origin counts as a hit
-- @field HorseHalfWidth lateral half-width of the horse footprint
-- @field HorseMaxVerticalDiff height difference above which a hit is ignored
-- @field TickSeconds detection interval, used to sweep the footprint forward
-- @field SweepMultiplier how far ahead to sweep, per meter per second
-- @field MaxSweepExtra cap on the forward sweep, in meters
-- @field HitMinIntervalMs the least time between two scored impacts on one
--   victim, so a single pass through someone is one impact and not five
-- @field ImpactSpeedSamples ticks of speed history a collision is scored from
-- @field HorseAirborneVz the upward speed, in meters per second, at which
--   the mod reports that the horse has left the ground. Nothing is written
--   at rest, and nothing is sampled that the detection loop was not already
--   reading
-- @field MaxImpactSpeed ceiling on the speed a collision is scored at
-- @field Knockback horizontal ragdoll impulse at full strength
-- @field Uplift vertical ragdoll impulse at full strength
-- @field RagdollMass what the horse collides with, in kilograms, divided by
--   the armor scale so armor is felt as weight rather than as a force
-- @field RagdollMassArmorScaled whether RagdollMass is divided by the armor
--   scale; false gives every victim the same mass, which is how the direction
--   of the effect is read
-- @field RagdollMassArmorExponent how sharply armor is felt as weight. The
--   base cancels out of the ratio between an armored victim's mass and an
--   unarmored one, so only this widens the gap between them
-- @field ArmorReferenceWeight armor weight that scales a target by exactly one
-- @field ArmorImpulseExponent how sharply armor weight reduces the impulse
-- @field MinArmorImpulse floor on the armor impulse multiplier
-- @field MaxArmorImpulse ceiling on the armor impulse multiplier, reached by
--   an unarmored target
-- @field ArmorStaminaExponent how sharply armor weight raises the stamina cost
-- @field MinArmorStamina floor on the armor stamina multiplier
-- @field MaxArmorStamina ceiling on the armor stamina multiplier
-- @field DynamicRecovery scale ragdoll recovery get-up delay based on tier and armor
-- @field RecoveryDelayByTier base get-up stillness delay by impact tier
-- @field RecoveryArmorScaleArmored recovery delay multiplier for armored targets
-- @field RecoveryArmorScaleUnarmored recovery delay multiplier for unarmored targets
-- @field RecoveryMinSec minimum bound on recovery stillness duration
-- @field RecoveryMaxSec maximum bound on recovery stillness duration
-- @field RecoveryGroundBarks emit periodic pain barks while downed on the ground
-- @field RecoveryBarkIntervalMs interval between ground hurt barks in milliseconds
-- @field RagdollStillDuration seconds of stillness before a ragdoll stands up
-- @field RagdollStillSpeedThreshold speed threshold under which a ragdoll is still
-- @field ProtectMutt when true, Henry's dog is never a valid victim
-- @field ProtectStoryCharacters when true, characters the game marks as
--   protected take no damage from an impact
-- @field StaminaDrainByTier what each kind of impact costs the horse, before
--   the rider's Horsemanship, the horse's barding and the combat penalty
-- @field ThrowRiderOnStaminaEmpty dismount Henry when the horse is spent
-- @field CombatStaminaMultiplier stamina cost multiplier while in a fight
-- @field SuppressStaggerInCombat skip the stagger animation during a fight
-- @field Barks whether the mod gives its moments spoken vanilla lines at all
-- @field CollisionBarks whether victims of an impact speak
-- @field RearBarks whether whoever a rear is aimed at speaks
-- @field RiderBarks whether Henry remarks over a body
-- @field BarkCooldownMs least time between two lines from one speaker; keep at
--   or below HitCooldownMs or whole impacts fall silent
-- @field BarkSuppressMs how long vanilla's own collision bark is held off
-- @field BarkOnRecovery whether a knocked-down victim speaks again once up
-- @field BarkGapMs least silence between a victim's cry and their recovery line
-- @field BarkInCombat whether a victim already fighting still speaks, which
--   vanilla refuses
-- @field BarkPriority the request's rank in the dialog system's auction; a
--   line below the top that cannot be delayed is silently discarded
-- @field BarkCanBeDelayed whether a line that loses the auction is queued
--   rather than dropped
-- @field BarkOverrideSuppress whether the line ignores a `suppressMonologs`
--   context, which otherwise silences everything rather than just this
-- @field ShieldVictimFromEngineDamage whether a victim the horse strikes is
--   made briefly immortal so the engine's trample cannot land the killing
--   blow, which the game would charge to the player as murder
-- @field ShieldWindowMs crash backstop only, in milliseconds: the shield is
--   lifted when the victim's body lands, and this bounds the case where that
--   never happens
-- @field SendHitReaction post the native brain message so barks still fire
-- @field WalkStagger whether the walk tier plays a stagger animation
-- @field SuppressAutoCureSec how often the auto-cure exemption is rechecked,
--   in seconds, or 0 to leave victims in the daycycle
-- @field AutoCureHealthLimit health at or above which the auto-cure exemption
--   is dropped, matching vanilla's own limit
-- @field CollisionIsCrime whether riding someone down is reported to the
--   game as a crime, at trot and gallop
-- @field Rear whether the mod's own key rears the horse at a standstill
-- @field RearActionMap the name of that action map
-- @field RearActionMapFile where the mod ships it, loaded with
--   `ActionMapManager.LoadFromXML` so no vanilla input file is overridden
-- @field RearIdleOnly rear only from the horse's idle state, not while it moves
-- @field RearMaxSpeed the speed above which a rear request is ignored, in
--   meters per second, since a rear is a standstill move
-- @field RearCooldownMs how long before another rear is accepted
-- @field RearChargeKey which key rears and charges. One of r, q, y, u, o, h,
--   the keys the mod's action map declares
-- @field RearOnlyKey which key rears on the spot, from the same list
-- @field RearOnlyFragTag the FragTag that rears on the spot
-- @field RearChargeStrikes whether the charge knocks down who it reaches. It
--   carries its own detection rather than using the mod's collision loop,
--   so who is hit does not depend on the physics behaving
-- @field RearChargeStrikeReach how far ahead the charge reaches, in meters
-- @field RearChargeStrikeWidth how wide, either side of the horse
-- @field RearChargeStrikeBehind how far behind the horse still counts
-- @field RearChargeStrikeMs how long the strike sweeps for
-- @field RearChargeStrikePollMs how often it sweeps
-- @field RearChargeImpactSpeed the speed a charge is scored at
-- @field ImpactDustEffectRear the particle to spawn for a rear impact
-- @field RearChargeImpulse the physical push that carries the charge, applied
--   once the rear animation has ended so the horse collides normally
-- @field RearChargeLift how much of that push is upward
-- @field RearChargeWaitMs when the mod starts watching for the rear to end
-- @field RearChargeWaitPollMs how often it looks
-- @field RearChargeWaitCeilingMs push anyway by this point
-- @field RearChargeLungePeakMin the top speed a lunge must reach before it can
--   be judged spent, so noise in the derived speed cannot close the window
--   before the horse has gone anywhere
-- @field RearChargeLungeSpentAt the fraction of its own peak speed the horse
--   must fall to for the lunge to count as finished
-- @field RearChargeWindowMs how long after a charge starts that impacts are
--   scored as a gallop rather than by the horse's speed
-- @field RearFragTag the FragTag of the rear option in the mod's horse
--   animation database
-- @field RearAnimSpeed how fast the rear plays
-- @field RearStrikes whether the hooves coming down hit anyone in front
-- @field RearStrikeMs when in the animation the hooves land
-- @field RearReach how far in front the hooves reach, in meters
-- @field Lean whether the rider can lean out to see past the horse's head
-- @field LeanLeftKey which key leans left, one of r, q, e, f, y, u, o, h
-- @field LeanRightKey which key leans right, from the same list
-- @field LeanDistance how far across the horse the camera holds, in meters
--   from the horse's centerline rather than from where the camera rests, so
--   both sides finish the same distance from the head. The camera sits about
--   6 cm to the horse's left at rest, so the travel differs slightly between
--   the two sides while the finishing position does not
-- @field LeanForwardShare how much of the lean also carries the camera
--   forward, as a fraction of the sideways travel. 0 leans straight out
-- @field LeanTravelAmplitude how hard the camera is driven on the way out,
--   which sets how fast it gets there
-- @field LeanHoldAmplitude the amplitude used once the target is reached.
--   Lower is a steadier hold, because the residual wobble is the travel speed
--   times the poll interval
-- @field LeanPollMs how often the held offset is checked and corrected
-- @field LeanMaxAngleDeg how far off the horse's line the rider may be
--   looking and still lean, in degrees. Past it the camera travels through the
--   rider and the horse rather than out beside them, because the offset is
--   applied in camera space. Turning past it mid lean ends the lean. 0 removes
--   the limit

-- @field LeanDeadband how far off target the camera may sit before a
--   correction is spent on it, in meters. Wider is fewer corrections, and a
--   correction costs an animation queue entry for LeanShakeSec
-- @field LeanShakePeriod the period passed to SetViewShake. A shake's curve
--   peaks at its period and then reverses by itself, so this is kept long
--   enough that a hold never reaches that turn, and the amplitudes are scaled
--   with it because the travel speed is roughly amplitude over period
-- @field LeanShakeSec how long each shake lives. **Every shake is an entry in
--   the rider's animation queue and the queue holds sixteen**, so a long life
--   is paid for long after the lean that made it ended. An overflowed queue
--   rejects further animations rather than merely warning
-- @field LeanMinFlipMs the least time between two corrections, which bounds
--   how fast queue entries can be spent. It applies to corrections only: the
--   press, the arrival at the target and the release are never throttled,
--   because dropping any of those leaves the camera traveling
-- @field LeanMaxPitchDeg how far up or down the rider may be looking and
--   still lean, in degrees. The yaw limit is flattened so looking up or down
--   is not treated as looking away, which stops meaning anything once the
--   horizontal component collapses. Looking down is also where the camera is
--   nearest the rider's own model
-- @field LeanTurnLeadMs how far ahead of the angle limit a turn is judged, in
--   milliseconds. Ending a lean takes about 160 ms, so reacting at the limit
--   is too late for a fast turn and the camera clips through the rider. The
--   angle is projected forward at the current turn rate instead, which
--   tightens the limit only for the turns that need it
-- @field LeanSuppressShake whether an impact's camera shake is held back
--   while the rider is leaning. Both are SetViewShake, and a second call
--   reverses the camera rather than adding to it, so a shake mid lean sends
--   the camera home at the moment the rider leaned out to watch
-- @field LeanHomeMs how long after a release before another lean may start,
--   which is the time the camera needs to come home. Without it a re-press
--   takes its bearings from a camera that is still displaced
-- @field LeanRunawayFactor how far past the target the camera may get, as a
--   multiple of LeanDistance, before the lean is ended outright
-- @field LeanReleaseSec the short shake fired on release, which expires and
--   lets the camera return home

-- @field RearArc the arc in front that counts, in degrees
-- @field RearFear whether a rear frightens the people it does not hit
-- @field RearFearReach how far a near miss reaches, in meters, all round
-- @field RearFearScreamPriority the rank the scream is submitted at
-- @field RearImpactSpeed the speed a rear is scored at, since the horse's
--   own speed is zero and what matters is the hooves
-- @field ReleaseMovementAttempts how many times that release is repeated, in
--   case the fragment re-applies its movement layer as it blends
-- @field ReleaseMovementGapMs how far apart those attempts are
-- @field ReleaseAnimationMovement take movement control off the animation once
--   a reaction has started, so victims are not carried into walls
-- @field ReplanAfterReaction ask a victim to re-plan their activity once the
--   reaction is over, so they approach and re-align to whatever they were using
-- @field LogTelemetry write diagnostics to kcd.log
-- @field TraceRecovery time each animation state during a recovery
-- @field ImpulseDelayMs how long to wait before the ragdoll impulse
-- @field LateralImpulse how much of the impulse pushes across the
--   horse's line rather than along it
-- @field RagdollBrake whether a thrown body is braked at all. The engine's
--   own collision decides the launch and is never interfered with; the brake
--   is one counter-impulse along the body's own velocity and can only ever
--   subtract
-- @field RagdollBrakeKeepArmored the fraction of its speed a victim in full
--   mail keeps, the low end of the bracket
-- @field RagdollBrakeKeepUnarmored the fraction an unarmored victim keeps,
--   the high end. 1.0 is untouched, and is only reached by a victim whose
--   armor scale reaches `RagdollBrakeArmorScaleUnarmored` exactly
-- @field RagdollBrakeArmorScaleArmored the armor scale treated as fully
--   armored, the low end of the range
-- @field RagdollBrakeArmorScaleUnarmored the armor scale treated as
--   unarmored. An endpoint set above the highest scale that actually occurs
--   silently converts "leave them alone" into "slow everyone"
-- @field RagdollSpeedCapArmorScaled whether the speed ceiling a traveling
--   body is held to is scaled by the victim's armor. This is the lever that
--   separates an armored victim from an unarmored one, because distance
--   tracks how long a body spends above the ceiling
-- @field RagdollSpeedCapArmored the ceiling for a victim in full mail
-- @field RagdollSpeedCapUnarmored the ceiling for an unarmored victim
-- @field RagdollAirDampingArmorScaled whether the drag applied to a
--   traveling body is scaled by the victim's armor. The ceiling only decides
--   when the drag starts, and past the ceiling plus the span it saturates, so
--   without this every victim receives the same drag on the fast throws,
--   which are the ones where armor should tell them apart
-- @field RagdollAirDampingArmored the drag for a victim in full mail
-- @field RagdollAirDampingUnarmored the drag for an unarmored victim
-- @field RagdollDamping how fast a thrown body sheds speed, 0 for the
--   engine's own value
-- @field RagdollMinEnergy the energy below which a body is put to rest,
-- @field RagdollDampPollMs how often a thrown body is looked at, milliseconds
-- @field RagdollDampSettleSpeed the speed it must fall under before the
--   damping is applied, meters per second
-- @field SettleFragTag the empty fragment played to take a victim out of a
--   ragdoll without imposing a pose or a facing on them
-- @field RagdollDampRampSamples over how many samples the damping reaches its
--   full value once the body is down, so a fast landing decelerates rather
--   than being braked
-- @field RagdollSpeedSoftCap the speed past which a traveling body is
--   dragged down whether it is touching anything or not, in meters per
--   second. Read off the per-throw speed traces: a long throw runs 8 to 9
--   for its first three or four samples and a short one never passes 3.9,
--   so 4 separates them and nothing ordinary is touched
-- @field RagdollSpeedSoftCapSpan how far above the cap the drag reaches full
--   strength, so it comes in progressively rather than as a wall
-- @field RagdollAirDamping the damping applied at full strength in the air,
--   against RagdollDamping on the ground
-- @field RagdollDampContactRun how many samples in a row must report contact
--   before a thrown body is damped, so a bounce does not count as landing
-- @field RagdollDampFloorMs the earliest the damping may be applied, so it
--   cannot fire while the body is still being launched
-- @field RagdollDampCeilingMs the latest, applied regardless of speed
--   0 for the engine's own value
-- @field DiagnoseMisses name the reason a nearby NPC produced no reaction
-- @field Retaliation whether a victim shoved repeatedly at a walk can lose
--   patience and fight back
-- @field RetaliationFreeBumps how many walk impacts a victim tolerates before
--   any chance of a fight begins
-- @field RetaliationChanceStep how much each further shove adds to the chance
-- @field RetaliationMaxChance ceiling on that chance
-- @field RetaliationMemorySec how long a victim remembers being shoved, in
--   seconds, before the count decays to nothing
-- @field RetaliationCeilingSec failsafe, in seconds, after which a watched
--   incident is closed however it looks
-- @field SurrenderHintYieldsToGame do not raise the mod's surrender prompt
--   for a victim the game will prompt for itself, which is a guard, since
--   an arrest carries vanilla's own prompt
-- @field SurrenderHintCalmPasses quiet passes before the prompt gives up. A
--   fallback now that the prompt tracks who it is for: enough to cover the
--   danger reading blinking out mid-fight, not a wait for the fight to end
-- @field SurrenderHintHoldMs how often to put the surrender prompt back, since
--   the HUD drops it when the action map changes
-- @field ProvokeDuringCombat whether a new victim can be provoked while the
--   rider is already in a fight, which turns bystanders into attackers
-- @field RetaliationSurrenderHint whether the on-screen surrender prompt is
--   shown while a provoked victim is fighting
-- @field RetaliationPullsRiderDown whether a provoked victim drags the rider
--   out of the saddle before fighting, rather than punching the horse
-- @field PullDownPollMs how often to look for the chance to do it
-- @field PullDownForce ask for the pull-down even when the game reports the
--   victim cannot perform it; some NPCs are never eligible and this does not
--   change that, it exists for future investigation
-- @field PullDownRepeatMs how often to ask again once it has been requested,
--   since a single request is queued behind whatever the brain is doing
-- @field PullDownCeilingMs how long to keep looking before giving up
-- @field WomenRaiseAlarm whether a woman shoved once too often runs to fetch
--   a guard, where a man turns and fights
-- @field ImpactDamage whether the mod charges the victim for the impact on
--   top of what the engine charges for the collision
-- @field ImpactDamageArmorScale the `smash_def` past the ignored figure at
--   which a victim takes half the tier's damage; higher means armor matters less
-- @field ImpactDamageIgnoredArmor `smash_def` that does not count as armor,
--   covering the shoes and shirt every villager wears
-- @field ImpactSoundByTier the layer list each tier plays on impact
-- @field RiderVocalByTier Henry's own grunt for each tier
-- @field RiderVocalRankByTier each tier's rank in the shared voice gate
-- @field CameraShakeByTier how hard each tier kicks the camera
-- @field RiderBlurByTier how much each tier blurs the rider's view
-- @field RiderBlurLengthByTier how long each tier's blur lasts
-- @field ImpactDustScaleByTier how much dust each tier raises
-- @field VictimDirtByTier the dirt each tier leaves on the victim
-- @field VictimBloodByTier the blood each tier leaves on the victim
-- @field HitStrengthByTier how hard the engine is told each tier hit, by
--   HitReactionStrength name
-- @field VictimBarkByTier which spoken set a victim answers each tier with
-- @field RetaliationByTier which tiers can make a victim fight back
-- @field StaminaPerVictimByTier which tiers charge the horse once per victim
-- @field VictimLockMsByTier how long a victim is closed to further impacts,
--   for tiers that are one deliberate move rather than a series of collisions
-- @field VictimFlatFraction how low a victim's head must be, against their own
--   standing height, to count as flat on the ground
-- @field ReactionByTier what each tier does to the victim's body: "stagger",
--   "knockdown", "fall" or "ragdoll"
-- @field ThrowByTier how hard each ragdoll tier throws, as a scalar
-- @field ImpactDamageByTier what each kind of collision is worth before armor
-- @field ImpactDamageOwnsTheHit give back what the engine charged for a
--   collision, so the mod's figure is the whole cost rather than an addition
--   to an unknown one
-- @field ImpactDamageReclaimCeiling the most that can be given back for one
--   impact, so an unrelated injury in the delay window is not healed
-- @field ImpactDamageArmorCurve how sharply armor bites; 1 is the plain
--   hyperbola, above 1 bites sooner, below 1 flattens
-- @field ImpactDamageArmorFloor the least armor can reduce an impact to, since
--   no plate makes a man weigh less than the horse standing on him
-- @field ImpactDamageVariance how far either side of the tier figure a single
--   impact can land, as a fraction
-- @field ImpactDamageDelayMs how long to wait before charging the victim, so
--   that the engine's own trample damage lands first and this mod delivers
--   the killing blow; 0 charges immediately, which lets the engine decide
--   whether a collision death is attributed to the rider
-- @field ImpactDust whether an impact throws dust off the ground
-- @field ImpactDustEffect the particle library node to spawn
-- @field ImpactDustHeight meters above the victim's origin to spawn it
-- @field ImpactDustSampleMs how often the victim's velocity is sampled
-- @field ImpactDustFallVz vertical velocity below which they are falling
-- @field ImpactDustLandVz vertical velocity above which they have landed
-- @field ImpactDustFallWaitSamples samples to wait for a fall to start
-- @field ImpactDustMaxSamples samples after which the dust is spawned anyway
-- @field RiderBlur whether a gallop blurs the rider's view in first person
-- @field RiderBlurAmount how heavy the blur starts
-- @field RiderBlurHoldMs how long it is held at full before decaying
-- @field RiderBlurChroma chromatic shift layered on the same envelope
-- @field RiderBlurMs how long it takes to decay to nothing
-- @field RiderBlurSteps how many writes the decay is made of
-- @field RiderBlurFirstPersonOnly skip it when the camera is not on the player
-- @field RiderBlurFirstPersonRange camera distance that still counts as first
--   person, in meters
-- @field CameraShake whether a gallop impact kicks the rider's camera
-- @field CameraShakeAngle degrees of angular shake, on all three axes
-- @field CameraShakeShift meters of positional shake, on all three axes
-- @field CameraShakeDurationSec how long the shake lasts
-- @field CameraShakeFrequency oscillations per second
-- @field CameraShakeRandomness how much each shake varies from the last
-- @field Horsemanship whether the rider's horse_riding skill counts
-- @field HorsemanshipSkill the skill name read for it
-- @field HorsemanshipMaxLevel the level the figures below are worth at
-- @field HorsemanshipStaminaWorst the stamina cost multiplier at level 0
-- @field HorsemanshipStaminaBest the multiplier at HorsemanshipMaxLevel
-- @field HorsemanshipSeatChance chance of keeping the saddle at the top
-- @field Barding whether the horse's own barding changes what a collision does
-- @field BardingFullSmashDef the total `smash_def` counted as a full set
-- @field BardingStaminaRelief how much less stamina an impact costs at a full set
-- @field BardingDamageBonus how much harder a fully barded horse hits
-- @field BardingForceSteps rows of `{ coverage, knockback added, uplift added }`,
--   the flat force a barded horse adds, in five steps from bare to a full set
-- @field HorseBoltsWhenSpent whether a spent horse may leave after throwing
-- @field HorseBoltChance how often it does
-- @field HorseBoltRestoreMs how long until its health is given back
-- @field ImpactSound whether a collision makes a noise
-- @field ImpactSoundDistance meters added to every layer, the master level
-- @field ImpactSoundCrack the occasional bone crack layer
-- @field ImpactSoundCrackChance how often a gallop adds it
-- @field RiderVocal whether Henry grunts as the collision goes through him
-- @field RiderVocalCooldownMs how long the rider stays quiet after grunting
-- @field HorseVocal whether the horse vocalizes on impact
-- @field HorseVocalCooldownMs how long the horse stays quiet after vocalizing
-- @field HorseVocalByTier per-tier horse vocal, same format as RiderVocalByTier
-- @field HorseVocalRankByTier severity ordering for the horse voice gate
-- @field RiderBark whether Henry says something about the impact
-- @field RiderBarkChance how often an impact produces a line instead of a grunt
-- @field RiderBarkCooldownMs how long Henry stays quiet after speaking
-- @field RiderBarkKill whether a kill gets its own line from the kill pool
-- @field RiderBarkPriority the priority Henry's own line is sent at
-- @field VictimMarks whether a collision leaves dirt and blood on the victim
-- @field RequirePerks whether maneuvers are gated by Horsemanship perks
-- @field AutoGrantPerks whether to automatically grant the maneuvers' perks
-- @field ShowTutorials whether to display on-screen maneuver tutorials
-- @table Config
HorseCollisionMod.Config = {
	-- Speed tiers, in meters per second. Below SpeedWalk nothing happens.
	SpeedWalk                = 1.8,
	SpeedTrot                = 4.5,
	SpeedGallop              = 8.5,

	-- Maneuver gating.
	RequirePerks             = true,
	AutoGrantPerks           = false,
	ShowTutorials            = true,

	-- Detection. HitRadius is a broad-phase sphere; everything inside it is
	-- then tested against the horse footprint, in meters from the horse
	-- origin. The sweep extends the footprint forward by one tick of travel.
	HitRadius                = 2.5,
	HorseFrontReach          = 1.05,
	HorseRearReach           = 0.20,
	HorseHalfWidth           = 0.70,
	HorseMaxVerticalDiff     = 2.35,
	-- The detection interval, and the only figure the loop rate and the
	-- forward sweep are both taken from. It was 0.1 while the timer itself was
	-- hardcoded to 100 ms, which agreed by accident rather than by design.
	--
	-- A tenth of a second is a long time to wait for the noise of being hit by
	-- a horse. The impact sound made that audible, and the rider heard it
	-- arrive after the visual and the physical feedback at every speed.
	TickSeconds              = 0.033,
	SweepMultiplier          = 0.50,
	MaxSweepExtra            = 0.35,
	HitMinIntervalMs         = 700,

	-- A collision is scored on the peak of the last ImpactSpeedSamples ticks,
	-- not on the speed read when the victim is noticed. MaxImpactSpeed is the
	-- ceiling on that value, a little above the top of the gallop plateau.
	-- Nine ticks rather than three, because the tick is a third as long. The
	-- window a collision is scored over is what matters, and it is unchanged.
	HorseAirborneVz          = 2.5,
	ImpactSpeedSamples       = 9,
	MaxImpactSpeed           = 11.0,

	-- Knockdown impulse. Trot and gallop only; the walk tier never ragdolls.
	Knockback                = 50.0,
	Uplift                   = 30.0,

	-- What the horse is hitting, in kilograms, divided by the armor scale so
	-- a man in mail is the heavier thing to move. Every human is 80 to the
	-- physics engine, which is why armor has never been felt in a throw.
	-- 0 leaves the engine's own figure alone.
	RagdollMass              = 80.0,
	RagdollMassArmorScaled   = false,

	-- How hard armor is felt as weight. The mass written is the base over the
	-- armor scale raised to this, so the ratio between an armored victim and
	-- an unarmored one is the scale ratio raised to it as well. The base
	-- cancels out of that ratio entirely, which is why 40 and 80 both left
	-- armored and unarmored victims traveling the same distance: both
	-- present the horse with the same 3.4x spread. Above 1 widens the spread;
	-- 1 is the plain division and 0 removes the scaling.
	RagdollMassArmorExponent = 3.7,

	-- What the target is wearing, as a multiplier on the impulse and on the
	-- horse's stamina cost. Both are 1.0 at ArmorReferenceWeight; an
	-- exponent of 0 switches that half off.
	ArmorReferenceWeight     = 8.0,
	ArmorImpulseExponent     = 0.5,
	MinArmorImpulse          = 0.35,
	MaxArmorImpulse          = 1.5,
	ArmorStaminaExponent     = 0.4,
	MinArmorStamina          = 0.75,
	MaxArmorStamina          = 3.0,

	-- Horse stamina, against a full pool of roughly 210.
	StaminaDrainByTier       = {
		Walk = 0.0, Trot = 14.0, Gallop = 22.0, Rear = 12.0, Charge = 22.0
	},

	ThrowRiderOnStaminaEmpty = true,

	-- How long a victim is exempted from vanilla's auto-cure daycycle,
	-- in seconds. Zero leaves them in it.
	SuppressAutoCureSec      = 30,

	-- What a trot impact does.
	--
	-- "knockdown" plays an animated fall and an animated get-up through the
	-- same path as the walk stagger, and creates no physics body, so it
	-- cannot incur the trample damage a ragdoll does.
	--
	-- "fall" plays the same fall and stops there, handing the body to a
	-- ragdoll once the clip ends so the game recovers the victim the way it
	-- recovers any fallen actor. The trample the mod moved away from is not a
	-- risk here, because the ragdoll is created several seconds after the
	-- impact rather than underneath the horse that caused it.
	--
	-- "ragdoll" is the physics knockdown the mod shipped before, created at
	-- the moment of impact.

	-- Whether riding someone down is a crime.
	--
	-- Sent at trot and gallop, where the collision hurts them, and never at a
	-- walk: a stagger costs no health and being arrested for brushing past
	-- someone is not the intent. The game charges it as a brawl, which is what
	-- vanilla does with a ridden collision too, and prosecutes murder on its
	-- own when a victim dies.
	CollisionIsCrime         = true,

	-- Takes movement control off the animation once a reaction has started,
	-- so the victim is moved by the entity rather than by root motion and
	-- stops being carried through walls. False restores the behavior before
	-- this, where a stagger beside a building could end inside it.
	ReleaseAnimationMovement = true,
	ReleaseMovementAttempts  = 4,
	ReleaseMovementGapMs     = 80,

	-- Sends a victim back to their activity once their reaction is over, so
	-- they walk to whatever they were using and are aligned to it on the way
	-- in rather than resuming it from wherever they fell.
	ReplanAfterReaction      = true,

	-- The health at or above which a victim is no longer a candidate for
	-- vanilla's auto-cure daycycle. Vanilla's own limit is 40, declared as
	-- `t_autoCureLowHealthLimit` in `Libs/AI/final/sb_daycycles.xml`. The
	-- exemption is held until the victim is back over this.
	AutoCureHealthLimit      = 40.0,

	-- Combat.
	CombatStaminaMultiplier  = 2.2,
	SuppressStaggerInCombat  = true,

	-- Spoken reactions. Every line is vanilla, spoken by the character's own
	-- voice actor and selected by naming a metarole, so no new audio ships.
	-- `Bark.lua` carries the sets and the reasoning behind each one.
	--
	-- The pillars have separate switches on purpose: the collision reactions
	-- and the rear are independent mechanics, and neither may carry the
	-- other's setting. `Barks` is the master over both.
	Barks                    = true,
	CollisionBarks           = true,
	RearBarks                = true,
	RiderBarks               = true,
	-- Per speaker, so a crowd reacting to one impact is not a choir, and a
	-- victim struck twice does not talk over their own first line.
	--
	-- **Keep this at or below `HitCooldownMs`.** It was 6000 against a hit
	-- cooldown of 3000, which meant every second impact the mod acted on was
	-- silent, exactly and arithmetically: the log showed two `Impact` lines
	-- per `Bark` line for a whole ride. The rider read that as barks randomly
	-- failing to fire. A victim cannot be struck again until the hit cooldown
	-- expires, so that cooldown is already the guard against talking over
	-- themselves and a longer one here only deletes reactions.
	BarkCooldownMs           = 3000,
	-- How long vanilla's own collision bark is held off, which is the window
	-- HushVanillaBark opens ahead of contact so the mod's line is not talked over.
	BarkSuppressMs           = 2500,
	-- Whether a victim knocked down at trot or gallop says something once
	-- they are back on their feet. The cry of pain at the moment of impact is
	-- wordless, so without this they stand up and walk off having never
	-- remarked on being ridden down.
	BarkOnRecovery           = true,
	-- How long after the impact the victim's recovery line is spoken, timed so
	-- it lands *during* the get-up rather than after it. Tuned by ear: a
	-- state-driven trigger fires only once the get-up has finished, which
	-- leaves an audible hole between standing and speaking.
	-- The least silence between two lines from the same speaker. A victim who
	-- recovers quickly is upright while their own cry of pain is still
	-- playing, and speaking again then cuts the first line off mid-word.
	BarkGapMs                = 2500,
	-- Whether a victim already fighting the player still complains about being
	-- ridden into. Vanilla refuses this outright and so does the mod; the
	-- setting exists so the behavior can be compared rather than assumed.
	BarkInCombat             = false,
	-- Make a victim briefly immortal across the moment of contact, so the
	-- engine's own collision damage lands on nothing and the mod is the only
	-- thing that charges them. Research setting.
	ShieldVictimFromEngineDamage = false,
	-- A backstop, not a mechanism. The shield goes on only where an impact is
	-- scored and `ApplyImpactDamage` lifts it synchronously, so this should
	-- A crash backstop, in milliseconds, and nothing else. The shield is lifted
	-- by the mod's own damage call, which the victim's ragdoll resolving fires,
	-- so reaching this means that call never happened.
	ShieldWindowMs           = 6000,
	-- The rest of the `dialog:monologRequest` message. The dispatch tree sorts
	-- every in-flight request by priority and silently discards one that is
	-- below the top and cannot be delayed, so a bark sent at the default zero
	-- loses to anything else the speaker is saying.
	BarkPriority             = 0,
	BarkCanBeDelayed         = false,
	-- Exempts the line from a `suppressMonologs` context, which is the gate
	-- that silences everything rather than just the collision bark.
	BarkOverrideSuppress     = false,

	-- Retaliation. Barging the same person at a walk costs nobody anything,
	-- which makes it an annoyance rather than an act. These let a victim
	-- run out of patience: each shove is counted, and once the count passes
	-- `RetaliationFreeBumps` every further one rolls against a chance that
	-- grows with the count, up to `RetaliationMaxChance`.
	--
	-- A provoked fight is deliberately not a crime. The hit that starts it
	-- carries the engine's own `real = false`, which drives the victim's
	-- decision without reaching the reputation system, so no fine is levied
	-- and no guard is summoned. Guards who witness the brawl still join in,
	-- because they witnessed it.
	-- Rearing on command. Everything else this mod does needs speed; a rear is
	-- what a rider has at a standstill.
	Rear                     = true,
	RearChargeKey            = "r",
	RearActionMap            = "hcm_rear",
	RearActionMapFile        = "Libs/Config/hcm_actionmaps.xml",
	RearIdleOnly             = true,
	RearMaxSpeed             = 0.15,
	RearCooldownMs           = 2500,
	RearFragTag              = "hcm_rear_charge",
	RearOnlyKey              = "f",
	RearOnlyFragTag          = "hcm_rear",
	-- Hooves coming down, not a horse riding into someone. Lighter than a
	-- charge and led by the hoof rather than by the body.
	RearChargeStrikes        = true,
	RearChargeStrikeReach    = 1.8,
	RearChargeStrikeWidth    = 0.9,
	RearChargeStrikeBehind   = 0.2,
	RearChargeStrikeMs       = 1600,
	RearChargeStrikePollMs   = 50,
	RearChargeImpactSpeed    = 7.5,
	RearChargeImpulse        = 6000,
	RearChargeLift           = 0.2,
	RearChargeWaitMs         = 400,
	RearChargeWaitPollMs     = 30,
	RearChargeWaitCeilingMs  = 3000,
	RearChargeLungePeakMin   = 3.0,
	RearChargeLungeSpentAt   = 0.5,
	RearChargeWindowMs       = 2600,
	RearAnimSpeed            = 1.0,
	RearStrikes              = true,
	RearStrikeMs             = 700,
	Lean                     = true,
	LeanLeftKey              = "q",
	LeanRightKey             = "e",
	LeanDistance             = 0.65,
	LeanForwardShare         = 0.35,
	LeanTravelAmplitude      = 110.0,
	LeanHoldAmplitude        = 3.0,
	LeanPollMs               = 30,
	LeanDeadband             = 0.06,
	LeanMinFlipMs            = 200,
	LeanRunawayFactor        = 2.0,
	LeanMaxAngleDeg          = 45,
	LeanMaxPitchDeg          = 55,
	LeanSuppressShake        = true,
	LeanTurnLeadMs           = 200,
	LeanHomeMs               = 220,
	LeanShakePeriod          = 40.0,
	LeanShakeSec             = 1.5,
	LeanReleaseSec           = 0.05,
	RearReach                = 2.5,
	RearArc                  = 70,
	RearFear                 = true,
	RearFearReach            = 3.5,
	RearFearScreamPriority   = 50,
	RearImpactSpeed          = 6.0,

	Retaliation              = true,
	RetaliationFreeBumps     = 1,
	RetaliationChanceStep    = 0.25,
	RetaliationMaxChance     = 0.85,
	RetaliationMemorySec     = 45,
	RetaliationCeilingSec    = 120,
	RetaliationPullsRiderDown = true,
	RetaliationSurrenderHint = true,
	ProvokeDuringCombat      = false,
	SurrenderHintHoldMs      = 1000,
	SurrenderHintYieldsToGame = true,
	SurrenderHintCalmPasses  = 3,
	PullDownPollMs           = 250,
	PullDownForce            = false,
	PullDownRepeatMs         = 1500,
	PullDownCeilingMs        = 8000,
	WomenRaiseAlarm          = true,

	-- What being ridden down costs the victim, over and above what the
	-- engine charges for the collision itself.
	ImpactDamage             = true,
	-- What a collision is worth, before armor. The three settings below this
	-- are the whole damage model and are meant to be read together: this table
	-- says what the blow is, the armor pair says how much of it survives what
	-- the victim is wearing, and the floor says how little armor can refuse.
	ImpactSoundByTier        = {
		Walk   = { { "f_n_mat_foleyal_cl", 0 },
		           { "hs_hp_soil", 4 },
		           { "f_n_mat_foleyal_cl", 5 },
		           { "f_n_mat_foleyam_cl", 8 },
		           { "f_bodyfall1", 12 },
		           { "f_n_mat_foleyam_cl", 13 },
		           { "f_bodyfall1", 18 } },
		Trot   = { { "body", 0, 1.3 },
		           { "body", 0, 1.65 },
		           { "f_bodyfall1", 0, 1.5 } },
		Gallop = { { "body", 0, 0.5 },
		           { "n_lu_log_ground", 0, 1.0 },
		           { "body_armed", 0, 0.85 },
		           { "blunt", 0, 1.0 },
		           { "face_armed", 0, 0.9 },
		           { "f_bodyfall1", 0, 0.7 } },
		Rear   = { { "a_o_jump_landing", 0, 0, 0.6 },
		           { "hs_hp_soil", 2, 0.6 },
		           { "body", 0, 1.6 },
		           { "blunt", 0, 2.0 },
		           { "f_bodyfall1", 0, 1.3 } },
		Charge = { { "body", 0, 0.6 },
		           { "hs_hp_soil", 3, 0.8 },
		           { "body_armed", 0, 0.9 },
		           { "blunt", 0, 1.0 },
		           { "hs_hp_soil", 6, 0.7 },
		           { "face_armed", 0, 0.9 },
		           { "f_bodyfall1", 0, 0.7 } },
	},

	HorseVocalByTier         = {
		Walk   = { "a_o_horse_excited1", 0, 0, 1 },
		Trot   = { "a_o_horse_excited1", 0, 0, 1 },
		Gallop = { "a_o_horse_whinny1",  0, 0, 1 },
		Rear   = { "", 0, 0, 1 },
		Charge = { "", 0, 0, 1 },
	},

	HorseVocalRankByTier     = {
		Walk = 1, Trot = 2, Gallop = 3, Rear = 2, Charge = 3,
	},

	RiderVocalByTier         = {
		Walk   = { "v_henry_hit_soft", 140, 0, 1 },
		Trot   = { "v_henry_hit_medium", 110, 0, 1 },
		Gallop = { "v_henry_hit_heavy", 90, 0, 1 },
		Rear   = { "v_henry_hit_medium", 110, 0, 1 },
		Charge = { "v_henry_hit_heavy", 90, 0, 1 },
	},

	RiderVocalRankByTier     = {
		Walk = 1, Trot = 2, Gallop = 3, Rear = 2, Charge = 3
	},

	CameraShakeByTier        = {
		Trot = 0.6, Gallop = 1.0, Rear = 0.8, Charge = 1.2
	},

	RiderBlurByTier          = {
		Trot = 0.7, Gallop = 1.0, Rear = 0.6, Charge = 1.1
	},

	RiderBlurLengthByTier    = {
		Trot = 0.3, Gallop = 1.0, Rear = 0.4, Charge = 1.1
	},

	ImpactDustScaleByTier    = {
		Trot = 0, Gallop = 0.09, Rear = 0.6, Charge = 0.10
	},

	VictimDirtByTier         = {
		Trot = 0.35, Gallop = 0.60, Rear = 0.35, Charge = 0.60
	},

	VictimBloodByTier        = {
		Trot = 0.15, Gallop = 0.45, Rear = 0.15, Charge = 0.45
	},

	HitStrengthByTier        = {
		Walk = "Tickle", Trot = "MinorInjury", Gallop = "MajorInjury",
		Rear = "MinorInjury", Charge = "MajorInjury"
	},

	VictimBarkByTier         = {
		Walk = "collision", Trot = "collision", Gallop = "collision",
		Rear = "rear", Charge = "rear"
	},

	RetaliationByTier        = {
		Walk = true, Trot = false, Gallop = false, Rear = false, Charge = false
	},

	StaminaPerVictimByTier   = {
		Walk = true, Trot = true, Gallop = true, Rear = false, Charge = false
	},

	VictimLockMsByTier       = { Charge = 2600 },

	VictimFlatFraction       = 0.15,

	ReactionByTier           = {
		Walk = "stagger", Trot = "fall", Gallop = "ragdoll",
		Rear = "fall", Charge = "ragdoll"
	},

	ThrowByTier              = { Gallop = 1.0, Charge = 0.7 },

	ImpactDamageByTier       = {
		Walk = 0, Trot = 18, Gallop = 95, Rear = 60, Charge = 110
	},

	ImpactDamageOwnsTheHit   = true,
	ImpactDamageReclaimCeiling = 60,

	ImpactDamageArmorScale   = 0.6,
	ImpactDamageArmorCurve   = 1.0,
	ImpactDamageArmorFloor   = 0.0,
	ImpactDamageIgnoredArmor = 0.5,
	ImpactDamageVariance     = 0.15,
	ImpactDamageDelayMs      = 600,

	-- The rider's own half of a gallop impact. A collision costs stamina and
	-- costs the victim health, and in hardcore mode neither is visible from
	-- the saddle, so a kick to the camera is the only part of it the player
	-- feels. Gallop only: a trot knockdown should stay a shove.
	--
	-- Angle is degrees of rotation and shift is meters of displacement, both
	-- applied on all three axes. Frequency is the period vanilla's own shakes
	-- pass, which is a small number: `SinglePlayer:ViewShake` uses 1/20 and
	-- the CameraShake entity defaults to 0.5. Randomness varies each shake so
	-- repeated collisions do not feel canned.
	CameraShake              = true,
	CameraShakeAngle         = 4.0,
	CameraShakeShift         = 0.08,
	CameraShakeDurationSec   = 0.5,
	CameraShakeFrequency     = 0.05,
	CameraShakeRandomness    = 0.5,

	-- What a gallop impact does to the rider's own view in first person. The
	-- dust the collision throws up is on the ground below the field of view at
	-- speed, so a first person rider sees none of it; this is their share.
	--
	-- A blur pulse, because the engine has no dust or dirt lens overlay and
	-- this is the same cue the game uses for taking a hit. Amount is how heavy
	-- the blur starts, and it decays to nothing over RiderBlurMs.
	--
	-- Off in third person by default, where the real effect is already
	-- visible. The views are told apart by how far the camera sits from the
	-- player, which is under a meter in first person and several in third.
	RiderBlur                = true,
	RiderBlurAmount          = 1.0,
	RiderBlurHoldMs          = 260,
	RiderBlurChroma          = 0.2,
	RiderBlurMs              = 480,
	RiderBlurSteps           = 7,
	RiderBlurFirstPersonOnly = true,
	RiderBlurFirstPersonRange = 1.5,

	-- What the rider's own Horsemanship is worth. The game's `horse_riding`
	-- skill runs 0 to 20; a rider at 0 is unaffected and the figures below are
	-- what the skill is worth at the top of that scale.
	--
	-- The stamina cost is multiplied, not discounted, and the range is wide on
	-- purpose. At level 0 a single gallop impact very nearly empties the
	-- horse; at 20 it takes four or five armored guards, or about nine
	-- villagers. The ceiling is set against guards rather than villagers
	-- because guards are what the figure was judged on, and it stays low
	-- enough that a rider never becomes a cartoon. It runs linearly between
	-- the two, so every level is worth the same.
	--
	-- Seat is the chance of staying mounted when the horse is finally spent.
	-- The horse still stops either way; a rider who can ride does not always
	-- come off with it.
	Horsemanship             = true,
	HorsemanshipSkill        = "horse_riding",
	HorsemanshipMaxLevel     = 20,
	HorsemanshipStaminaWorst = 10.0,  -- the cost multiplier at level 0
	HorsemanshipStaminaBest  = 1.2,   -- and at HorsemanshipMaxLevel
	HorsemanshipSeatChance   = 0.6,   -- chance of keeping the saddle, at the top

	-- What the horse's own barding is worth. Barding is the horse's armor and
	-- is separate from its tack, read from the total `smash_def` of what it is
	-- wearing. Three flat effects rather than one multiplier, each scaling from
	-- nothing on a bare horse to its figure here on a full set. Nothing about
	-- the rider enters this: barding does not scale with Horsemanship.
	Barding                  = true,
	BardingFullSmashDef      = 1.45,
	BardingStaminaRelief     = 0.25,
	BardingDamageBonus       = 0.15,
	BardingForceSteps        = {
		{ 0.0, 0.0, 0.0 },
		{ 0.2, 1.0, 0.6 },
		{ 0.4, 2.0, 1.2 },
		{ 0.6, 3.0, 1.8 },
		{ 0.8, 4.0, 2.4 },
		{ 1.0, 5.0, 3.0 }
	},

	-- What happens to the horse after it dumps a rider who rode it into people
	-- until it was spent. Sometimes it wants nothing more to do with them and
	-- leaves, using its own AI: its combat subbrain flees wherever, so it only
	-- has to be given something to flee from.
	--
	-- A chance rather than a certainty. A horse that always bolts is a
	-- punishment; one that sometimes bolts is a horse.
	HorseBoltsWhenSpent      = true,
	HorseBoltChance          = 0.4,
	HorseBoltRestoreMs       = 3000,  -- health is given back this long after

	-- The noise a collision makes, played on the victim at the moment of
	-- impact. The names are audio triggers from the game's own .animevents
	-- vocabulary; a name outside it resolves to nothing. An empty string
	-- silences one tier without touching the others.
	ImpactSound              = true,

	-- Each tier is a list of { trigger, delay in milliseconds }. The trigger
	-- name "body" is replaced with the blunt impact matching what the victim
	-- is wearing: cloth, mail or plate.
	-- A third entry is a distance in meters, and it is the volume control:
	-- the layer is pushed that far back along the line from the listener, so
	-- it arrives from the same direction and quieter. Higher is quieter, and
	-- it does nothing to `a_o_jump_landing`, which is a 2D event whose level
	-- is fixed.
	--
	-- Walk names the cloth impact outright rather than using the `body` token.
	-- A shove at walking pace should not ring somebody's mail, which the token
	-- would do for an armored victim.
	-- A layer is { trigger, delay in ms, distance in meters, chance }.
	--
	-- Distance is the volume control. There is no gain anywhere in this
	-- engine's audio, so a layer is quietened by being played from further
	-- away: the offset is added along the line from the listener to the
	-- victim, so it arrives from the same direction and only its level drops.
	-- Because a victim is always a meter or two away at the moment of impact,
	-- the number behaves as a volume knob rather than as a position.
	--
	-- It does nothing to a 2D event. `a_o_jump_landing` and
	-- `c_special_bone_crack1` both ignore position entirely, so the only
	-- control over those is `chance`, which is how often the layer appears.
	--
	-- Two trigger names are tokens, replaced with the sample matching what the
	-- victim is wearing: `body` is the blunt impact against that material and
	-- `foley` is the movement rustle it makes.

	-- A shove disturbs someone's clothing rather than striking them, so the
	-- walk tier is cloth foley over a body settling, with a single hoofstep
	-- underneath for the horse. Quiet by being pushed back five meters.
	-- A layer is { trigger, delay in milliseconds, distance in meters, chance }.
	--
	-- Distance is the volume control, because the engine has no gain: a layer
	-- is quietened by being played from further away, offset along the line
	-- from the listener to the victim so it arrives from the same direction.
	-- A victim is always a meter or two away at impact, so the number behaves
	-- as a volume knob rather than as a position. The curve is steep and short:
	-- for the blunt impacts the usable range is about a meter, and past
	-- roughly 1.5 the sound is gone entirely, so the fine adjustments are
	-- fractional and are made to one copy of a layer rather than to all of it.
	--
	-- Distance does nothing to a 2D event. `a_o_jump_landing` and
	-- `c_special_bone_crack1` ignore position completely, which is why neither
	-- is used here.
	--
	-- Loudness otherwise comes from repetition. Naming a sample twice a few
	-- milliseconds apart thickens and lifts it, which is the only way up once
	-- a layer is already at zero distance.
	--
	-- Two trigger names are tokens, replaced with the sample matching what the
	-- victim is wearing: `body` is the blunt impact against that material and
	-- `foley` is the movement rustle it makes.

	-- The master level control, in meters, added to every layer of every
	-- tier. Higher is quieter. The per-layer distances set the balance
	-- between the layers; this sets how loud that balance is as a whole.
	--
	-- The listener follows the camera, so first person hears the mix from on
	-- top of the victim and a third-person camera hears the same mix from
	-- several meters back. Tuned in first person, the loudest case.
	ImpactSoundDistance      = 2.0,

	-- A shove disturbs someone's clothing rather than striking them, so the
	-- walk tier carries no impact at all: two cloth foleys and a body
	-- settling, each doubled because those samples are very quiet, over a
	-- single hoofstep.

	-- A trot puts someone on the ground, so the blunt impact leads, doubled
	-- with the second copy taken back a fraction to shade it down.

	-- A gallop stacks four different blunt impacts rather than repeats of one,
	-- so it reads as a collision instead of a flam, with the body settling
	-- underneath. Every impact layer is a token, so a mailed guard and a
	-- peasant in cloth sound different on all four.
	--
	-- No hoofstep. `hs_hp_soil` is `hoofsteps_player`, the same family as
	-- `a_o_jump_landing`, and those events ignore position: it played at a
	-- fixed full level under every other layer with no way down.

	-- The occasional injury, gallop only. A foley event, so unlike
	-- `c_special_bone_crack1` it can be quietened; that one is 2D and came out
	-- at cartoon volume whatever was done to it.
	ImpactSoundCrack         = { "f_bodyfall_leg_break", 20, 6 },
	ImpactSoundCrackChance   = 0.12,

	-- Henry's own grunt, one authored severity per tier. `Sound.lua` documents
	-- why these are FMOD events rather than barks: the mod names the exact
	-- event, so the dialog system cannot answer a request for a grunt with a
	-- monolog, which is what made every earlier attempt at Henry's half
	-- unusable.
	--
	-- Read as an impact layer: `{ trigger, delayMs, distance, chance }`. A
	-- trigger of `""` silences that tier alone.
	RiderVocal               = true,

	-- How long the rider stays quiet after grunting. Riding into a group lands
	-- several collisions inside a second and one grunt each reads as broken
	-- audio rather than as a man being jolted. A harder impact is still let
	-- through, so a gallop is never silenced by the walk shove before it.
	RiderVocalCooldownMs     = 1500,

	-- Whether the horse vocalizes on impact. The trigger is played on the
	-- horse entity, not the victim; horse audio triggers carry engine-level
	-- `path="horse"` metadata and must not be fired on a human proxy.
	HorseVocal               = true,

	-- How long the horse stays quiet after vocalizing. Mirrors the rider
	-- cooldown so a crowd of collisions does not produce a chorus.
	HorseVocalCooldownMs     = 1500,

	-- Henry saying something about the impact, rather than only grunting. The
	-- lines are vanilla's, addressed by `alias` so the mod names one topic
	-- instead of a whole bark set; `Bark.lua` carries the list and why these
	-- ones. Every impact draws from the same pool regardless of tier.
	--
	-- Words and breath share one gate, because both come out of Henry and two
	-- at once is a defect. So the chance below is how often an impact produces a
	-- line *instead of* a grunt, and a line holds the grunt off for its own
	-- cooldown, which is longer because a line takes longer to say.
	RiderBark                = false,
	RiderBarkChance          = 0.35,
	RiderBarkCooldownMs      = 5000,
	RiderBarkKill            = true,

	-- Henry's own line gets its own priority rather than sharing the victims'.
	-- Requests register in a shared array which the dialog system sorts
	-- descending, and a request below the top is discarded with no error, so at
	-- the default of zero a line loses every contest it enters. Both aliases
	-- that were confirmed audible in testing were sent at 50, so that is the
	-- shipped value: it makes the tested configuration the default one.
	RiderBarkPriority        = 50,

	-- How long a victim is left alone after being hit. The knockdown tiers
	-- read the victim's own state rather than counting: a fall, the ragdoll
	-- that follows it and the get-up run about seven seconds together, and a
	-- second impact inside that plays no reaction and usually costs no health.
	--
	-- The victim is busy while an animation the mod started or a ragdoll owns
	-- their body, and hittable again once HitReadySettleMs has passed with
	-- neither. Any busy state restarts that window, because a trot victim is
	-- briefly idle between the fall clip ending and the ragdoll taking over.
	-- HitReadyCeilingMs releases a victim who is never seen busy at all.
	--
	-- Setting HitCooldownStateDriven false goes back to counting, on
	-- HitCooldownMs and KnockdownRecoveryMs alone.
	-- Which tiers wait for a victim to be ready. Only the ones that play an
	-- animation need to: a knockdown clip starts from standing and has nothing
	-- to blend from on a victim already flat, while a ragdoll has no pose to
	-- start from and can land at any point in a recovery.


	-- The dust a body throws up where it lands. Nothing at a walk, where
	-- nobody falls. Scale is the size of the effect, so a gallop kicks up
	-- more than a trot; 0 switches a tier off.
	--
	-- The effect name is a particle library node, from the game's own
	-- Libs/Particles. `collisions.destructibles.arrow_soil` is the soil an
	-- arrow kicks out of the ground and is the closest thing the game has to
	-- a body landing on dirt. `WH_Particels.other.gravel` and
	-- `WH_Particels.dust.sweep` are the alternatives worth trying.
	ImpactDust               = true,
	ImpactDustEffect         = "WH_Particels.other.explosion_dust",
	ImpactDustEffectRear     = "collisions.destructibles.arrow_soil",
	ImpactDustHeight         = 0.05,
	ImpactDustSampleMs       = 50,
	ImpactDustFallVz         = -0.5,
	ImpactDustLandVz         = -0.15,
	ImpactDustFallWaitSamples = 8,
	ImpactDustMaxSamples     = 30,

	-- The dirt and blood a collision leaves on the victim, applied at trot
	-- and gallop only. Deltas in the range 0 to 1, accumulating across
	-- impacts. Dirt covers everything the victim is wearing; blood is
	-- applied to the body zones on the side the blow landed on. Zero
	-- switches either half off without touching the other.
	VictimMarks              = true,

	-- Switches.
	ProtectMutt              = true,
	ProtectStoryCharacters   = true,
	WalkStagger              = true,
	SendHitReaction          = true,
	LogTelemetry             = true,

	-- Names the reason a nearby NPC produced no reaction. Every test in the
	-- detection loop rejects silently, so a missed impact and an impact that
	-- never happened look identical. Off by default: it is noisy and only
	-- useful while investigating.
	DiagnoseMisses           = false,


	-- How long after the action ends before the displacement is read back.


	-- Times every animation state a recovering victim passes through and
	-- logs the sequence. Answers where a recovery spends its seconds, which
	-- a single duration cannot. Off by default: one line per impact and a
	-- poll running for the length of each recovery.
	TraceRecovery            = false,

	-- How long to wait after the ragdoll before applying the impulse, in
	-- milliseconds.
	--
	-- An impulse applied to a body that has not physicalized yet is
	-- ignored silently, and the same magnitude has been measured throwing
	-- one victim four meters and another none at all, which is the
	-- signature of a window missed rather than of a force too small.
	ImpulseDelayMs           = 50,

	-- How much of the impulse pushes a victim sideways, against the
	-- horse's line of travel. 0 is straight along it, 1 is as much across
	-- as along.
	--
	-- A body thrown along the horse's line does not clear it. At a gallop
	-- the horse travels near ten meters a second and the impulse moves a
	-- 120 kilogram body at a fraction of that, so the horse overtakes its
	-- own victim and tramples them a second time. Pushing them across the
	-- line clears it regardless of how hard they are thrown.
	--
	-- The side is whichever one the victim is already on, so a glancing
	-- contact carries them further the way they were already going.
	LateralImpulse           = 0.0,

	-- How quickly a ragdolled victim sheds speed, and how readily it comes
	-- to rest. Both 0 leave the engine's own values alone.
	--
	-- A thrown body slides, and a slide is most of the distance an impact
	-- appears to produce. That makes distance a poor reading of force and
	-- it makes the ground feel like ice. `damping` bleeds velocity off the
	-- body and `min_energy` is the threshold below which physics puts it to
	-- rest, both fields of `pe_simulation_params`, reached through
	-- `entity:SetPhysicParams(PHYSICPARAM_SIMULATION, ...)`.
	-- What fraction of its speed a thrown body is allowed to keep, and the
	-- armor scales the two ends of that bracket belong to.
	--
	-- The brake is a single counter-impulse along the body's own velocity,
	-- fired once shortly after the ragdoll is thrown. Braking a body to a
	-- fraction of its speed is proportional rather than absolute, so the
	-- engine's own variation between one contact and the next passes through
	-- intact and what is controlled is how much is taken away.
	RagdollBrake             = true,
	RagdollBrakeKeepArmored  = 0.45,
	RagdollBrakeKeepUnarmored = 1.0,
	RagdollBrakeArmorScaleArmored = 0.35,
	RagdollBrakeArmorScaleUnarmored = 1.26,
	RagdollDamping           = 5.0,
	RagdollMinEnergy         = 1.0,
	RagdollDampPollMs        = 100,
	RagdollDampSettleSpeed   = 0.5,
	SettleFragTag            = "hcm_settle",
	RagdollSpeedCapArmorScaled = true,
	RagdollSpeedCapArmored   = 2.5,
	RagdollSpeedCapUnarmored = 6.0,
	RagdollSpeedSoftCap      = 4.0,
	RagdollSpeedSoftCapSpan  = 3.0,
	RagdollAirDampingArmorScaled = true,
	RagdollAirDampingArmored = 20.0,
	RagdollAirDampingUnarmored = 4.0,
	RagdollAirDamping        = 8.0,
	RagdollDampContactRun    = 3,
	RagdollDampRampSamples   = 8,
	RagdollDampFloorMs       = 200,
	RagdollDampCeilingMs     = 6000,

	-- Dynamic Ragdoll Recovery
	DynamicRecovery           = true,
	RecoveryDelayByTier       = {
		Trot   = 0.5,
		Gallop = 2.0,
		Rear   = 1.0,
		Charge = 3.5,
	},
	RecoveryArmorScaleArmored   = 0.6,
	RecoveryArmorScaleUnarmored = 1.5,
	RecoveryMinSec            = 0.3,
	RecoveryMaxSec            = 5.0,
	RecoveryGroundBarks       = true,
	RecoveryBarkIntervalMs    = 1400,

	-- Native Engine Ragdoll Stillness
	RagdollStillDuration        = 0.8,
	RagdollStillSpeedThreshold  = 0.4,
}



--- When each victim was last scored, by entity id.
--
-- Whether the horse has already been charged for the contact it is still
-- passing through, read by `ImpactIsNewContact`. It debounces one pass into
-- one impact and says nothing about the victim's recovery, which is
-- `IsVictimFlat` and is read from the body rather than from a clock.
--
-- @table LastScoredHit
HorseCollisionMod.LastScoredHit = {}

--- Victims closed to further impacts until a stated time.
--
-- Separate from `LastScoredHit`, which is a rolling interval between ordinary
-- collisions. This is a deliberate lockout: a charge strikes once and the
-- victim is not available again for the length of the move.
--
-- @table LockedUntil
HorseCollisionMod.LockedUntil = {}

--- Entities the development tooling created, which take no impact damage.
--
-- Populated only by `tools/dev_subject.lua`. Nothing in normal play writes to
-- it, and it is not a setting, so a shipped build can never have anything in
-- it. It exists because an NPC cannot be made unkillable through the engine.
--
-- @table ImmortalSubjects
HorseCollisionMod.ImmortalSubjects = {}

--- What each victim was doing when it was hit, keyed by entity id.
--
-- Read back once the victim is on their feet, to tell one that has resumed
-- its activity from one left standing with nothing to do. A beggar and an
-- innkeeper cannot recover their own loop and need the replan; almost
-- everyone else recovers on their own and is only interrupted by it.
--
-- Cleared with the rest of the per-victim state on a load screen.
HorseCollisionMod.VictimActivity = {}

--- How high each victim carries their head standing, by entity id.
--
-- Recorded at the first impact that reaches them, when they are by definition
-- upright, and read by `IsVictimFlat` to tell a body lying on the ground from
-- one that has begun to get up. Measured rather than configured: no threshold
-- in this mod decides it.
HorseCollisionMod.StandingHead = {}




--- How often each victim has been shoved at a walk, keyed by entity id.
--
-- Each entry holds the running count and the time of the last shove, so a
-- victim barged three times in a minute is treated differently from one
-- barged three times across an afternoon. `RetaliationMemorySec` decides
-- where the line falls, and a count that has gone stale is discarded rather
-- than decremented, because a victim either still resents it or does not.
--
-- Lives in the entry point rather than in `Retaliation.lua` because the load
-- screen clears the per-victim state before any part file has a chance to
-- create its own tables.
-- @table Annoyance
HorseCollisionMod.Annoyance = {}

--- Each victim's regard for the rider before the fight, keyed by entity id.
--
-- Recorded at the moment of provocation, which is still clean: the shoves
-- that lead up to it raise no crime and the provocation names the victim as
-- his own attacker, so neither touches reputation. The repair afterwards
-- restores this figure rather than a fixed amount, because a fixed amount
-- calibrated for a ruined victim overshoots and leaves a man who was beaten
-- thinking better of the rider than he did beforehand.
-- @table Baseline
HorseCollisionMod.Baseline = {}

--- Last time each entity was reported as a miss, keyed by entity id.
--- The broad phase result, reused until the horse has moved far enough to
-- need a fresh one.
--
-- `System.GetEntitiesInSphere` is the whole cost of the detection loop.
-- Measured in game it takes 0.10 ms for one entity inside a one meter sphere
-- and 0.43 ms for eight inside the shipped 2.5, while the footprint test and
-- everything else in the tick are too cheap to measure. Running it thirty
-- times a second is therefore the only part of this mod with a real budget.
--
-- It does not have to run every tick. The sphere reaches `HitRadius`, 2.5
-- meters, and the footprint can only ever reach `HorseFrontReach` plus
-- `MaxSweepExtra`, 1.4. Anyone outside the sphere is at least 1.1 meters from
-- the furthest the footprint reaches, so they cannot be hit until something
-- closes that gap. Re-querying when the horse has moved most of it, rather
-- than on a tick count, makes the saving independent of speed: a gallop
-- refreshes often and a trot rarely, which is the right way round.
--
-- @table SphereCache
HorseCollisionMod.SphereCache = { pos = nil, ents = nil, at = 0 }

--- How much of that margin the horse may use before the broad phase is redone.
--
-- The remaining 0.3 meters of the 1.1 covers the victim walking toward the
-- horse while the cache stands.
HorseCollisionMod.SphereCacheTravel = 0.8

--- The longest a broad phase result is trusted, in milliseconds.
--
-- A horse barely moving still lets people walk up to it. At a walking pace of
-- 1.5 meters a second a victim covers 0.22 meters in this time, inside the
-- allowance above.
HorseCollisionMod.SphereCacheMaxAgeMs = 150

HorseCollisionMod.RecentRejections = {}

--- When each speaker last said something, keyed by entity id.
--
-- Per speaker rather than global so two people can react to one event,
-- which is what lets a bystander answer a victim instead of the street
-- shouting in chorus.
HorseCollisionMod.RecentBarks = {}

--- Victims whose engine collision damage has been switched off.
HorseCollisionMod.ShieldedVictims = {}

--- The game's own non-persistent immortality buff, `imm=1`.
--
-- Non-persistent deliberately: it cannot be written into a save, so a victim
-- cannot be left permanently unkillable by a crash or a reload mid-window.
HorseCollisionMod.ImmortalityBuffGuid = "730503bf-735a-4f47-baae-c2d84ee77524"

--- When vanilla's collision bark was last switched off, by entity id.
--
-- Separate from `RecentBarks` because the two have different jobs: one
-- throttles how often somebody speaks, the other throttles how often a
-- context option is written while the horse bears down on them.
HorseCollisionMod.RecentHushes = {}

--- Recent horse speeds, newest last, for spotting deceleration on impact.
--
-- Speed is sampled once per tick at the top of the loop. A collision slows the
-- horse, so if a victim only enters the footprint on the tick after contact
-- begins, the speed read is the speed after the impact rather than the speed
-- that caused it. That would explain a gallop being recorded as a walk, and it
-- would also drop the reaction entirely whenever the loss takes the horse under
-- `SpeedWalk`, because that test returns before any entity is examined.
--
-- Kept deliberately short. Half a second of history is enough to see a
-- deceleration and not so much that an earlier gallop colors a later walk.
HorseCollisionMod.SpeedHistory = {}

HorseCollisionMod.SpeedHistorySize = 10


-- How long after a reaction begins the victim is rebuilt, per tier.
--
-- Timed from the start of the reaction, because nothing here reads whether the
-- victim is still on the ground, so the figure has to cover the whole fall and
-- get-up. Too short cuts the animation; every millisecond past the end is time
-- the victim spends standing idle before their own behavior resumes.
--
-- Separate per tier because a stagger is over in about a second while a
-- knockdown runs several times longer. Not settings: once these are right
-- there is no reason for a player to hold an opinion about them.
-- How the end of a reaction is recognized, so the rebuild is triggered by an
-- observation rather than by a clock guessing at the animation's length.
--
-- `actor:GetCurrentAnimationState()` reports `AnimationControlled` for exactly
-- as long as an interactive action owns the actor, and the value it changes to
-- afterwards is an ordinary locomotion state. Leaving that value is therefore
-- the reaction ending, whatever clip played and however long it ran.
--
-- A fixed delay cannot do this job. Measured across knockdowns the state was
-- held for anywhere between 4.3 and 7.0 seconds, and a stagger released it in
-- 2.3, so any single figure lands inside the range and rebuilds some victims
-- mid-animation. Rebuilding mid-animation is worse than not rebuilding at all,
-- because the animation takes the body back afterwards and the freeze the
-- rebuild exists to prevent happens anyway.
--
-- The ceiling covers a victim who dies, unstreams, or holds the state past
-- anything observed, and the state must have been seen at least once before
-- leaving it counts, so a poll landing before the action starts cannot be
-- mistaken for the reaction already being over.
HorseCollisionMod.ReactionAnimationState = "AnimationControlled"
HorseCollisionMod.ReactionPollMs = 100
HorseCollisionMod.ReactionEndCeilingMs = 12000


-- How long after the rebuild the victim is asked to re-plan. The rebuild
-- resets the behavior and the re-plan chooses what it does next, so they are
-- ordered rather than issued together.

--- How abruptly the replan is allowed to interrupt what the victim is doing.
--
-- `daycycleHaltSpeed` in the engine's type definitions: 0 slow, 1 fast,
-- 2 instant.
--
-- Vanilla reserves `instant` for teleports and cutscenes, where the screen is
-- faded or the character is being relocated outright, and a transition with no
-- wind-down is the point. Every vanilla call site that uses it is one of those.
-- Sent to an NPC standing in the street it reads as a one-frame snap, and the
-- activity it tears down takes any prop the NPC was holding with it.
HorseCollisionMod.ReplanHaltSpeed = 1

-- When to try setting a ragdolled victim's mass, in milliseconds from the
-- moment the reaction starts. Not an LDoc item: the generator rejects a
-- documented table that carries array entries.
--
-- A ladder rather than a single delay. Mass only takes once the body is
-- physicalized, and how long that takes is not fixed; the impulse path waits
-- `ImpulseDelayMs` for the same reason and was still measured applying to a
-- body that had not finished. Each rung is tried in turn and the first that
-- reads back is kept, so the telemetry reports which one won rather than the
-- code assuming one.
--
-- The rungs are tight because the horse is the thing being raced. At ten
-- meters per second it covers a centimeter every millisecond, so a mass that
-- arrives late arrives after the collision it was meant to change.
HorseCollisionMod.RagdollMassAttemptsMs = { 0, 16, 33, 50, 80, 120 }

--- How often a provoked victim is sampled while the incident is open.
--
-- A poll interval, not a duration: it decides how promptly the mod notices a
-- fight has ended, never how long the fight is allowed to last. One second is
-- fine for a state that changes on the scale of a scuffle, and it keeps the
-- telemetry readable rather than a wall of lines.
-- The per-tier tables live in HorseCollisionMod/Tiers.lua, which owns the tier
-- concept and the single accessor every one of them is read through.
HorseCollisionMod.RetaliationPollMs = 1000

--- Consecutive samples out of the fight before the incident is closed.
--
-- More than one, because a fighter between exchanges reads as finished for an
-- instant and closing there would cut a live fight short.
HorseCollisionMod.RetaliationSettledSamples = 3


--- The lowest a repair will leave a victim, whatever the arithmetic says.
--
-- Vanilla stops an NPC dealing with the player below 0.2, and below that he
-- decides to flee again every time he perceives the rider, which is what made
-- the damage look permanent. This sits above that rather than on it, so a
-- victim is never left balanced on the edge of it.
HorseCollisionMod.RepairFloor = 0.35

--- What losing the fight costs a victim permanently.
--
-- The repair deliberately does not restore a victim to exactly what he was.
-- He was ridden down and then beaten, and remembering it is correct; what is
-- not correct is being ruined for good. So the target is his own standing
-- less this, held above the floor above, which leaves a man who thinks less
-- of the rider than his neighbors do and still trades with him.
HorseCollisionMod.RepairFightCost = 0.15

--- How far one `surrender_step` moves a relationship.
--
-- Measured by applying it repeatedly from zero and reading between each: the
-- move is exactly 0.1389 every time, and the second argument the bind accepts
-- does not scale it. 0.1, 0.2 and no argument at all all produced the same
-- figure, so the count of applications is the only control there is.
--
-- `surrender_step` also cannot carry anyone past 0.8430, which the same sweep
-- reached and then stopped at.
HorseCollisionMod.RepairStepValue = 0.1389

--- A ceiling on the applications any single repair will make.
--
-- Nothing legitimate needs more: a victim at 0.0 restored to a townsman's
-- 0.35 takes three. It bounds a victim whose relationship cannot be read.
HorseCollisionMod.RepairMaxSteps = 5

--- Whether a yielding victim is stopped the instant the yield ends.
--
-- Off, and kept deliberately rather than because it is used. On the first
-- read after a surrender ends, the earliest the run can be caught at all, the
-- stand-down goes out and he never gets going: measured as
-- `YieldCaught state=MotionIdle stoodDown=true` with no run after it.
--
-- It is off because the run it prevents ends by itself, and stopping it hands
-- him to `state_standDown` and about twenty five seconds of standing still.
-- Turn it on only if a victim is ever seen running who should not be, and
-- expect that pause to come with it.
HorseCollisionMod.CatchYieldImmediately = false

--- How long after stopping him his standing is checked a second time.
HorseCollisionMod.AftermathSettleMs = 8000

--- The standing assumed for a victim nothing was recorded for.
--
-- Untouched townsmen sampled across a village all read 0.50.
HorseCollisionMod.RepairDefaultTarget = 0.50

--- How often a provoked victim is checked for having entered the fight.
--
-- Faster than the incident poll above, because this one is racing a victim
-- who is standing still and not fighting: every quarter second he spends in
-- a guard he was never going to break out of is a quarter second the shove
-- reads as having done nothing.
HorseCollisionMod.RetaliationReleaseMs = 250

--- How many of those checks are made before giving up on the release.
--
-- Twenty at a quarter second is five seconds, which is far longer than the
-- behavior tree takes to reach the fight subtree. Bounded so a victim who
-- never arrives, because the provocation was refused or he was interrupted,
-- cannot leave a timer running for the rest of the session.
HorseCollisionMod.RetaliationReleaseTries = 20


-- How the ragdoll handover is watched, for the tier that hands recovery back
-- to the game. `GetPhysicalizationProfile` reads `alive` throughout a ragdoll
-- and cannot be used; the animation state does report `BlendRagdoll`.
--
-- The ceiling is generous because this waits on the game's own recovery rather
-- than on a clip of known length.
--- How long an offset audio proxy is kept before it is removed.
--
-- One is created per distanced impact sound layer, so they must not
-- accumulate. Every sample the mod plays is well under a second, and the call
-- that creates the proxy was measured at four microseconds, so the lifetime is
-- the only part of this worth bounding at all.
HorseCollisionMod.AudioProxyLifetimeMs = 2000

HorseCollisionMod.RagdollAnimationState = "BlendRagdoll"

--- Every animation state that means the body is in a ragdoll.
--
-- The engine has one per context and the mod only ever knew the first. Counted
-- over a session's log, `CombatBlendRagdoll` appears 185 times against
-- `BlendRagdoll`'s 175, so more than half of all ragdolled victims were
-- invisible to every test that compared against the single name: whether a
-- victim was already down, whether they were flat, whether they had finished
-- getting up, whether their recovery line was due.
--
-- That is what made the mod's behavior depend on whether a victim happened to
-- be fighting, which reads from the saddle as random.
--- Victims whose fall clip has not yet handed the body to physics.
--
-- A `hcm_fall_` clip carries its ragdoll as a ProcLayer that fires partway
-- through it, so between the clip starting and that layer firing there is a
-- handover in flight. Starting a second clip on the same victim in that window
-- cancels it, and the canceled handover then lands against whatever the
-- victim is doing later: they collapse seconds after the impact if they are
-- idle, or are yanked limp in the middle of another clip, which lifts the body
-- and drops it.
--
-- The readiness cooldown used to prevent this as a side effect, and the diary
-- said so in as many words -- that it existed "to prevent ghost damage and the
-- awkward restart of a fall clip on a victim who is not standing". Removing
-- those timers removed that protection with them, which is what made both
-- symptoms reproducible.
--
-- Keyed by entity id, set when a fall clip starts and cleared when the body is
-- seen to ragdoll or the wait gives up.
HorseCollisionMod.FallPending = {}

HorseCollisionMod.RagdollAnimationStates = {
	BlendRagdoll = true,
	CombatBlendRagdoll = true,
}


-- The action hint slot the surrender prompt uses. An arbitrary id, chosen high
-- enough to stay clear of the ones vanilla raises for its own hints.
HorseCollisionMod.SurrenderHintId = 4771

-- How long `WhenVictimIsUp` waits for a victim to finish getting up before
-- firing anyway. A backstop for a victim never seen in the get-up at all,
-- because the reaction was suppressed or the impact killed them.
HorseCollisionMod.GetUpCeilingMs = 15000

-- How long `WhenRagdollLands` waits for a thrown body to come to rest before
-- giving up and firing anyway.
--
-- Its own rather than the resolve ceiling above, because it is waiting for a
-- much earlier and much shorter event. Measured across sixteen gallop impacts,
-- landing was reported between 1936ms and 2864ms, so three seconds covers
-- every real case with room to spare.
--
-- What the ceiling is actually for is the victim who never leaves the ground:
-- somebody who crumples or slides instead of flying keeps ground contact the
-- whole way, so the airborne half of the test never becomes true. On the
-- fifteen second ceiling that victim waited out the shield's own backstop and
-- spent nine seconds unprotected before their damage landed.
HorseCollisionMod.RagdollLandCeilingMs = 3000

-- What counts as a body having stopped, in meters moved between two polls, and
-- how often that is read. Shared by `ImpactThrow` and `WhenBodyStops` so the
-- mod has one definition of rest rather than two that disagree.
HorseCollisionMod.RestStillMeters = 0.05
HorseCollisionMod.RestPollMs = 200

-- The state an actor reports while one of this mod's reaction clips owns the
-- body. `WatchHitReady` treats it and the ragdoll state as the two ways a
-- victim can be busy; everything else is a victim on their feet.
HorseCollisionMod.ReactionAnimationState = "AnimationControlled"


--- Applies HorseCollisionMod_Settings.lua over the defaults above.
--
-- Settings live in their own file so that changing one does not mean opening
-- the mod's source at all. That file ships alongside this one in
-- `Scripts/Startup/` and defines a single global.
--
-- Startup scripts are loaded in name order, so the settings file runs after
-- this one and its global does not exist at the time this file is executed.
-- The merge therefore happens from the load screen, by which point everything
-- in `Scripts/Startup/` has run.
--
-- A key that is not already in Config is rejected rather than added. Config is
-- the list of settings that exist, so an unknown key means a typo, and adding
-- it would be silently ignored by whatever was supposed to read it. A wrong
-- type is rejected for the same reason. Both are logged, because a setting that
-- quietly does nothing is worse than one that visibly fails.
--
-- @treturn number settings applied
-- @treturn number entries rejected
function HorseCollisionMod:ApplySettings()
	local settings = rawget(_G, "HorseCollisionModSettings")

	if type(settings) ~= "table" then
		return 0, 0
	end

	local applied = 0
	local rejected = 0

	for key, value in pairs(settings) do
		local current = self.Config[key]

		if current == nil then
			self:Log("Setting '" .. tostring(key) .. "' is not a setting, ignored")
			rejected = rejected + 1
		elseif type(value) ~= type(current) then
			self:Log("Setting '" .. tostring(key) .. "' wants a "
					.. type(current) .. ", got " .. type(value) .. ", ignored")
			rejected = rejected + 1
		elseif value ~= current then
			self.Config[key] = value
			applied = applied + 1
		end
	end

	if self.Config.AutoGrantPerks then
		self:GrantPerks()
	end

	-- Global engine ragdoll stillness thresholds for recovery
	local threshold = self.Config.RagdollStillSpeedThreshold or 0.4
	System.SetCVar("wh_rd_StillSpeedThreshold", threshold)
	System.SetCVar("wh_rd_StillDuration", self.Config.RagdollStillDuration or 0.8)

	return applied, rejected
end

-- Entity classes whose animation database this mod redirects.
--
-- Documented as an ordinary comment rather than an LDoc block, for the reason
-- given on ImpactProbeSamples above: LDoc reads an annotated table as a set of
-- named fields, and one that only maps class names to a character set carries
-- nothing a per-field line would add.
--
-- Each entry maps an entity class table to the character set it belongs to.
--
-- Both the exposed classes and the `_x` templates they came from are listed,
-- and the distinction is the whole reason this works. `NPC_x` is a template;
-- `NPC.lua` does `NPC = CreateAI(NPC_x)`, and `CreateAI` builds a fresh table
-- and *copies* the fields in. So the live class holds a snapshot of the stock
-- paths taken when its script loaded, and redirecting only the template
-- changes nothing about what spawns.
--
-- The player class is declared
-- directly rather than through CreateAI, so redirecting it did work, which
-- made the mod's own files load and hid the fault.
-- The parent database is a few hundred bytes and holds no
-- fragments of its own; it references the untouched vanilla database inside its
-- own pak, plus this mod's fragment file.
--
-- This is what makes the mod additive. The alternative, and what 2.0.0 shipped,
-- is overriding kcd_male_database.adb outright, which means any other mod
-- touching human animations either loses its changes to this one or takes this
-- one's away depending only on mod_order.txt. Mannequin databases cannot be
-- merged, so that conflict is total and silent in both directions.
--
HorseCollisionMod.AnimationDatabases = {
	-- The exposed classes. These are what the engine spawns, and what has to
	-- be redirected for any of this to take effect.
	NPC           = "male",
	NPC_NAI       = "male",
	NullAI        = "male",
	DummyTarget   = "male",
	Player        = "male",
	NPC_Female    = "female",
	PlayerFemale  = "female",

	-- The templates they were built from. Redirected too, so that anything
	-- calling CreateAI after this point inherits the right paths rather than
	-- the stock ones.
	NPC_x         = "male",
	NPC_NAI_x     = "male",
	NullAI_x      = "male",
	DummyTarget_x = "male",
	NPC_Female_x  = "female",

	-- The horse, so a rear can be asked for. Its vanilla database has no
	-- `AnimationControlled` fragment at all, which is the only fragment
	-- `StartInteractiveActionByName` can reach.
	Horse         = "horse"
}
--- The parent database each character set uses.
--
-- Only `AnimDatabase3P` is redirected. `ActionController` deliberately is not:
-- leaving entities on vanilla's controller def means every fragment except
-- this mod's resolves through vanilla's own files, and the mod never appears
-- in the resolution path of animations it has nothing to do with.
--
-- Redirecting `ActionController` as well would let the stagger FragTags live
-- in a file named hcm_*, and it resolves correctly, but it puts a copied
-- fragment id file in the path of unrelated animations: the beggar's kneeling
-- resolves through BeggarIn and kcd_beggar_tags.xml by way of that same file,
-- and stops. The FragTags are declared in vanilla's own tag file instead,
-- which is 1 KB and costs no other animation its resolution path.
--
-- @table AnimationSets
HorseCollisionMod.AnimationSets = {
	male   = "Animations/Mannequin/ADB/hcm_male_database.adb",
	female = "Animations/Mannequin/ADB/hcm_female_database.adb",
	horse  = "Animations/Mannequin/ADB/hcm_horse_database.adb"
}

--- Points the redirected entity classes at this mod's parent databases.
--
-- AnimDatabase3P is read when an actor spawns, so this has to happen before the
-- world is populated. A Startup script runs early enough, but the entity class
-- tables are loaded on demand and may not all exist yet, hence the retry from
-- the load screen for any that were missing.
--
-- Redirecting a class twice is harmless, and a class that never appears is
-- skipped rather than treated as an error, so this is safe to call repeatedly.
--
-- @treturn number how many classes were redirected by this call
-- @treturn number how many are still waiting for their class table to exist
function HorseCollisionMod:RedirectAnimationDatabases()
	local redirected = 0
	local pending = 0

	for class, set in pairs(self.AnimationDatabases) do
		local target = rawget(_G, class)
		local database = self.AnimationSets[set]

		if type(target) ~= "table" then
			pending = pending + 1
		elseif target.AnimDatabase3P ~= database then
			target.AnimDatabase3P = database
			redirected = redirected + 1
		end
	end

	return redirected, pending
end

--- UI event handler that serves as the mod's entry point.
--
-- A Startup script has no general "game loaded" hook available to it, so the
-- end of the loading screen stands in for one.
--
-- @tparam string actionName UI action that fired
-- @tparam string eventName phase of that action
-- @tparam table argTable event arguments, unused
function HorseCollisionMod:uiActionListener(actionName, eventName, argTable)
	if HorseCollisionModListenerInstance and self ~= HorseCollisionModListenerInstance then
		return
	end

	if self.Config and self.Config.LogTelemetry then
		local a = string.lower(actionName or "")
		local e = string.lower(eventName or "")
		if string.match(a, "dialog") or string.match(e, "dialog")
			or string.match(a, "item") or string.match(e, "item")
			or string.match(a, "money") or string.match(e, "money")
			or string.match(a, "msg") or string.match(e, "msg")
			or string.match(a, "surrender") or string.match(e, "surrender")
			or string.match(a, "inventory") or string.match(e, "inventory") then
			self:Log("UIEvent action=" .. tostring(actionName) .. " event=" .. tostring(eventName))
		end
	end

	if actionName == "igm_inventory" then
		if eventName == "OnStart" then
			self.InventoryOpen = true
		elseif eventName == "OnEnd" then
			self.InventoryOpen = false
			self:CheckMenuTutorials()
		end
	end

	if actionName == "sys_loadingimagescreen" and eventName == "OnEnd" then
		HorseCollisionModGeneration = HorseCollisionModGeneration + 1

		local currentTick = HorseCollisionModGeneration

		self.TimerTick = currentTick

		-- Contact stamps are written against a clock the save restores, and
		-- the entity ids keying them are reused across a load. Neither
		-- survives the transition, so the tables are dropped rather than
		-- carried into a world they no longer describe.
		self.LastScoredHit = {}
		self.StandingHead = {}
		self.LockedUntil = {}
		self.RecentRejections = {}
		self.RecentBarks = {}
		self.RecentHushes = {}
		self.SphereCache = { pos = nil, ents = nil, at = 0 }

		-- The rear's cooldown is stamped the same way and was missed, which is
		-- the whole of why the rear keys were dead for an unpredictable stretch
		-- after a load. `System.GetCurrTime` is level time, and loading a save
		-- winds it back to the moment the save was written, so a deadline set
		-- before the save is still in the future in the world that comes back.
		-- Measured: presses reached the hook at +112 ms and were refused for
		-- cooldown 56 times before one was taken at +14.3 s.
		--
		-- The range of the symptom falls straight out of it. Rear, then save
		-- and load, and the wait is however far the clock moved; load without
		-- having reared and there is no deadline to wait for and the keys work
		-- at once.
		self.RearNextAt = nil

		-- The lean's re-base guard is stamped the same way, and was the other
		-- deadline missed when the rear's was fixed: `LeanHomeUntil` is set in
		-- `StopLean` against this same clock, and a load that winds the clock
		-- back leaves it in the future, so `StartLean` refuses every press
		-- until the clock catches up. `LeanHeld` is dropped too, since a save
		-- written mid-lean would otherwise come back holding a sign that
		-- nothing can ever release, permanently refusing `StartLean`.
		self.LeanHomeUntil = nil
		self.LeanHeld = nil
		self.LeanLastFlip = nil
		self.LeanGeneration = (self.LeanGeneration or 0) + 1

		self.VictimActivity = {}
		self.SurrenderHintFor = {}
		self.Annoyance = {}
		self.WasMounted = false

		-- A hint showing when the game was saved would come back with the
		-- save and never be taken down, since the fight that raised it is
		-- gone.
		self:HideSurrenderHint(true)
		self.Baseline = {}

		local applied, rejected = self:ApplySettings()

		if applied > 0 or rejected > 0 then
			self:Log("Settings: " .. tostring(applied) .. " applied, "
					.. tostring(rejected) .. " ignored")
		end

		if self.Config.AutoGrantPerks then
			self:GrantPerks()
		end

		if self.SyncTutorialsOnLoad then
			self:SyncTutorialsOnLoad()
		end

		self:HookRearKey()
		self:LoadRearActionMap()

		local again = self:RedirectAnimationDatabases()

		if again > 0 then
			self:Log("Redirected " .. tostring(again)
					.. " animation databases that loaded late")
		end

		self:Log("Load screen ended. v" .. self.Version
				.. " initializing physics timer loop "
				.. tostring(currentTick))

		Script.SetTimer(self:TickMs(), function()
			HorseCollisionMod:UpdateTimer(currentTick)
		end)
	end
end

-- The rest of the mod, named explicitly and in the order it is wanted.
--
-- `Script.ReloadScript` is how the base game composes its own Lua: it is the
-- first line of nearly every vanilla entity script and is what
-- `Scripts/common.lua` uses to pull in its utility files. It is synchronous
-- and resolves the path through the merged pak filesystem, so a part file is
-- fully defined by the time the next line runs.
--
-- The parts live outside `Scripts/Startup/` on purpose. The engine enumerates
-- that folder and executes what it finds, in no guaranteed order, which would
-- both run a part before this table exists and run it a second time. Only the
-- entry point is enumerated; everything else is named here.
--
-- Loaded at the foot of the file rather than the head so that every part can
-- rely on the whole entry point being defined, and so the bootstrap below,
-- which calls into the mod, runs after the parts are in place. Each part adds
-- to the table above and carries no top-level statements, so the reload the
-- dev console fires cascades through them harmlessly.
Script.ReloadScript("Scripts/HorseCollisionMod/Enums.lua")
Script.ReloadScript("Scripts/HorseCollisionMod/Tiers.lua")
Script.ReloadScript("Scripts/HorseCollisionMod/Log.lua")
Script.ReloadScript("Scripts/HorseCollisionMod/Armor.lua")
Script.ReloadScript("Scripts/HorseCollisionMod/Detection.lua")
Script.ReloadScript("Scripts/HorseCollisionMod/Health.lua")
Script.ReloadScript("Scripts/HorseCollisionMod/Reaction.lua")
Script.ReloadScript("Scripts/HorseCollisionMod/Marks.lua")
Script.ReloadScript("Scripts/HorseCollisionMod/Sound.lua")
Script.ReloadScript("Scripts/HorseCollisionMod/Bark.lua")
Script.ReloadScript("Scripts/HorseCollisionMod/Recovery.lua")
Script.ReloadScript("Scripts/HorseCollisionMod/Crime.lua")
Script.ReloadScript("Scripts/HorseCollisionMod/Retaliation.lua")
Script.ReloadScript("Scripts/HorseCollisionMod/Rider.lua")
Script.ReloadScript("Scripts/HorseCollisionMod/Lean.lua")
Script.ReloadScript("Scripts/HorseCollisionMod/Rear.lua")
Script.ReloadScript("Scripts/HorseCollisionMod/Fear.lua")
Script.ReloadScript("Scripts/HorseCollisionMod/Impact.lua")
Script.ReloadScript("Scripts/HorseCollisionMod/Tutorial.lua")
Script.ReloadScript("Scripts/HorseCollisionMod/Update.lua")

-- Runs at file scope rather than from the load screen, because
-- AnimDatabase3P is read when an actor spawns and the load screen ends
-- after the world is already populated.
local hcmRedirected, hcmPending = HorseCollisionMod:RedirectAnimationDatabases()

HorseCollisionMod:Log("Redirected " .. tostring(hcmRedirected)
		.. " animation databases, " .. tostring(hcmPending) .. " pending")

if type(UIAction) == "table" then
	if type(UIAction.UnregisterActionListener) == "function"
			and HorseCollisionModListenerInstance then
		pcall(function()
			UIAction.UnregisterActionListener(HorseCollisionModListenerInstance,
					"", "", "uiActionListener")
		end)
	end

	if type(UIAction.RegisterActionListener) == "function" then
		UIAction.RegisterActionListener(HorseCollisionMod, "", "", "uiActionListener")
		HorseCollisionModListenerInstance = HorseCollisionMod
	end
end
